/PROG  B0001X1000.LS
/ATTR
OWNER       = MNEDITOR;
COMMENT     = "";
PROG_SIZE   = 636;
CREATE      = DATE 23-01-07  TIME 11:59:14;
MODIFIED    = DATE 23-01-07  TIME 12:02:18;
FILE_NAME   = ;
VERSION     = 0;
LINE_COUNT  = 4;
MEMORY_SIZE = 992;
PROTECT     = READ_WRITE;
TCD:  STACK_SIZE    = 0,
      TASK_PRIORITY = 50,
      TIME_SLICE    = 0,
      BUSY_LAMP_OFF = 0,
      ABORT_REQUEST = 0,
      PAUSE_REQUEST = 0;
DEFAULT_GROUP    = 1,*,*,*,*;
CONTROL_CODE     = 00000000 00000000;
/MN
   1:J P[1] 100% FINE    ;
   2:L P[2] 100mm/sec CNT100    ;
   3:L P[3] 100mm/sec CNT100    ;
   4:L P[4] 100mm/sec CNT100    ;
   5:L P[5] 100mm/sec CNT100    ;
   6:L P[6] 100mm/sec CNT100    ;
   7:L P[7] 100mm/sec CNT100    ;
   8:L P[8] 100mm/sec CNT100    ;
   9:L P[9] 100mm/sec CNT100    ;
   10:L P[10] 100mm/sec CNT100    ;
   11:L P[11] 100mm/sec CNT100    ;
   12:L P[12] 100mm/sec CNT100    ;
   13:L P[13] 100mm/sec CNT100    ;
   14:L P[14] 100mm/sec CNT100    ;
   15:L P[15] 100mm/sec CNT100    ;
   16:L P[16] 100mm/sec CNT100    ;
   17:L P[17] 100mm/sec CNT100    ;
   18:L P[18] 100mm/sec CNT100    ;
   19:L P[19] 100mm/sec CNT100    ;
   20:L P[20] 100mm/sec CNT100    ;
   21:L P[21] 100mm/sec CNT100    ;
   22:L P[22] 100mm/sec CNT100    ;
   23:L P[23] 100mm/sec CNT100    ;
   24:L P[24] 100mm/sec CNT100    ;
   25:L P[25] 100mm/sec CNT100    ;
   26:L P[26] 100mm/sec CNT100    ;
   27:L P[27] 100mm/sec CNT100    ;
   28:L P[28] 100mm/sec CNT100    ;
   29:L P[29] 100mm/sec CNT100    ;
   30:L P[30] 100mm/sec CNT100    ;
   31:L P[31] 100mm/sec CNT100    ;
   32:L P[32] 100mm/sec CNT100    ;
   33:L P[33] 100mm/sec CNT100    ;
   34:L P[34] 100mm/sec CNT100    ;
   35:L P[35] 100mm/sec CNT100    ;
   36:L P[36] 100mm/sec CNT100    ;
   37:L P[37] 100mm/sec CNT100    ;
   38:L P[38] 100mm/sec CNT100    ;
   39:L P[39] 100mm/sec CNT100    ;
   40:L P[40] 100mm/sec CNT100    ;
   41:L P[41] 100mm/sec CNT100    ;
   42:L P[42] 100mm/sec CNT100    ;
   43:L P[43] 100mm/sec CNT100    ;
   44:L P[44] 100mm/sec CNT100    ;
   45:L P[45] 100mm/sec CNT100    ;
   46:L P[46] 100mm/sec CNT100    ;
   47:L P[47] 100mm/sec CNT100    ;
   48:L P[48] 100mm/sec CNT100    ;
   49:L P[49] 100mm/sec CNT100    ;
   50:L P[50] 100mm/sec CNT100    ;
   51:L P[51] 100mm/sec CNT100    ;
   52:L P[52] 100mm/sec CNT100    ;
   53:L P[53] 100mm/sec CNT100    ;
   54:L P[54] 100mm/sec CNT100    ;
   55:L P[55] 100mm/sec CNT100    ;
   56:L P[56] 100mm/sec CNT100    ;
   57:L P[57] 100mm/sec CNT100    ;
   58:L P[58] 100mm/sec CNT100    ;
   59:L P[59] 100mm/sec CNT100    ;
   60:L P[60] 100mm/sec CNT100    ;
   61:L P[61] 100mm/sec CNT100    ;
   62:L P[62] 100mm/sec CNT100    ;
   63:L P[63] 100mm/sec CNT100    ;
   64:L P[64] 100mm/sec CNT100    ;
   65:L P[65] 100mm/sec CNT100    ;
   66:L P[66] 100mm/sec CNT100    ;
   67:L P[67] 100mm/sec CNT100    ;
   68:L P[68] 100mm/sec CNT100    ;
   69:L P[69] 100mm/sec CNT100    ;
   70:L P[70] 100mm/sec CNT100    ;
   71:L P[71] 100mm/sec CNT100    ;
   72:L P[72] 100mm/sec CNT100    ;
   73:L P[73] 100mm/sec CNT100    ;
   74:L P[74] 100mm/sec CNT100    ;
   75:L P[75] 100mm/sec CNT100    ;
   76:L P[76] 100mm/sec CNT100    ;
   77:L P[77] 100mm/sec CNT100    ;
   78:L P[78] 100mm/sec CNT100    ;
   79:L P[79] 100mm/sec CNT100    ;
   80:L P[80] 100mm/sec CNT100    ;
   81:L P[81] 100mm/sec CNT100    ;
   82:L P[82] 100mm/sec CNT100    ;
   83:L P[83] 100mm/sec CNT100    ;
   84:L P[84] 100mm/sec CNT100    ;
   85:L P[85] 100mm/sec CNT100    ;
   86:L P[86] 100mm/sec CNT100    ;
   87:L P[87] 100mm/sec CNT100    ;
   88:L P[88] 100mm/sec CNT100    ;
   89:L P[89] 100mm/sec CNT100    ;
   90:L P[90] 100mm/sec CNT100    ;
   91:L P[91] 100mm/sec CNT100    ;
   92:L P[92] 100mm/sec CNT100    ;
   93:L P[93] 100mm/sec CNT100    ;
   94:L P[94] 100mm/sec CNT100    ;
   95:L P[95] 100mm/sec CNT100    ;
   96:L P[96] 100mm/sec CNT100    ;
   97:L P[97] 100mm/sec CNT100    ;
   98:L P[98] 100mm/sec CNT100    ;
   99:L P[99] 100mm/sec CNT100    ;
   100:L P[100] 100mm/sec CNT100    ;
   101:L P[101] 100mm/sec CNT100    ;
   102:L P[102] 100mm/sec CNT100    ;
   103:L P[103] 100mm/sec CNT100    ;
   104:L P[104] 100mm/sec CNT100    ;
   105:L P[105] 100mm/sec CNT100    ;
   106:L P[106] 100mm/sec CNT100    ;
   107:L P[107] 100mm/sec CNT100    ;
   108:L P[108] 100mm/sec CNT100    ;
   109:L P[109] 100mm/sec CNT100    ;
   110:L P[110] 100mm/sec CNT100    ;
   111:L P[111] 100mm/sec CNT100    ;
   112:L P[112] 100mm/sec CNT100    ;
   113:L P[113] 100mm/sec CNT100    ;
   114:L P[114] 100mm/sec CNT100    ;
   115:L P[115] 100mm/sec CNT100    ;
   116:L P[116] 100mm/sec CNT100    ;
   117:L P[117] 100mm/sec CNT100    ;
   118:L P[118] 100mm/sec CNT100    ;
   119:L P[119] 100mm/sec CNT100    ;
   120:L P[120] 100mm/sec CNT100    ;
   121:L P[121] 100mm/sec CNT100    ;
   122:L P[122] 100mm/sec CNT100    ;
   123:L P[123] 100mm/sec CNT100    ;
   124:L P[124] 100mm/sec CNT100    ;
   125:L P[125] 100mm/sec CNT100    ;
   126:L P[126] 100mm/sec CNT100    ;
   127:L P[127] 100mm/sec CNT100    ;
   128:L P[128] 100mm/sec CNT100    ;
   129:L P[129] 100mm/sec CNT100    ;
   130:L P[130] 100mm/sec CNT100    ;
   131:L P[131] 100mm/sec CNT100    ;
   132:L P[132] 100mm/sec CNT100    ;
   133:L P[133] 100mm/sec CNT100    ;
   134:L P[134] 100mm/sec CNT100    ;
   135:L P[135] 100mm/sec CNT100    ;
   136:L P[136] 100mm/sec CNT100    ;
   137:L P[137] 100mm/sec CNT100    ;
   138:L P[138] 100mm/sec CNT100    ;
   139:L P[139] 100mm/sec CNT100    ;
   140:L P[140] 100mm/sec CNT100    ;
   141:L P[141] 100mm/sec CNT100    ;
   142:L P[142] 100mm/sec CNT100    ;
   143:L P[143] 100mm/sec CNT100    ;
   144:L P[144] 100mm/sec CNT100    ;
   145:L P[145] 100mm/sec CNT100    ;
   146:L P[146] 100mm/sec CNT100    ;
   147:L P[147] 100mm/sec CNT100    ;
   148:L P[148] 100mm/sec CNT100    ;
   149:L P[149] 100mm/sec CNT100    ;
   150:L P[150] 100mm/sec CNT100    ;
   151:L P[151] 100mm/sec CNT100    ;
   152:L P[152] 100mm/sec CNT100    ;
   153:L P[153] 100mm/sec CNT100    ;
   154:L P[154] 100mm/sec CNT100    ;
   155:L P[155] 100mm/sec CNT100    ;
   156:L P[156] 100mm/sec CNT100    ;
   157:L P[157] 100mm/sec CNT100    ;
   158:L P[158] 100mm/sec CNT100    ;
   159:L P[159] 100mm/sec CNT100    ;
   160:L P[160] 100mm/sec CNT100    ;
   161:L P[161] 100mm/sec CNT100    ;
   162:L P[162] 100mm/sec CNT100    ;
   163:L P[163] 100mm/sec CNT100    ;
   164:L P[164] 100mm/sec CNT100    ;
   165:L P[165] 100mm/sec CNT100    ;
   166:L P[166] 100mm/sec CNT100    ;
   167:L P[167] 100mm/sec CNT100    ;
   168:L P[168] 100mm/sec CNT100    ;
   169:L P[169] 100mm/sec CNT100    ;
   170:L P[170] 100mm/sec CNT100    ;
   171:L P[171] 100mm/sec CNT100    ;
   172:L P[172] 100mm/sec CNT100    ;
   173:L P[173] 100mm/sec CNT100    ;
   174:L P[174] 100mm/sec CNT100    ;
   175:L P[175] 100mm/sec CNT100    ;
   176:L P[176] 100mm/sec CNT100    ;
   177:L P[177] 100mm/sec CNT100    ;
   178:L P[178] 100mm/sec CNT100    ;
   179:L P[179] 100mm/sec CNT100    ;
   180:L P[180] 100mm/sec CNT100    ;
   181:L P[181] 100mm/sec CNT100    ;
   182:L P[182] 100mm/sec CNT100    ;
   183:L P[183] 100mm/sec CNT100    ;
   184:L P[184] 100mm/sec CNT100    ;
   185:L P[185] 100mm/sec CNT100    ;
   186:L P[186] 100mm/sec CNT100    ;
   187:L P[187] 100mm/sec CNT100    ;
   188:L P[188] 100mm/sec CNT100    ;
   189:L P[189] 100mm/sec CNT100    ;
   190:L P[190] 100mm/sec CNT100    ;
   191:L P[191] 100mm/sec CNT100    ;
   192:L P[192] 100mm/sec CNT100    ;
   193:L P[193] 100mm/sec CNT100    ;
   194:L P[194] 100mm/sec CNT100    ;
   195:L P[195] 100mm/sec CNT100    ;
   196:L P[196] 100mm/sec CNT100    ;
   197:L P[197] 100mm/sec CNT100    ;
   198:L P[198] 100mm/sec CNT100    ;
   199:L P[199] 100mm/sec CNT100    ;
   200:L P[200] 100mm/sec CNT100    ;
   201:L P[201] 100mm/sec CNT100    ;
   202:L P[202] 100mm/sec CNT100    ;
   203:L P[203] 100mm/sec CNT100    ;
   204:L P[204] 100mm/sec CNT100    ;
   205:L P[205] 100mm/sec CNT100    ;
   206:L P[206] 100mm/sec CNT100    ;
   207:L P[207] 100mm/sec CNT100    ;
   208:L P[208] 100mm/sec CNT100    ;
   209:L P[209] 100mm/sec CNT100    ;
   210:L P[210] 100mm/sec CNT100    ;
   211:L P[211] 100mm/sec CNT100    ;
   212:L P[212] 100mm/sec CNT100    ;
   213:L P[213] 100mm/sec CNT100    ;
   214:L P[214] 100mm/sec CNT100    ;
   215:L P[215] 100mm/sec CNT100    ;
   216:L P[216] 100mm/sec CNT100    ;
   217:L P[217] 100mm/sec CNT100    ;
   218:L P[218] 100mm/sec CNT100    ;
   219:L P[219] 100mm/sec CNT100    ;
   220:L P[220] 100mm/sec CNT100    ;
   221:L P[221] 100mm/sec CNT100    ;
   222:L P[222] 100mm/sec CNT100    ;
   223:L P[223] 100mm/sec CNT100    ;
   224:L P[224] 100mm/sec CNT100    ;
   225:L P[225] 100mm/sec CNT100    ;
   226:L P[226] 100mm/sec CNT100    ;
   227:L P[227] 100mm/sec CNT100    ;
   228:L P[228] 100mm/sec CNT100    ;
   229:L P[229] 100mm/sec CNT100    ;
   230:L P[230] 100mm/sec CNT100    ;
   231:L P[231] 100mm/sec CNT100    ;
   232:L P[232] 100mm/sec CNT100    ;
   233:L P[233] 100mm/sec CNT100    ;
   234:L P[234] 100mm/sec CNT100    ;
   235:L P[235] 100mm/sec CNT100    ;
   236:L P[236] 100mm/sec CNT100    ;
   237:L P[237] 100mm/sec CNT100    ;
   238:L P[238] 100mm/sec CNT100    ;
   239:L P[239] 100mm/sec CNT100    ;
   240:L P[240] 100mm/sec CNT100    ;
   241:L P[241] 100mm/sec CNT100    ;
   242:L P[242] 100mm/sec CNT100    ;
   243:L P[243] 100mm/sec CNT100    ;
   244:L P[244] 100mm/sec CNT100    ;
   245:L P[245] 100mm/sec CNT100    ;
   246:L P[246] 100mm/sec CNT100    ;
   247:L P[247] 100mm/sec CNT100    ;
   248:L P[248] 100mm/sec CNT100    ;
   249:L P[249] 100mm/sec CNT100    ;
   250:L P[250] 100mm/sec CNT100    ;
   251:L P[251] 100mm/sec CNT100    ;
   252:L P[252] 100mm/sec CNT100    ;
   253:L P[253] 100mm/sec CNT100    ;
   254:L P[254] 100mm/sec CNT100    ;
   255:L P[255] 100mm/sec CNT100    ;
   256:L P[256] 100mm/sec CNT100    ;
   257:L P[257] 100mm/sec CNT100    ;
   258:L P[258] 100mm/sec CNT100    ;
   259:L P[259] 100mm/sec CNT100    ;
   260:L P[260] 100mm/sec CNT100    ;
   261:L P[261] 100mm/sec CNT100    ;
   262:L P[262] 100mm/sec CNT100    ;
   263:L P[263] 100mm/sec CNT100    ;
   264:L P[264] 100mm/sec CNT100    ;
   265:L P[265] 100mm/sec CNT100    ;
   266:L P[266] 100mm/sec CNT100    ;
   267:L P[267] 100mm/sec CNT100    ;
   268:L P[268] 100mm/sec CNT100    ;
   269:L P[269] 100mm/sec CNT100    ;
   270:L P[270] 100mm/sec CNT100    ;
   271:L P[271] 100mm/sec CNT100    ;
   272:L P[272] 100mm/sec CNT100    ;
   273:L P[273] 100mm/sec CNT100    ;
   274:L P[274] 100mm/sec CNT100    ;
   275:L P[275] 100mm/sec CNT100    ;
   276:L P[276] 100mm/sec CNT100    ;
   277:L P[277] 100mm/sec CNT100    ;
   278:L P[278] 100mm/sec CNT100    ;
   279:L P[279] 100mm/sec CNT100    ;
   280:L P[280] 100mm/sec CNT100    ;
   281:L P[281] 100mm/sec CNT100    ;
   282:L P[282] 100mm/sec CNT100    ;
   283:L P[283] 100mm/sec CNT100    ;
   284:L P[284] 100mm/sec CNT100    ;
   285:L P[285] 100mm/sec CNT100    ;
   286:L P[286] 100mm/sec CNT100    ;
   287:L P[287] 100mm/sec CNT100    ;
   288:L P[288] 100mm/sec CNT100    ;
   289:L P[289] 100mm/sec CNT100    ;
   290:L P[290] 100mm/sec CNT100    ;
   291:L P[291] 100mm/sec CNT100    ;
   292:L P[292] 100mm/sec CNT100    ;
   293:L P[293] 100mm/sec CNT100    ;
   294:L P[294] 100mm/sec CNT100    ;
   295:L P[295] 100mm/sec CNT100    ;
   296:L P[296] 100mm/sec CNT100    ;
   297:L P[297] 100mm/sec CNT100    ;
   298:L P[298] 100mm/sec CNT100    ;
   299:L P[299] 100mm/sec CNT100    ;
   300:L P[300] 100mm/sec CNT100    ;
   301:L P[301] 100mm/sec CNT100    ;
   302:L P[302] 100mm/sec CNT100    ;
   303:L P[303] 100mm/sec CNT100    ;
   304:L P[304] 100mm/sec CNT100    ;
   305:L P[305] 100mm/sec CNT100    ;
   306:L P[306] 100mm/sec CNT100    ;
   307:L P[307] 100mm/sec CNT100    ;
   308:L P[308] 100mm/sec CNT100    ;
   309:L P[309] 100mm/sec CNT100    ;
   310:L P[310] 100mm/sec CNT100    ;
   311:L P[311] 100mm/sec CNT100    ;
   312:L P[312] 100mm/sec CNT100    ;
   313:L P[313] 100mm/sec CNT100    ;
   314:L P[314] 100mm/sec CNT100    ;
   315:L P[315] 100mm/sec CNT100    ;
   316:L P[316] 100mm/sec CNT100    ;
   317:L P[317] 100mm/sec CNT100    ;
   318:L P[318] 100mm/sec CNT100    ;
   319:L P[319] 100mm/sec CNT100    ;
   320:L P[320] 100mm/sec CNT100    ;
   321:L P[321] 100mm/sec CNT100    ;
   322:L P[322] 100mm/sec CNT100    ;
   323:L P[323] 100mm/sec CNT100    ;
   324:L P[324] 100mm/sec CNT100    ;
   325:L P[325] 100mm/sec CNT100    ;
   326:L P[326] 100mm/sec CNT100    ;
   327:L P[327] 100mm/sec CNT100    ;
   328:L P[328] 100mm/sec CNT100    ;
   329:L P[329] 100mm/sec CNT100    ;
   330:L P[330] 100mm/sec CNT100    ;
   331:L P[331] 100mm/sec CNT100    ;
   332:L P[332] 100mm/sec CNT100    ;
   333:L P[333] 100mm/sec CNT100    ;
   334:L P[334] 100mm/sec CNT100    ;
   335:L P[335] 100mm/sec CNT100    ;
   336:L P[336] 100mm/sec CNT100    ;
   337:L P[337] 100mm/sec CNT100    ;
   338:L P[338] 100mm/sec CNT100    ;
   339:L P[339] 100mm/sec CNT100    ;
   340:L P[340] 100mm/sec CNT100    ;
   341:L P[341] 100mm/sec CNT100    ;
   342:L P[342] 100mm/sec CNT100    ;
   343:L P[343] 100mm/sec CNT100    ;
   344:L P[344] 100mm/sec CNT100    ;
   345:L P[345] 100mm/sec CNT100    ;
   346:L P[346] 100mm/sec CNT100    ;
   347:L P[347] 100mm/sec CNT100    ;
   348:L P[348] 100mm/sec CNT100    ;
   349:L P[349] 100mm/sec CNT100    ;
   350:L P[350] 100mm/sec CNT100    ;
   351:L P[351] 100mm/sec CNT100    ;
   352:L P[352] 100mm/sec CNT100    ;
   353:L P[353] 100mm/sec CNT100    ;
   354:L P[354] 100mm/sec CNT100    ;
   355:L P[355] 100mm/sec CNT100    ;
   356:L P[356] 100mm/sec CNT100    ;
   357:L P[357] 100mm/sec CNT100    ;
   358:L P[358] 100mm/sec CNT100    ;
   359:L P[359] 100mm/sec CNT100    ;
   360:L P[360] 100mm/sec CNT100    ;
   361:L P[361] 100mm/sec CNT100    ;
   362:L P[362] 100mm/sec CNT100    ;
   363:L P[363] 100mm/sec CNT100    ;
   364:L P[364] 100mm/sec CNT100    ;
   365:L P[365] 100mm/sec CNT100    ;
   366:L P[366] 100mm/sec CNT100    ;
   367:L P[367] 100mm/sec CNT100    ;
   368:L P[368] 100mm/sec CNT100    ;
   369:L P[369] 100mm/sec CNT100    ;
   370:L P[370] 100mm/sec CNT100    ;
   371:L P[371] 100mm/sec CNT100    ;
   372:L P[372] 100mm/sec CNT100    ;
   373:L P[373] 100mm/sec CNT100    ;
   374:L P[374] 100mm/sec CNT100    ;
   375:L P[375] 100mm/sec CNT100    ;
   376:L P[376] 100mm/sec CNT100    ;
   377:L P[377] 100mm/sec CNT100    ;
   378:L P[378] 100mm/sec CNT100    ;
   379:L P[379] 100mm/sec CNT100    ;
   380:L P[380] 100mm/sec CNT100    ;
   381:L P[381] 100mm/sec CNT100    ;
   382:L P[382] 100mm/sec CNT100    ;
   383:L P[383] 100mm/sec CNT100    ;
   384:L P[384] 100mm/sec CNT100    ;
   385:L P[385] 100mm/sec CNT100    ;
   386:L P[386] 100mm/sec CNT100    ;
   387:L P[387] 100mm/sec CNT100    ;
   388:L P[388] 100mm/sec CNT100    ;
   389:L P[389] 100mm/sec CNT100    ;
   390:L P[390] 100mm/sec CNT100    ;
   391:L P[391] 100mm/sec CNT100    ;
   392:L P[392] 100mm/sec CNT100    ;
   393:L P[393] 100mm/sec CNT100    ;
   394:L P[394] 100mm/sec CNT100    ;
   395:L P[395] 100mm/sec CNT100    ;
   396:L P[396] 100mm/sec CNT100    ;
   397:L P[397] 100mm/sec CNT100    ;
   398:L P[398] 100mm/sec CNT100    ;
   399:L P[399] 100mm/sec CNT100    ;
   400:L P[400] 100mm/sec CNT100    ;
   401:L P[401] 100mm/sec CNT100    ;
   402:L P[402] 100mm/sec CNT100    ;
   403:L P[403] 100mm/sec CNT100    ;
   404:L P[404] 100mm/sec CNT100    ;
   405:L P[405] 100mm/sec CNT100    ;
   406:L P[406] 100mm/sec CNT100    ;
   407:L P[407] 100mm/sec CNT100    ;
   408:L P[408] 100mm/sec CNT100    ;
   409:L P[409] 100mm/sec CNT100    ;
   410:L P[410] 100mm/sec CNT100    ;
   411:L P[411] 100mm/sec CNT100    ;
   412:L P[412] 100mm/sec CNT100    ;
   413:L P[413] 100mm/sec CNT100    ;
   414:L P[414] 100mm/sec CNT100    ;
   415:L P[415] 100mm/sec CNT100    ;
   416:L P[416] 100mm/sec CNT100    ;
   417:L P[417] 100mm/sec CNT100    ;
   418:L P[418] 100mm/sec CNT100    ;
   419:L P[419] 100mm/sec CNT100    ;
   420:L P[420] 100mm/sec CNT100    ;
   421:L P[421] 100mm/sec CNT100    ;
   422:L P[422] 100mm/sec CNT100    ;
   423:L P[423] 100mm/sec CNT100    ;
   424:L P[424] 100mm/sec CNT100    ;
   425:L P[425] 100mm/sec CNT100    ;
   426:L P[426] 100mm/sec CNT100    ;
   427:L P[427] 100mm/sec CNT100    ;
   428:L P[428] 100mm/sec CNT100    ;
   429:L P[429] 100mm/sec CNT100    ;
   430:L P[430] 100mm/sec CNT100    ;
   431:L P[431] 100mm/sec CNT100    ;
   432:L P[432] 100mm/sec CNT100    ;
   433:L P[433] 100mm/sec CNT100    ;
   434:L P[434] 100mm/sec CNT100    ;
   435:L P[435] 100mm/sec CNT100    ;
   436:L P[436] 100mm/sec CNT100    ;
   437:L P[437] 100mm/sec CNT100    ;
   438:L P[438] 100mm/sec CNT100    ;
   439:L P[439] 100mm/sec CNT100    ;
   440:L P[440] 100mm/sec CNT100    ;
   441:L P[441] 100mm/sec CNT100    ;
   442:L P[442] 100mm/sec CNT100    ;
   443:L P[443] 100mm/sec CNT100    ;
   444:L P[444] 100mm/sec CNT100    ;
   445:L P[445] 100mm/sec CNT100    ;
   446:L P[446] 100mm/sec CNT100    ;
   447:L P[447] 100mm/sec CNT100    ;
   448:L P[448] 100mm/sec CNT100    ;
   449:L P[449] 100mm/sec CNT100    ;
   450:L P[450] 100mm/sec CNT100    ;
   451:L P[451] 100mm/sec CNT100    ;
   452:L P[452] 100mm/sec CNT100    ;
   453:L P[453] 100mm/sec CNT100    ;
   454:L P[454] 100mm/sec CNT100    ;
   455:L P[455] 100mm/sec CNT100    ;
   456:L P[456] 100mm/sec CNT100    ;
   457:L P[457] 100mm/sec CNT100    ;
   458:L P[458] 100mm/sec CNT100    ;
   459:L P[459] 100mm/sec CNT100    ;
   460:L P[460] 100mm/sec CNT100    ;
   461:L P[461] 100mm/sec CNT100    ;
   462:L P[462] 100mm/sec CNT100    ;
   463:L P[463] 100mm/sec CNT100    ;
   464:L P[464] 100mm/sec CNT100    ;
   465:L P[465] 100mm/sec CNT100    ;
   466:L P[466] 100mm/sec CNT100    ;
   467:L P[467] 100mm/sec CNT100    ;
   468:L P[468] 100mm/sec CNT100    ;
   469:L P[469] 100mm/sec CNT100    ;
   470:L P[470] 100mm/sec CNT100    ;
   471:L P[471] 100mm/sec CNT100    ;
   472:L P[472] 100mm/sec CNT100    ;
   473:L P[473] 100mm/sec CNT100    ;
   474:L P[474] 100mm/sec CNT100    ;
   475:L P[475] 100mm/sec CNT100    ;
   476:L P[476] 100mm/sec CNT100    ;
   477:L P[477] 100mm/sec CNT100    ;
   478:L P[478] 100mm/sec CNT100    ;
   479:L P[479] 100mm/sec CNT100    ;
   480:L P[480] 100mm/sec CNT100    ;
   481:L P[481] 100mm/sec CNT100    ;
   482:L P[482] 100mm/sec CNT100    ;
   483:L P[483] 100mm/sec CNT100    ;
   484:L P[484] 100mm/sec CNT100    ;
   485:L P[485] 100mm/sec CNT100    ;
   486:L P[486] 100mm/sec CNT100    ;
   487:L P[487] 100mm/sec CNT100    ;
   488:L P[488] 100mm/sec CNT100    ;
   489:L P[489] 100mm/sec CNT100    ;
   490:L P[490] 100mm/sec CNT100    ;
   491:L P[491] 100mm/sec CNT100    ;
   492:L P[492] 100mm/sec CNT100    ;
   493:L P[493] 100mm/sec CNT100    ;
   494:L P[494] 100mm/sec CNT100    ;
   495:L P[495] 100mm/sec CNT100    ;
   496:L P[496] 100mm/sec CNT100    ;
   497:L P[497] 100mm/sec CNT100    ;
   498:L P[498] 100mm/sec CNT100    ;
   499:L P[499] 100mm/sec CNT100    ;
   500:L P[500] 100mm/sec CNT100    ;
   501:L P[501] 100mm/sec CNT100    ;
   502:L P[502] 100mm/sec CNT100    ;
   503:L P[503] 100mm/sec CNT100    ;
   504:L P[504] 100mm/sec CNT100    ;
   505:L P[505] 100mm/sec CNT100    ;
   506:L P[506] 100mm/sec CNT100    ;
   507:L P[507] 100mm/sec CNT100    ;
   508:L P[508] 100mm/sec CNT100    ;
   509:L P[509] 100mm/sec CNT100    ;
   510:L P[510] 100mm/sec CNT100    ;
   511:L P[511] 100mm/sec CNT100    ;
   512:L P[512] 100mm/sec CNT100    ;
   513:L P[513] 100mm/sec CNT100    ;
   514:L P[514] 100mm/sec CNT100    ;
   515:L P[515] 100mm/sec CNT100    ;
   516:L P[516] 100mm/sec CNT100    ;
   517:L P[517] 100mm/sec CNT100    ;
   518:L P[518] 100mm/sec CNT100    ;
   519:L P[519] 100mm/sec CNT100    ;
   520:L P[520] 100mm/sec CNT100    ;
   521:L P[521] 100mm/sec CNT100    ;
   522:L P[522] 100mm/sec CNT100    ;
   523:L P[523] 100mm/sec CNT100    ;
   524:L P[524] 100mm/sec CNT100    ;
   525:L P[525] 100mm/sec CNT100    ;
   526:L P[526] 100mm/sec CNT100    ;
   527:L P[527] 100mm/sec CNT100    ;
   528:L P[528] 100mm/sec CNT100    ;
   529:L P[529] 100mm/sec CNT100    ;
   530:L P[530] 100mm/sec CNT100    ;
   531:L P[531] 100mm/sec CNT100    ;
   532:L P[532] 100mm/sec CNT100    ;
   533:L P[533] 100mm/sec CNT100    ;
   534:L P[534] 100mm/sec CNT100    ;
   535:L P[535] 100mm/sec CNT100    ;
   536:L P[536] 100mm/sec CNT100    ;
   537:L P[537] 100mm/sec CNT100    ;
   538:L P[538] 100mm/sec CNT100    ;
   539:L P[539] 100mm/sec CNT100    ;
   540:L P[540] 100mm/sec CNT100    ;
   541:L P[541] 100mm/sec CNT100    ;
   542:L P[542] 100mm/sec CNT100    ;
   543:L P[543] 100mm/sec CNT100    ;
   544:L P[544] 100mm/sec CNT100    ;
   545:L P[545] 100mm/sec CNT100    ;
   546:L P[546] 100mm/sec CNT100    ;
   547:L P[547] 100mm/sec CNT100    ;
   548:L P[548] 100mm/sec CNT100    ;
   549:L P[549] 100mm/sec CNT100    ;
   550:L P[550] 100mm/sec CNT100    ;
   551:L P[551] 100mm/sec CNT100    ;
   552:L P[552] 100mm/sec CNT100    ;
   553:L P[553] 100mm/sec CNT100    ;
   554:L P[554] 100mm/sec CNT100    ;
   555:L P[555] 100mm/sec CNT100    ;
   556:L P[556] 100mm/sec CNT100    ;
   557:L P[557] 100mm/sec CNT100    ;
   558:L P[558] 100mm/sec CNT100    ;
   559:L P[559] 100mm/sec CNT100    ;
   560:L P[560] 100mm/sec CNT100    ;
   561:L P[561] 100mm/sec CNT100    ;
   562:L P[562] 100mm/sec CNT100    ;
   563:L P[563] 100mm/sec CNT100    ;
   564:L P[564] 100mm/sec CNT100    ;
   565:L P[565] 100mm/sec CNT100    ;
   566:L P[566] 100mm/sec CNT100    ;
   567:L P[567] 100mm/sec CNT100    ;
   568:L P[568] 100mm/sec CNT100    ;
   569:L P[569] 100mm/sec CNT100    ;
   570:L P[570] 100mm/sec CNT100    ;
   571:L P[571] 100mm/sec CNT100    ;
   572:L P[572] 100mm/sec CNT100    ;
   573:L P[573] 100mm/sec CNT100    ;
   574:L P[574] 100mm/sec CNT100    ;
   575:L P[575] 100mm/sec CNT100    ;
   576:L P[576] 100mm/sec CNT100    ;
   577:L P[577] 100mm/sec CNT100    ;
   578:L P[578] 100mm/sec CNT100    ;
   579:L P[579] 100mm/sec CNT100    ;
   580:L P[580] 100mm/sec CNT100    ;
   581:L P[581] 100mm/sec CNT100    ;
   582:L P[582] 100mm/sec CNT100    ;
   583:L P[583] 100mm/sec CNT100    ;
   584:L P[584] 100mm/sec CNT100    ;
   585:L P[585] 100mm/sec CNT100    ;
   586:L P[586] 100mm/sec CNT100    ;
   587:L P[587] 100mm/sec CNT100    ;
   588:L P[588] 100mm/sec CNT100    ;
   589:L P[589] 100mm/sec CNT100    ;
   590:L P[590] 100mm/sec CNT100    ;
   591:L P[591] 100mm/sec CNT100    ;
   592:L P[592] 100mm/sec CNT100    ;
   593:L P[593] 100mm/sec CNT100    ;
   594:L P[594] 100mm/sec CNT100    ;
   595:L P[595] 100mm/sec CNT100    ;
   596:L P[596] 100mm/sec CNT100    ;
   597:L P[597] 100mm/sec CNT100    ;
   598:L P[598] 100mm/sec CNT100    ;
   599:L P[599] 100mm/sec CNT100    ;
   600:L P[600] 100mm/sec CNT100    ;
   601:L P[601] 100mm/sec CNT100    ;
   602:L P[602] 100mm/sec CNT100    ;
   603:L P[603] 100mm/sec CNT100    ;
   604:L P[604] 100mm/sec CNT100    ;
   605:L P[605] 100mm/sec CNT100    ;
   606:L P[606] 100mm/sec CNT100    ;
   607:L P[607] 100mm/sec CNT100    ;
   608:L P[608] 100mm/sec CNT100    ;
   609:L P[609] 100mm/sec CNT100    ;
   610:L P[610] 100mm/sec CNT100    ;
   611:L P[611] 100mm/sec CNT100    ;
   612:L P[612] 100mm/sec CNT100    ;
   613:L P[613] 100mm/sec CNT100    ;
   614:L P[614] 100mm/sec CNT100    ;
   615:L P[615] 100mm/sec CNT100    ;
   616:L P[616] 100mm/sec CNT100    ;
   617:L P[617] 100mm/sec CNT100    ;
   618:L P[618] 100mm/sec CNT100    ;
   619:L P[619] 100mm/sec CNT100    ;
   620:L P[620] 100mm/sec CNT100    ;
   621:L P[621] 100mm/sec CNT100    ;
   622:L P[622] 100mm/sec CNT100    ;
   623:L P[623] 100mm/sec CNT100    ;
   624:L P[624] 100mm/sec CNT100    ;
   625:L P[625] 100mm/sec CNT100    ;
   626:L P[626] 100mm/sec CNT100    ;
   627:L P[627] 100mm/sec CNT100    ;
   628:L P[628] 100mm/sec CNT100    ;
   629:L P[629] 100mm/sec CNT100    ;
   630:L P[630] 100mm/sec CNT100    ;
   631:L P[631] 100mm/sec CNT100    ;
   632:L P[632] 100mm/sec CNT100    ;
   633:L P[633] 100mm/sec CNT100    ;
   634:L P[634] 100mm/sec CNT100    ;
   635:L P[635] 100mm/sec CNT100    ;
   636:L P[636] 100mm/sec CNT100    ;
   637:L P[637] 100mm/sec CNT100    ;
   638:L P[638] 100mm/sec CNT100    ;
   639:L P[639] 100mm/sec CNT100    ;
   640:L P[640] 100mm/sec CNT100    ;
   641:L P[641] 100mm/sec CNT100    ;
   642:L P[642] 100mm/sec CNT100    ;
   643:L P[643] 100mm/sec CNT100    ;
   644:L P[644] 100mm/sec CNT100    ;
   645:L P[645] 100mm/sec CNT100    ;
   646:L P[646] 100mm/sec CNT100    ;
   647:L P[647] 100mm/sec CNT100    ;
   648:L P[648] 100mm/sec CNT100    ;
   649:L P[649] 100mm/sec CNT100    ;
   650:L P[650] 100mm/sec CNT100    ;
   651:L P[651] 100mm/sec CNT100    ;
   652:L P[652] 100mm/sec CNT100    ;
/POS
P[1]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  0.000  mm,    Y =   0.000  mm,    Z =   -225.827  mm,
    W =  0.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[2]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  415.701  mm,    Y =   -23.336  mm,    Z =   -285.453  mm,
    W =  -179.933 deg,    P =   0.015 deg,    R =   -0.998 deg
};
P[3]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  426.035  mm,    Y =   -22.839  mm,    Z =   -286.493  mm,
    W =  -179.954 deg,    P =   -0.006 deg,    R =   -0.999 deg
};
P[4]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  407.412  mm,    Y =   -18.324  mm,    Z =   -286.012  mm,
    W =  -179.912 deg,    P =   0.043 deg,    R =   -0.995 deg
};
P[5]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  398.850  mm,    Y =   -11.447  mm,    Z =   -286.402  mm,
    W =  -179.912 deg,    P =   0.047 deg,    R =   -0.995 deg
};
P[6]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  403.205  mm,    Y =   -22.723  mm,    Z =   -286.321  mm,
    W =  -179.918 deg,    P =   0.055 deg,    R =   -0.995 deg
};
P[7]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  396.245  mm,    Y =   -14.974  mm,    Z =   -286.355  mm,
    W =  -179.912 deg,    P =   0.049 deg,    R =   -0.995 deg
};
P[8]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  410.171  mm,    Y =   -30.920  mm,    Z =   -286.524  mm,
    W =  -179.942 deg,    P =   0.022 deg,    R =   -0.998 deg
};
P[9]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  405.915  mm,    Y =   -31.962  mm,    Z =   -286.375  mm,
    W =  -179.930 deg,    P =   0.046 deg,    R =   -0.997 deg
};
P[10]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  399.576  mm,    Y =   -26.158  mm,    Z =   -286.539  mm,
    W =  -179.919 deg,    P =   0.057 deg,    R =   -0.995 deg
};
P[11]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  392.866  mm,    Y =   -18.788  mm,    Z =   -286.154  mm,
    W =  -179.916 deg,    P =   0.059 deg,    R =   -0.995 deg
};
P[12]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  387.398  mm,    Y =   -15.093  mm,    Z =   -287.461  mm,
    W =  -179.916 deg,    P =   0.066 deg,    R =   -0.994 deg
};
P[13]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  409.495  mm,    Y =   -99.354  mm,    Z =   -287.868  mm,
    W =  -179.979 deg,    P =   0.097 deg,    R =   -0.995 deg
};
P[14]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  451.580  mm,    Y =   -58.839  mm,    Z =   -288.839  mm,
    W =  -180.001 deg,    P =   -0.017 deg,    R =   -1.000 deg
};
P[15]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  422.480  mm,    Y =   -29.022  mm,    Z =   -288.452  mm,
    W =  -179.951 deg,    P =   0.007 deg,    R =   -0.999 deg
};
P[16]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  443.727  mm,    Y =   -65.671  mm,    Z =   -288.166  mm,
    W =  -179.995 deg,    P =   -0.002 deg,    R =   -1.000 deg
};
P[17]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  394.615  mm,    Y =   -30.992  mm,    Z =   -288.646  mm,
    W =  -179.921 deg,    P =   0.065 deg,    R =   -0.995 deg
};
P[18]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  414.368  mm,    Y =   -96.278  mm,    Z =   -287.955  mm,
    W =  -179.982 deg,    P =   0.081 deg,    R =   -0.997 deg
};
P[19]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  405.239  mm,    Y =   -95.006  mm,    Z =   -288.006  mm,
    W =  -179.957 deg,    P =   0.099 deg,    R =   -0.994 deg
};
P[20]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  404.422  mm,    Y =   -105.119  mm,    Z =   -288.561  mm,
    W =  -179.973 deg,    P =   0.122 deg,    R =   -0.992 deg
};
P[21]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  451.958  mm,    Y =   -43.582  mm,    Z =   -289.614  mm,
    W =  -179.989 deg,    P =   -0.028 deg,    R =   -1.000 deg
};
P[22]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  458.693  mm,    Y =   -51.027  mm,    Z =   -289.683  mm,
    W =  -180.014 deg,    P =   -0.028 deg,    R =   -0.999 deg
};
P[23]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  458.401  mm,    Y =   -65.467  mm,    Z =   -289.018  mm,
    W =  -180.037 deg,    P =   -0.010 deg,    R =   -0.999 deg
};
P[24]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  444.930  mm,    Y =   -51.931  mm,    Z =   -289.395  mm,
    W =  -179.978 deg,    P =   -0.015 deg,    R =   -1.000 deg
};
P[25]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  462.990  mm,    Y =   -70.984  mm,    Z =   -289.682  mm,
    W =  -180.062 deg,    P =   -0.009 deg,    R =   -0.998 deg
};
P[26]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  451.500  mm,    Y =   -72.451  mm,    Z =   -289.110  mm,
    W =  -180.034 deg,    P =   0.001 deg,    R =   -0.999 deg
};
P[27]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  437.376  mm,    Y =   -57.869  mm,    Z =   -289.236  mm,
    W =  -179.970 deg,    P =   -0.006 deg,    R =   -1.000 deg
};
P[28]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  384.951  mm,    Y =   -18.264  mm,    Z =   -289.573  mm,
    W =  -179.917 deg,    P =   0.067 deg,    R =   -0.994 deg
};
P[29]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  401.816  mm,    Y =   -37.050  mm,    Z =   -289.356  mm,
    W =  -179.929 deg,    P =   0.056 deg,    R =   -0.996 deg
};
P[30]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  387.853  mm,    Y =   -23.670  mm,    Z =   -289.197  mm,
    W =  -179.915 deg,    P =   0.071 deg,    R =   -0.994 deg
};
P[31]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  426.699  mm,    Y =   -96.979  mm,    Z =   -289.801  mm,
    W =  -180.025 deg,    P =   0.031 deg,    R =   -0.999 deg
};
P[32]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  419.439  mm,    Y =   -90.027  mm,    Z =   -289.256  mm,
    W =  -179.983 deg,    P =   0.030 deg,    R =   -0.999 deg
};
P[33]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  413.033  mm,    Y =   -83.261  mm,    Z =   -289.570  mm,
    W =  -179.962 deg,    P =   0.036 deg,    R =   -0.999 deg
};
P[34]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  405.857  mm,    Y =   -89.086  mm,    Z =   -289.162  mm,
    W =  -179.955 deg,    P =   0.091 deg,    R =   -0.995 deg
};
P[35]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  420.236  mm,    Y =   -103.955  mm,    Z =   -289.390  mm,
    W =  -180.018 deg,    P =   0.085 deg,    R =   -0.996 deg
};
P[36]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  455.534  mm,    Y =   -53.652  mm,    Z =   -290.106  mm,
    W =  -180.004 deg,    P =   -0.023 deg,    R =   -1.000 deg
};
P[37]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  447.475  mm,    Y =   -46.607  mm,    Z =   -290.188  mm,
    W =  -179.982 deg,    P =   -0.022 deg,    R =   -1.000 deg
};
P[38]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  316.563  mm,    Y =   75.978  mm,    Z =   -290.444  mm,
    W =  -179.950 deg,    P =   -0.050 deg,    R =   -0.997 deg
};
P[39]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  417.086  mm,    Y =   -36.321  mm,    Z =   -290.421  mm,
    W =  -179.946 deg,    P =   0.016 deg,    R =   -0.998 deg
};
P[40]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  388.437  mm,    Y =   -10.004  mm,    Z =   -290.820  mm,
    W =  -179.914 deg,    P =   0.059 deg,    R =   -0.994 deg
};
P[41]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  353.158  mm,    Y =   14.824  mm,    Z =   -290.305  mm,
    W =  -179.980 deg,    P =   0.062 deg,    R =   -0.998 deg
};
P[42]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  432.528  mm,    Y =   -67.697  mm,    Z =   -290.271  mm,
    W =  -179.969 deg,    P =   0.006 deg,    R =   -0.999 deg
};
P[43]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  357.845  mm,    Y =   4.368  mm,    Z =   -290.756  mm,
    W =  -179.967 deg,    P =   0.084 deg,    R =   -0.996 deg
};
P[44]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  352.179  mm,    Y =   10.358  mm,    Z =   -290.508  mm,
    W =  -179.980 deg,    P =   0.073 deg,    R =   -0.997 deg
};
P[45]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  432.980  mm,    Y =   -104.157  mm,    Z =   -290.861  mm,
    W =  -180.043 deg,    P =   0.050 deg,    R =   -0.998 deg
};
P[46]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  380.432  mm,    Y =   -73.574  mm,    Z =   -290.832  mm,
    W =  -179.924 deg,    P =   0.126 deg,    R =   -0.989 deg
};
P[47]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  411.356  mm,    Y =   -111.409  mm,    Z =   -290.070  mm,
    W =  -180.000 deg,    P =   0.110 deg,    R =   -0.994 deg
};
P[48]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  398.414  mm,    Y =   -98.410  mm,    Z =   -290.635  mm,
    W =  -179.948 deg,    P =   0.126 deg,    R =   -0.991 deg
};
P[49]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  465.281  mm,    Y =   -56.114  mm,    Z =   -291.610  mm,
    W =  -180.045 deg,    P =   -0.031 deg,    R =   -0.999 deg
};
P[50]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  463.282  mm,    Y =   -60.656  mm,    Z =   -290.960  mm,
    W =  -180.044 deg,    P =   -0.020 deg,    R =   -0.999 deg
};
P[51]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  429.131  mm,    Y =   -28.523  mm,    Z =   -290.934  mm,
    W =  -179.960 deg,    P =   -0.001 deg,    R =   -0.999 deg
};
P[52]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  439.118  mm,    Y =   -47.765  mm,    Z =   -291.625  mm,
    W =  -179.966 deg,    P =   -0.012 deg,    R =   -0.999 deg
};
P[53]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  322.807  mm,    Y =   67.995  mm,    Z =   -291.831  mm,
    W =  -179.980 deg,    P =   -0.033 deg,    R =   -0.999 deg
};
P[54]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  311.856  mm,    Y =   78.946  mm,    Z =   -291.831  mm,
    W =  -179.939 deg,    P =   -0.045 deg,    R =   -0.997 deg
};
P[55]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  459.166  mm,    Y =   -78.482  mm,    Z =   -291.022  mm,
    W =  -180.058 deg,    P =   -0.000 deg,    R =   -0.998 deg
};
P[56]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  438.738  mm,    Y =   -73.067  mm,    Z =   -291.306  mm,
    W =  -179.992 deg,    P =   0.006 deg,    R =   -1.000 deg
};
P[57]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  434.463  mm,    Y =   -71.744  mm,    Z =   -291.066  mm,
    W =  -179.978 deg,    P =   0.007 deg,    R =   -1.000 deg
};
P[58]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  361.848  mm,    Y =   -1.164  mm,    Z =   -291.829  mm,
    W =  -179.957 deg,    P =   0.089 deg,    R =   -0.995 deg
};
P[59]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  431.447  mm,    Y =   -92.908  mm,    Z =   -291.474  mm,
    W =  -180.014 deg,    P =   0.019 deg,    R =   -1.000 deg
};
P[60]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  424.524  mm,    Y =   -86.311  mm,    Z =   -291.219  mm,
    W =  -179.985 deg,    P =   0.022 deg,    R =   -1.000 deg
};
P[61]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  416.257  mm,    Y =   -77.901  mm,    Z =   -291.618  mm,
    W =  -179.960 deg,    P =   0.030 deg,    R =   -0.999 deg
};
P[62]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  438.443  mm,    Y =   -101.021  mm,    Z =   -291.642  mm,
    W =  -180.046 deg,    P =   0.020 deg,    R =   -0.999 deg
};
P[63]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  427.765  mm,    Y =   -111.117  mm,    Z =   -291.852  mm,
    W =  -180.034 deg,    P =   0.063 deg,    R =   -0.997 deg
};
P[64]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  398.403  mm,    Y =   -92.740  mm,    Z =   -291.678  mm,
    W =  -179.948 deg,    P =   0.118 deg,    R =   -0.992 deg
};
P[65]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  372.748  mm,    Y =   -66.598  mm,    Z =   -291.169  mm,
    W =  -179.912 deg,    P =   0.134 deg,    R =   -0.987 deg
};
P[66]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  375.960  mm,    Y =   -76.793  mm,    Z =   -291.038  mm,
    W =  -179.923 deg,    P =   0.146 deg,    R =   -0.986 deg
};
P[67]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  369.382  mm,    Y =   -70.606  mm,    Z =   -291.058  mm,
    W =  -179.912 deg,    P =   0.151 deg,    R =   -0.985 deg
};
P[68]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  446.180  mm,    Y =   -36.772  mm,    Z =   -291.957  mm,
    W =  -179.973 deg,    P =   -0.028 deg,    R =   -0.999 deg
};
P[69]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  439.640  mm,    Y =   -41.111  mm,    Z =   -292.326  mm,
    W =  -179.964 deg,    P =   -0.014 deg,    R =   -0.999 deg
};
P[70]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  433.063  mm,    Y =   -34.885  mm,    Z =   -292.646  mm,
    W =  -179.962 deg,    P =   -0.009 deg,    R =   -0.999 deg
};
P[71]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  408.843  mm,    Y =   -10.862  mm,    Z =   -292.531  mm,
    W =  -179.911 deg,    P =   0.035 deg,    R =   -0.995 deg
};
P[72]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  407.290  mm,    Y =   -9.309  mm,    Z =   -292.531  mm,
    W =  -179.909 deg,    P =   0.030 deg,    R =   -0.995 deg
};
P[73]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  426.331  mm,    Y =   -36.434  mm,    Z =   -292.173  mm,
    W =  -179.958 deg,    P =   0.004 deg,    R =   -0.999 deg
};
P[74]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  318.764  mm,    Y =   63.020  mm,    Z =   -292.377  mm,
    W =  -179.983 deg,    P =   -0.016 deg,    R =   -1.000 deg
};
P[75]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  312.018  mm,    Y =   70.255  mm,    Z =   -292.171  mm,
    W =  -179.954 deg,    P =   -0.023 deg,    R =   -0.999 deg
};
P[76]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  351.352  mm,    Y =   25.860  mm,    Z =   -292.411  mm,
    W =  -179.990 deg,    P =   0.045 deg,    R =   -0.999 deg
};
P[77]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  344.175  mm,    Y =   32.500  mm,    Z =   -292.855  mm,
    W =  -180.005 deg,    P =   0.033 deg,    R =   -0.999 deg
};
P[78]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  363.152  mm,    Y =   6.201  mm,    Z =   -292.101  mm,
    W =  -179.962 deg,    P =   0.081 deg,    R =   -0.996 deg
};
P[79]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  428.920  mm,    Y =   -63.721  mm,    Z =   -292.469  mm,
    W =  -179.964 deg,    P =   0.008 deg,    R =   -0.999 deg
};
P[80]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  395.939  mm,    Y =   -37.934  mm,    Z =   -292.838  mm,
    W =  -179.927 deg,    P =   0.069 deg,    R =   -0.995 deg
};
P[81]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  390.829  mm,    Y =   -34.049  mm,    Z =   -292.637  mm,
    W =  -179.921 deg,    P =   0.066 deg,    R =   -0.995 deg
};
P[82]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  384.828  mm,    Y =   -27.848  mm,    Z =   -292.708  mm,
    W =  -179.917 deg,    P =   0.072 deg,    R =   -0.994 deg
};
P[83]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  430.033  mm,    Y =   -79.790  mm,    Z =   -292.827  mm,
    W =  -179.982 deg,    P =   0.013 deg,    R =   -1.000 deg
};
P[84]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  406.828  mm,    Y =   -78.932  mm,    Z =   -292.153  mm,
    W =  -179.948 deg,    P =   0.050 deg,    R =   -0.997 deg
};
P[85]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  437.464  mm,    Y =   -110.112  mm,    Z =   -292.585  mm,
    W =  -180.049 deg,    P =   0.048 deg,    R =   -0.998 deg
};
P[86]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  416.176  mm,    Y =   -112.018  mm,    Z =   -292.244  mm,
    W =  -180.013 deg,    P =   0.094 deg,    R =   -0.996 deg
};
P[87]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  386.028  mm,    Y =   -82.468  mm,    Z =   -292.655  mm,
    W =  -179.935 deg,    P =   0.138 deg,    R =   -0.988 deg
};
P[88]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  380.897  mm,    Y =   -83.069  mm,    Z =   -292.245  mm,
    W =  -179.931 deg,    P =   0.147 deg,    R =   -0.987 deg
};
P[89]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  405.728  mm,    Y =   -113.199  mm,    Z =   -292.256  mm,
    W =  -179.994 deg,    P =   0.132 deg,    R =   -0.991 deg
};
P[90]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  399.709  mm,    Y =   -109.136  mm,    Z =   -292.011  mm,
    W =  -179.971 deg,    P =   0.138 deg,    R =   -0.990 deg
};
P[91]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  362.670  mm,    Y =   -76.422  mm,    Z =   -292.837  mm,
    W =  -179.910 deg,    P =   0.180 deg,    R =   -0.980 deg
};
P[92]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  432.367  mm,    Y =   -22.968  mm,    Z =   -292.995  mm,
    W =  -179.958 deg,    P =   -0.018 deg,    R =   -0.999 deg
};
P[93]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  321.374  mm,    Y =   79.362  mm,    Z =   -293.872  mm,
    W =  -179.953 deg,    P =   -0.069 deg,    R =   -0.997 deg
};
P[94]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  325.910  mm,    Y =   70.290  mm,    Z =   -293.809  mm,
    W =  -179.981 deg,    P =   -0.053 deg,    R =   -0.998 deg
};
P[95]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  396.379  mm,    Y =   -5.619  mm,    Z =   -292.980  mm,
    W =  -179.914 deg,    P =   0.041 deg,    R =   -0.995 deg
};
P[96]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  433.158  mm,    Y =   -44.219  mm,    Z =   -293.666  mm,
    W =  -179.965 deg,    P =   -0.002 deg,    R =   -0.999 deg
};
P[97]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  432.135  mm,    Y =   -50.253  mm,    Z =   -293.087  mm,
    W =  -179.957 deg,    P =   -0.004 deg,    R =   -0.999 deg
};
P[98]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  465.282  mm,    Y =   -84.404  mm,    Z =   -293.343  mm,
    W =  -180.072 deg,    P =   -0.013 deg,    R =   -0.997 deg
};
P[99]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  325.452  mm,    Y =   55.766  mm,    Z =   -293.445  mm,
    W =  -179.998 deg,    P =   -0.010 deg,    R =   -1.000 deg
};
P[100]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  357.829  mm,    Y =   18.635  mm,    Z =   -293.321  mm,
    W =  -179.980 deg,    P =   0.065 deg,    R =   -0.998 deg
};
P[101]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  368.131  mm,    Y =   -1.414  mm,    Z =   -293.614  mm,
    W =  -179.950 deg,    P =   0.085 deg,    R =   -0.995 deg
};
P[102]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  346.081  mm,    Y =   19.785  mm,    Z =   -293.279  mm,
    W =  -179.994 deg,    P =   0.056 deg,    R =   -0.998 deg
};
P[103]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  310.563  mm,    Y =   55.367  mm,    Z =   -293.184  mm,
    W =  -179.977 deg,    P =   0.017 deg,    R =   -1.000 deg
};
P[104]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  303.505  mm,    Y =   62.768  mm,    Z =   -292.993  mm,
    W =  -179.955 deg,    P =   0.017 deg,    R =   -0.999 deg
};
P[105]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  444.750  mm,    Y =   -78.982  mm,    Z =   -293.179  mm,
    W =  -180.016 deg,    P =   0.009 deg,    R =   -1.000 deg
};
P[106]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  381.284  mm,    Y =   -15.566  mm,    Z =   -293.413  mm,
    W =  -179.925 deg,    P =   0.073 deg,    R =   -0.995 deg
};
P[107]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  402.463  mm,    Y =   -40.537  mm,    Z =   -293.062  mm,
    W =  -179.934 deg,    P =   0.048 deg,    R =   -0.997 deg
};
P[108]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  359.736  mm,    Y =   -3.955  mm,    Z =   -293.484  mm,
    W =  -179.956 deg,    P =   0.093 deg,    R =   -0.995 deg
};
P[109]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  355.048  mm,    Y =   0.126  mm,    Z =   -293.699  mm,
    W =  -179.968 deg,    P =   0.087 deg,    R =   -0.996 deg
};
P[110]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  348.580  mm,    Y =   7.031  mm,    Z =   -293.441  mm,
    W =  -179.982 deg,    P =   0.074 deg,    R =   -0.997 deg
};
P[111]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  423.336  mm,    Y =   -73.450  mm,    Z =   -292.978  mm,
    W =  -179.960 deg,    P =   0.017 deg,    R =   -0.999 deg
};
P[112]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  443.043  mm,    Y =   -95.151  mm,    Z =   -293.516  mm,
    W =  -180.046 deg,    P =   0.013 deg,    R =   -0.999 deg
};
P[113]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  436.366  mm,    Y =   -87.656  mm,    Z =   -293.622  mm,
    W =  -180.015 deg,    P =   0.019 deg,    R =   -1.000 deg
};
P[114]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  444.091  mm,    Y =   -108.822  mm,    Z =   -293.790  mm,
    W =  -180.056 deg,    P =   0.023 deg,    R =   -0.998 deg
};
P[115]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  399.794  mm,    Y =   -82.241  mm,    Z =   -293.347  mm,
    W =  -179.943 deg,    P =   0.095 deg,    R =   -0.994 deg
};
P[116]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  392.741  mm,    Y =   -75.805  mm,    Z =   -293.685  mm,
    W =  -179.934 deg,    P =   0.100 deg,    R =   -0.993 deg
};
P[117]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  384.531  mm,    Y =   -69.084  mm,    Z =   -293.124  mm,
    W =  -179.925 deg,    P =   0.104 deg,    R =   -0.992 deg
};
P[118]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  364.134  mm,    Y =   -60.338  mm,    Z =   -293.384  mm,
    W =  -179.904 deg,    P =   0.140 deg,    R =   -0.985 deg
};
P[119]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  391.645  mm,    Y =   -96.031  mm,    Z =   -293.644  mm,
    W =  -179.946 deg,    P =   0.134 deg,    R =   -0.990 deg
};
P[120]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  361.080  mm,    Y =   -65.025  mm,    Z =   -293.053  mm,
    W =  -179.904 deg,    P =   0.151 deg,    R =   -0.984 deg
};
P[121]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  354.129  mm,    Y =   -59.090  mm,    Z =   -293.860  mm,
    W =  -179.908 deg,    P =   0.141 deg,    R =   -0.986 deg
};
P[122]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  393.033  mm,    Y =   -102.973  mm,    Z =   -293.673  mm,
    W =  -179.953 deg,    P =   0.141 deg,    R =   -0.989 deg
};
P[123]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  369.567  mm,    Y =   -83.125  mm,    Z =   -293.067  mm,
    W =  -179.916 deg,    P =   0.177 deg,    R =   -0.981 deg
};
P[124]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  355.837  mm,    Y =   -69.870  mm,    Z =   -293.624  mm,
    W =  -179.907 deg,    P =   0.181 deg,    R =   -0.979 deg
};
P[125]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  439.404  mm,    Y =   -28.626  mm,    Z =   -294.704  mm,
    W =  -179.968 deg,    P =   -0.022 deg,    R =   -0.999 deg
};
P[126]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  469.204  mm,    Y =   -69.753  mm,    Z =   -294.315  mm,
    W =  -180.073 deg,    P =   -0.022 deg,    R =   -0.997 deg
};
P[127]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  332.082  mm,    Y =   62.736  mm,    Z =   -294.366  mm,
    W =  -180.001 deg,    P =   -0.034 deg,    R =   -0.999 deg
};
P[128]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  430.112  mm,    Y =   -41.585  mm,    Z =   -294.306  mm,
    W =  -179.958 deg,    P =   -0.002 deg,    R =   -0.999 deg
};
P[129]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  336.261  mm,    Y =   52.416  mm,    Z =   -294.423  mm,
    W =  -180.007 deg,    P =   -0.011 deg,    R =   -1.000 deg
};
P[130]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  330.719  mm,    Y =   58.198  mm,    Z =   -294.049  mm,
    W =  -179.998 deg,    P =   -0.018 deg,    R =   -1.000 deg
};
P[131]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  424.544  mm,    Y =   -42.523  mm,    Z =   -294.131  mm,
    W =  -179.951 deg,    P =   0.009 deg,    R =   -0.999 deg
};
P[132]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  332.907  mm,    Y =   48.665  mm,    Z =   -294.695  mm,
    W =  -180.004 deg,    P =   -0.002 deg,    R =   -1.000 deg
};
P[133]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  338.203  mm,    Y =   41.836  mm,    Z =   -294.871  mm,
    W =  -180.008 deg,    P =   0.012 deg,    R =   -1.000 deg
};
P[134]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  305.281  mm,    Y =   75.820  mm,    Z =   -294.099  mm,
    W =  -179.939 deg,    P =   -0.010 deg,    R =   -0.998 deg
};
P[135]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  410.021  mm,    Y =   -43.487  mm,    Z =   -294.108  mm,
    W =  -179.942 deg,    P =   0.027 deg,    R =   -0.998 deg
};
P[136]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  318.097  mm,    Y =   48.847  mm,    Z =   -294.187  mm,
    W =  -179.998 deg,    P =   0.016 deg,    R =   -1.000 deg
};
P[137]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  440.537  mm,    Y =   -83.517  mm,    Z =   -294.624  mm,
    W =  -180.016 deg,    P =   0.009 deg,    R =   -1.000 deg
};
P[138]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  423.947  mm,    Y =   -67.232  mm,    Z =   -294.833  mm,
    W =  -179.960 deg,    P =   0.014 deg,    R =   -0.999 deg
};
P[139]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  302.006  mm,    Y =   49.275  mm,    Z =   -294.866  mm,
    W =  -179.971 deg,    P =   0.027 deg,    R =   -0.999 deg
};
P[140]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  296.780  mm,    Y =   54.769  mm,    Z =   -294.058  mm,
    W =  -179.960 deg,    P =   0.023 deg,    R =   -0.999 deg
};
P[141]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  449.216  mm,    Y =   -101.778  mm,    Z =   -294.830  mm,
    W =  -180.052 deg,    P =   -0.002 deg,    R =   -0.999 deg
};
P[142]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  408.418  mm,    Y =   -72.361  mm,    Z =   -294.295  mm,
    W =  -179.952 deg,    P =   0.033 deg,    R =   -0.998 deg
};
P[143]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  400.859  mm,    Y =   -74.875  mm,    Z =   -294.684  mm,
    W =  -179.943 deg,    P =   0.062 deg,    R =   -0.996 deg
};
P[144]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  435.152  mm,    Y =   -116.761  mm,    Z =   -294.113  mm,
    W =  -180.052 deg,    P =   0.047 deg,    R =   -0.998 deg
};
P[145]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  376.542  mm,    Y =   -63.128  mm,    Z =   -294.219  mm,
    W =  -179.918 deg,    P =   0.116 deg,    R =   -0.990 deg
};
P[146]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  420.752  mm,    Y =   -116.169  mm,    Z =   -294.689  mm,
    W =  -180.023 deg,    P =   0.085 deg,    R =   -0.996 deg
};
P[147]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  391.736  mm,    Y =   -89.500  mm,    Z =   -294.122  mm,
    W =  -179.945 deg,    P =   0.130 deg,    R =   -0.990 deg
};
P[148]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  458.320  mm,    Y =   -36.942  mm,    Z =   -295.910  mm,
    W =  -179.992 deg,    P =   -0.046 deg,    R =   -0.999 deg
};
P[149]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  312.656  mm,    Y =   84.753  mm,    Z =   -295.009  mm,
    W =  -179.928 deg,    P =   -0.059 deg,    R =   -0.996 deg
};
P[150]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  383.298  mm,    Y =   -4.714  mm,    Z =   -295.293  mm,
    W =  -179.930 deg,    P =   0.063 deg,    R =   -0.996 deg
};
P[151]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  452.811  mm,    Y =   -85.196  mm,    Z =   -295.274  mm,
    W =  -180.054 deg,    P =   0.006 deg,    R =   -0.999 deg
};
P[152]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  424.807  mm,    Y =   -56.709  mm,    Z =   -295.469  mm,
    W =  -179.955 deg,    P =   0.009 deg,    R =   -0.999 deg
};
P[153]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  375.665  mm,    Y =   -7.673  mm,    Z =   -295.369  mm,
    W =  -179.931 deg,    P =   0.075 deg,    R =   -0.995 deg
};
P[154]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  339.943  mm,    Y =   28.215  mm,    Z =   -295.537  mm,
    W =  -180.007 deg,    P =   0.035 deg,    R =   -0.999 deg
};
P[155]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  297.203  mm,    Y =   70.366  mm,    Z =   -295.054  mm,
    W =  -179.937 deg,    P =   0.014 deg,    R =   -0.998 deg
};
P[156]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  447.411  mm,    Y =   -90.442  mm,    Z =   -295.406  mm,
    W =  -180.051 deg,    P =   0.010 deg,    R =   -0.999 deg
};
P[157]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  290.223  mm,    Y =   65.052  mm,    Z =   -295.750  mm,
    W =  -179.939 deg,    P =   0.019 deg,    R =   -0.998 deg
};
P[158]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  306.261  mm,    Y =   46.838  mm,    Z =   -295.876  mm,
    W =  -179.980 deg,    P =   0.025 deg,    R =   -0.999 deg
};
P[159]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  289.169  mm,    Y =   59.905  mm,    Z =   -295.492  mm,
    W =  -179.942 deg,    P =   0.020 deg,    R =   -0.998 deg
};
P[160]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  415.844  mm,    Y =   -67.838  mm,    Z =   -295.398  mm,
    W =  -179.950 deg,    P =   0.025 deg,    R =   -0.998 deg
};
P[161]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  288.750  mm,    Y =   47.580  mm,    Z =   -295.435  mm,
    W =  -179.963 deg,    P =   0.029 deg,    R =   -0.999 deg
};
P[162]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  441.962  mm,    Y =   -115.589  mm,    Z =   -295.104  mm,
    W =  -180.064 deg,    P =   0.039 deg,    R =   -0.997 deg
};
P[163]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  278.891  mm,    Y =   37.414  mm,    Z =   -295.846  mm,
    W =  -179.958 deg,    P =   0.037 deg,    R =   -0.998 deg
};
P[164]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  356.721  mm,    Y =   -53.917  mm,    Z =   -295.209  mm,
    W =  -179.911 deg,    P =   0.137 deg,    R =   -0.987 deg
};
P[165]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  386.275  mm,    Y =   -95.966  mm,    Z =   -295.595  mm,
    W =  -179.942 deg,    P =   0.144 deg,    R =   -0.988 deg
};
P[166]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  376.995  mm,    Y =   -89.439  mm,    Z =   -295.356  mm,
    W =  -179.925 deg,    P =   0.167 deg,    R =   -0.983 deg
};
P[167]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350.751  mm,    Y =   -63.206  mm,    Z =   -295.576  mm,
    W =  -179.906 deg,    P =   0.152 deg,    R =   -0.984 deg
};
P[168]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  464.780  mm,    Y =   -43.892  mm,    Z =   -296.126  mm,
    W =  -180.029 deg,    P =   -0.053 deg,    R =   -0.998 deg
};
P[169]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  339.027  mm,    Y =   56.996  mm,    Z =   -296.340  mm,
    W =  -180.002 deg,    P =   -0.023 deg,    R =   -1.000 deg
};
P[170]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  305.992  mm,    Y =   81.749  mm,    Z =   -295.975  mm,
    W =  -179.932 deg,    P =   -0.032 deg,    R =   -0.997 deg
};
P[171]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  470.612  mm,    Y =   -84.944  mm,    Z =   -296.595  mm,
    W =  -180.079 deg,    P =   -0.023 deg,    R =   -0.997 deg
};
P[172]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  363.663  mm,    Y =   15.310  mm,    Z =   -296.279  mm,
    W =  -179.969 deg,    P =   0.068 deg,    R =   -0.997 deg
};
P[173]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  418.272  mm,    Y =   -49.138  mm,    Z =   -296.489  mm,
    W =  -179.945 deg,    P =   0.017 deg,    R =   -0.998 deg
};
P[174]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  326.095  mm,    Y =   43.096  mm,    Z =   -296.700  mm,
    W =  -180.004 deg,    P =   0.014 deg,    R =   -1.000 deg
};
P[175]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  418.045  mm,    Y =   -62.359  mm,    Z =   -296.646  mm,
    W =  -179.954 deg,    P =   0.023 deg,    R =   -0.999 deg
};
P[176]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  454.859  mm,    Y =   -107.577  mm,    Z =   -296.870  mm,
    W =  -180.069 deg,    P =   0.001 deg,    R =   -0.998 deg
};
P[177]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  410.317  mm,    Y =   -63.037  mm,    Z =   -296.870  mm,
    W =  -179.944 deg,    P =   0.026 deg,    R =   -0.998 deg
};
P[178]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  282.258  mm,    Y =   65.016  mm,    Z =   -296.870  mm,
    W =  -179.933 deg,    P =   0.022 deg,    R =   -0.997 deg
};
P[179]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  450.244  mm,    Y =   -112.324  mm,    Z =   -296.363  mm,
    W =  -180.065 deg,    P =   0.032 deg,    R =   -0.997 deg
};
P[180]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  282.006  mm,    Y =   55.104  mm,    Z =   -296.523  mm,
    W =  -179.938 deg,    P =   0.026 deg,    R =   -0.998 deg
};
P[181]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  396.145  mm,    Y =   -69.989  mm,    Z =   -295.940  mm,
    W =  -179.933 deg,    P =   0.068 deg,    R =   -0.995 deg
};
P[182]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  282.957  mm,    Y =   41.667  mm,    Z =   -296.017  mm,
    W =  -179.961 deg,    P =   0.034 deg,    R =   -0.999 deg
};
P[183]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  284.739  mm,    Y =   30.524  mm,    Z =   -296.108  mm,
    W =  -179.979 deg,    P =   0.045 deg,    R =   -0.999 deg
};
P[184]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  370.616  mm,    Y =   -57.078  mm,    Z =   -296.532  mm,
    W =  -179.909 deg,    P =   0.124 deg,    R =   -0.988 deg
};
P[185]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  272.737  mm,    Y =   31.620  mm,    Z =   -296.665  mm,
    W =  -179.961 deg,    P =   0.081 deg,    R =   -0.996 deg
};
P[186]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  471.772  mm,    Y =   -53.439  mm,    Z =   -297.527  mm,
    W =  -180.056 deg,    P =   -0.049 deg,    R =   -0.997 deg
};
P[187]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  343.367  mm,    Y =   45.181  mm,    Z =   -297.409  mm,
    W =  -180.007 deg,    P =   0.006 deg,    R =   -1.000 deg
};
P[188]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  333.760  mm,    Y =   36.745  mm,    Z =   -297.844  mm,
    W =  -180.007 deg,    P =   0.020 deg,    R =   -1.000 deg
};
P[189]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  460.260  mm,    Y =   -90.274  mm,    Z =   -296.997  mm,
    W =  -180.062 deg,    P =   -0.004 deg,    R =   -0.998 deg
};
P[190]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  290.988  mm,    Y =   77.598  mm,    Z =   -296.960  mm,
    W =  -179.927 deg,    P =   0.012 deg,    R =   -0.997 deg
};
P[191]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  454.680  mm,    Y =   -98.060  mm,    Z =   -297.638  mm,
    W =  -180.053 deg,    P =   -0.006 deg,    R =   -0.999 deg
};
P[192]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  283.159  mm,    Y =   70.876  mm,    Z =   -297.189  mm,
    W =  -179.929 deg,    P =   0.019 deg,    R =   -0.997 deg
};
P[193]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  360.590  mm,    Y =   -8.625  mm,    Z =   -297.798  mm,
    W =  -179.947 deg,    P =   0.093 deg,    R =   -0.994 deg
};
P[194]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  311.292  mm,    Y =   41.780  mm,    Z =   -297.640  mm,
    W =  -179.990 deg,    P =   0.028 deg,    R =   -1.000 deg
};
P[195]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  296.454  mm,    Y =   41.544  mm,    Z =   -297.866  mm,
    W =  -179.975 deg,    P =   0.032 deg,    R =   -0.999 deg
};
P[196]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  402.801  mm,    Y =   -65.629  mm,    Z =   -297.247  mm,
    W =  -179.940 deg,    P =   0.041 deg,    R =   -0.997 deg
};
P[197]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  273.409  mm,    Y =   42.305  mm,    Z =   -297.222  mm,
    W =  -179.947 deg,    P =   0.039 deg,    R =   -0.998 deg
};
P[198]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  289.264  mm,    Y =   25.407  mm,    Z =   -297.803  mm,
    W =  -179.995 deg,    P =   0.051 deg,    R =   -0.999 deg
};
P[199]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  428.916  mm,    Y =   -118.626  mm,    Z =   -297.471  mm,
    W =  -180.039 deg,    P =   0.069 deg,    R =   -0.997 deg
};
P[200]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  280.123  mm,    Y =   24.892  mm,    Z =   -297.164  mm,
    W =  -179.988 deg,    P =   0.079 deg,    R =   -0.997 deg
};
P[201]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  347.641  mm,    Y =   -58.727  mm,    Z =   -297.635  mm,
    W =  -179.910 deg,    P =   0.139 deg,    R =   -0.986 deg
};
P[202]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  358.533  mm,    Y =   -80.466  mm,    Z =   -297.749  mm,
    W =  -179.908 deg,    P =   0.204 deg,    R =   -0.975 deg
};
P[203]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  351.534  mm,    Y =   -74.136  mm,    Z =   -297.755  mm,
    W =  -179.905 deg,    P =   0.199 deg,    R =   -0.976 deg
};
P[204]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  450.244  mm,    Y =   -30.564  mm,    Z =   -298.530  mm,
    W =  -179.973 deg,    P =   -0.044 deg,    R =   -0.999 deg
};
P[205]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  473.221  mm,    Y =   -76.371  mm,    Z =   -298.054  mm,
    W =  -180.084 deg,    P =   -0.028 deg,    R =   -0.996 deg
};
P[206]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  391.013  mm,    Y =   -2.841  mm,    Z =   -298.257  mm,
    W =  -179.929 deg,    P =   0.054 deg,    R =   -0.996 deg
};
P[207]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  357.308  mm,    Y =   31.079  mm,    Z =   -298.780  mm,
    W =  -179.989 deg,    P =   0.043 deg,    R =   -0.999 deg
};
P[208]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350.076  mm,    Y =   37.715  mm,    Z =   -298.729  mm,
    W =  -180.000 deg,    P =   0.027 deg,    R =   -1.000 deg
};
P[209]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  292.672  mm,    Y =   83.916  mm,    Z =   -298.873  mm,
    W =  -179.913 deg,    P =   0.005 deg,    R =   -0.996 deg
};
P[210]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  283.699  mm,    Y =   83.877  mm,    Z =   -298.769  mm,
    W =  -179.905 deg,    P =   0.008 deg,    R =   -0.995 deg
};
P[211]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  410.463  mm,    Y =   -56.167  mm,    Z =   -298.310  mm,
    W =  -179.942 deg,    P =   0.027 deg,    R =   -0.998 deg
};
P[212]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  339.949  mm,    Y =   13.692  mm,    Z =   -298.384  mm,
    W =  -179.995 deg,    P =   0.053 deg,    R =   -0.999 deg
};
P[213]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  345.319  mm,    Y =   5.265  mm,    Z =   -297.995  mm,
    W =  -179.984 deg,    P =   0.074 deg,    R =   -0.997 deg
};
P[214]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  352.213  mm,    Y =   -2.636  mm,    Z =   -297.988  mm,
    W =  -179.968 deg,    P =   0.085 deg,    R =   -0.996 deg
};
P[215]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  276.060  mm,    Y =   62.868  mm,    Z =   -297.944  mm,
    W =  -179.930 deg,    P =   0.026 deg,    R =   -0.997 deg
};
P[216]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  390.265  mm,    Y =   -63.102  mm,    Z =   -298.532  mm,
    W =  -179.926 deg,    P =   0.082 deg,    R =   -0.994 deg
};
P[217]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  290.610  mm,    Y =   34.255  mm,    Z =   -297.917  mm,
    W =  -179.981 deg,    P =   0.036 deg,    R =   -0.999 deg
};
P[218]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  274.778  mm,    Y =   48.244  mm,    Z =   -298.005  mm,
    W =  -179.939 deg,    P =   0.035 deg,    R =   -0.998 deg
};
P[219]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  266.293  mm,    Y =   39.147  mm,    Z =   -298.555  mm,
    W =  -179.938 deg,    P =   0.061 deg,    R =   -0.996 deg
};
P[220]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  384.123  mm,    Y =   -96.518  mm,    Z =   -298.516  mm,
    W =  -179.938 deg,    P =   0.146 deg,    R =   -0.987 deg
};
P[221]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  371.961  mm,    Y =   -91.329  mm,    Z =   -298.824  mm,
    W =  -179.921 deg,    P =   0.174 deg,    R =   -0.982 deg
};
P[222]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  366.196  mm,    Y =   -86.809  mm,    Z =   -298.127  mm,
    W =  -179.912 deg,    P =   0.186 deg,    R =   -0.979 deg
};
P[223]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  346.900  mm,    Y =   -67.699  mm,    Z =   -298.587  mm,
    W =  -179.911 deg,    P =   0.187 deg,    R =   -0.978 deg
};
P[224]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  443.929  mm,    Y =   -24.699  mm,    Z =   -299.266  mm,
    W =  -179.971 deg,    P =   -0.041 deg,    R =   -0.999 deg
};
P[225]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  325.260  mm,    Y =   84.142  mm,    Z =   -299.237  mm,
    W =  -179.949 deg,    P =   -0.086 deg,    R =   -0.995 deg
};
P[226]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  345.104  mm,    Y =   51.652  mm,    Z =   -299.786  mm,
    W =  -180.005 deg,    P =   -0.008 deg,    R =   -1.000 deg
};
P[227]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  362.827  mm,    Y =   23.326  mm,    Z =   -299.809  mm,
    W =  -179.977 deg,    P =   0.061 deg,    R =   -0.998 deg
};
P[228]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  299.586  mm,    Y =   86.494  mm,    Z =   -299.017  mm,
    W =  -179.911 deg,    P =   -0.024 deg,    R =   -0.996 deg
};
P[229]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  292.138  mm,    Y =   93.029  mm,    Z =   -299.852  mm,
    W =  -179.877 deg,    P =   -0.032 deg,    R =   -0.992 deg
};
P[230]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  286.613  mm,    Y =   89.090  mm,    Z =   -299.772  mm,
    W =  -179.893 deg,    P =   -0.011 deg,    R =   -0.994 deg
};
P[231]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  390.884  mm,    Y =   -34.530  mm,    Z =   -299.512  mm,
    W =  -179.923 deg,    P =   0.065 deg,    R =   -0.995 deg
};
P[232]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  319.141  mm,    Y =   35.957  mm,    Z =   -299.869  mm,
    W =  -180.002 deg,    P =   0.030 deg,    R =   -1.000 deg
};
P[233]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  276.587  mm,    Y =   78.162  mm,    Z =   -298.949  mm,
    W =  -179.907 deg,    P =   0.014 deg,    R =   -0.996 deg
};
P[234]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  403.775  mm,    Y =   -59.042  mm,    Z =   -299.715  mm,
    W =  -179.940 deg,    P =   0.030 deg,    R =   -0.998 deg
};
P[235]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  271.470  mm,    Y =   73.573  mm,    Z =   -298.983  mm,
    W =  -179.911 deg,    P =   0.015 deg,    R =   -0.996 deg
};
P[236]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  302.588  mm,    Y =   41.013  mm,    Z =   -299.384  mm,
    W =  -179.984 deg,    P =   0.032 deg,    R =   -0.999 deg
};
P[237]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  268.811  mm,    Y =   68.908  mm,    Z =   -299.085  mm,
    W =  -179.914 deg,    P =   0.023 deg,    R =   -0.996 deg
};
P[238]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  445.370  mm,    Y =   -117.440  mm,    Z =   -299.805  mm,
    W =  -180.071 deg,    P =   0.042 deg,    R =   -0.997 deg
};
P[239]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  268.247  mm,    Y =   45.422  mm,    Z =   -299.312  mm,
    W =  -179.939 deg,    P =   0.041 deg,    R =   -0.997 deg
};
P[240]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  285.760  mm,    Y =   20.409  mm,    Z =   -299.631  mm,
    W =  -180.008 deg,    P =   0.082 deg,    R =   -0.997 deg
};
P[241]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350.938  mm,    Y =   -48.363  mm,    Z =   -298.954  mm,
    W =  -179.920 deg,    P =   0.133 deg,    R =   -0.988 deg
};
P[242]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  408.869  mm,    Y =   -113.800  mm,    Z =   -299.836  mm,
    W =  -179.994 deg,    P =   0.111 deg,    R =   -0.994 deg
};
P[243]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  265.853  mm,    Y =   24.448  mm,    Z =   -299.282  mm,
    W =  -179.964 deg,    P =   0.127 deg,    R =   -0.991 deg
};
P[244]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  258.929  mm,    Y =   31.760  mm,    Z =   -299.526  mm,
    W =  -179.945 deg,    P =   0.110 deg,    R =   -0.992 deg
};
P[245]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  378.299  mm,    Y =   -94.604  mm,    Z =   -299.258  mm,
    W =  -179.930 deg,    P =   0.166 deg,    R =   -0.984 deg
};
P[246]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  439.327  mm,    Y =   -19.717  mm,    Z =   -300.255  mm,
    W =  -179.964 deg,    P =   -0.049 deg,    R =   -0.998 deg
};
P[247]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  316.781  mm,    Y =   91.903  mm,    Z =   -300.640  mm,
    W =  -179.926 deg,    P =   -0.091 deg,    R =   -0.993 deg
};
P[248]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  307.022  mm,    Y =   90.164  mm,    Z =   -300.190  mm,
    W =  -179.921 deg,    P =   -0.058 deg,    R =   -0.995 deg
};
P[249]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  384.245  mm,    Y =   1.222  mm,    Z =   -300.885  mm,
    W =  -179.933 deg,    P =   0.058 deg,    R =   -0.996 deg
};
P[250]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  465.093  mm,    Y =   -92.009  mm,    Z =   -300.383  mm,
    W =  -180.060 deg,    P =   -0.012 deg,    R =   -0.998 deg
};
P[251]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  277.287  mm,    Y =   89.274  mm,    Z =   -300.567  mm,
    W =  -179.887 deg,    P =   -0.001 deg,    R =   -0.994 deg
};
P[252]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  398.495  mm,    Y =   -41.044  mm,    Z =   -300.852  mm,
    W =  -179.931 deg,    P =   0.057 deg,    R =   -0.996 deg
};
P[253]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  404.482  mm,    Y =   -48.491  mm,    Z =   -300.783  mm,
    W =  -179.941 deg,    P =   0.031 deg,    R =   -0.998 deg
};
P[254]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  376.638  mm,    Y =   -20.631  mm,    Z =   -300.482  mm,
    W =  -179.925 deg,    P =   0.084 deg,    R =   -0.994 deg
};
P[255]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  382.965  mm,    Y =   -27.381  mm,    Z =   -300.571  mm,
    W =  -179.920 deg,    P =   0.073 deg,    R =   -0.994 deg
};
P[256]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  368.973  mm,    Y =   -14.170  mm,    Z =   -300.312  mm,
    W =  -179.930 deg,    P =   0.089 deg,    R =   -0.994 deg
};
P[257]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  333.551  mm,    Y =   21.796  mm,    Z =   -300.123  mm,
    W =  -180.004 deg,    P =   0.036 deg,    R =   -0.999 deg
};
P[258]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  262.591  mm,    Y =   73.693  mm,    Z =   -300.384  mm,
    W =  -179.892 deg,    P =   0.028 deg,    R =   -0.994 deg
};
P[259]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  396.053  mm,    Y =   -61.602  mm,    Z =   -300.372  mm,
    W =  -179.931 deg,    P =   0.058 deg,    R =   -0.996 deg
};
P[260]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  381.829  mm,    Y =   -58.185  mm,    Z =   -300.822  mm,
    W =  -179.923 deg,    P =   0.083 deg,    R =   -0.994 deg
};
P[261]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  268.395  mm,    Y =   55.961  mm,    Z =   -300.679  mm,
    W =  -179.933 deg,    P =   0.027 deg,    R =   -0.997 deg
};
P[262]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  258.282  mm,    Y =   44.936  mm,    Z =   -300.693  mm,
    W =  -179.926 deg,    P =   0.069 deg,    R =   -0.995 deg
};
P[263]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  273.350  mm,    Y =   18.244  mm,    Z =   -300.562  mm,
    W =  -179.990 deg,    P =   0.131 deg,    R =   -0.991 deg
};
P[264]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  252.315  mm,    Y =   39.201  mm,    Z =   -300.397  mm,
    W =  -179.923 deg,    P =   0.093 deg,    R =   -0.993 deg
};
P[265]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  391.065  mm,    Y =   -104.388  mm,    Z =   -300.132  mm,
    W =  -179.946 deg,    P =   0.141 deg,    R =   -0.989 deg
};
P[266]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  254.039  mm,    Y =   27.407  mm,    Z =   -300.101  mm,
    W =  -179.951 deg,    P =   0.128 deg,    R =   -0.991 deg
};
P[267]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  246.616  mm,    Y =   34.615  mm,    Z =   -300.587  mm,
    W =  -179.922 deg,    P =   0.123 deg,    R =   -0.989 deg
};
P[268]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  250.661  mm,    Y =   23.415  mm,    Z =   -300.404  mm,
    W =  -179.958 deg,    P =   0.153 deg,    R =   -0.987 deg
};
P[269]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  243.820  mm,    Y =   29.941  mm,    Z =   -300.790  mm,
    W =  -179.924 deg,    P =   0.140 deg,    R =   -0.987 deg
};
P[270]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  476.183  mm,    Y =   -60.909  mm,    Z =   -301.131  mm,
    W =  -180.072 deg,    P =   -0.045 deg,    R =   -0.996 deg
};
P[271]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  338.268  mm,    Y =   70.254  mm,    Z =   -301.402  mm,
    W =  -179.997 deg,    P =   -0.067 deg,    R =   -0.998 deg
};
P[272]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  476.928  mm,    Y =   -73.297  mm,    Z =   -301.734  mm,
    W =  -180.075 deg,    P =   -0.037 deg,    R =   -0.996 deg
};
P[273]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  473.968  mm,    Y =   -88.138  mm,    Z =   -301.405  mm,
    W =  -180.097 deg,    P =   -0.033 deg,    R =   -0.995 deg
};
P[274]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  369.522  mm,    Y =   15.595  mm,    Z =   -301.073  mm,
    W =  -179.964 deg,    P =   0.061 deg,    R =   -0.997 deg
};
P[275]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  326.894  mm,    Y =   29.660  mm,    Z =   -301.356  mm,
    W =  -180.005 deg,    P =   0.030 deg,    R =   -1.000 deg
};
P[276]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  270.446  mm,    Y =   85.739  mm,    Z =   -301.078  mm,
    W =  -179.885 deg,    P =   0.009 deg,    R =   -0.993 deg
};
P[277]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  459.456  mm,    Y =   -105.461  mm,    Z =   -301.255  mm,
    W =  -180.071 deg,    P =   -0.010 deg,    R =   -0.997 deg
};
P[278]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  455.297  mm,    Y =   -113.109  mm,    Z =   -301.731  mm,
    W =  -180.086 deg,    P =   0.019 deg,    R =   -0.996 deg
};
P[279]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  305.310  mm,    Y =   35.452  mm,    Z =   -301.426  mm,
    W =  -179.990 deg,    P =   0.033 deg,    R =   -0.999 deg
};
P[280]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  262.387  mm,    Y =   79.245  mm,    Z =   -301.701  mm,
    W =  -179.879 deg,    P =   0.024 deg,    R =   -0.992 deg
};
P[281]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  299.791  mm,    Y =   34.971  mm,    Z =   -301.575  mm,
    W =  -179.985 deg,    P =   0.036 deg,    R =   -0.999 deg
};
P[282]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  296.425  mm,    Y =   27.664  mm,    Z =   -301.813  mm,
    W =  -179.993 deg,    P =   0.043 deg,    R =   -0.999 deg
};
P[283]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  372.591  mm,    Y =   -52.553  mm,    Z =   -301.676  mm,
    W =  -179.912 deg,    P =   0.114 deg,    R =   -0.990 deg
};
P[284]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  361.681  mm,    Y =   -46.792  mm,    Z =   -301.120  mm,
    W =  -179.914 deg,    P =   0.129 deg,    R =   -0.988 deg
};
P[285]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  262.211  mm,    Y =   49.948  mm,    Z =   -301.725  mm,
    W =  -179.923 deg,    P =   0.051 deg,    R =   -0.996 deg
};
P[286]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  399.810  mm,    Y =   -109.602  mm,    Z =   -301.124  mm,
    W =  -179.966 deg,    P =   0.136 deg,    R =   -0.990 deg
};
P[287]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  255.210  mm,    Y =   18.028  mm,    Z =   -301.526  mm,
    W =  -179.972 deg,    P =   0.163 deg,    R =   -0.986 deg
};
P[288]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  244.102  mm,    Y =   16.890  mm,    Z =   -301.562  mm,
    W =  -179.964 deg,    P =   0.174 deg,    R =   -0.984 deg
};
P[289]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  328.342  mm,    Y =   86.078  mm,    Z =   -302.771  mm,
    W =  -179.953 deg,    P =   -0.097 deg,    R =   -0.994 deg
};
P[290]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  333.144  mm,    Y =   76.598  mm,    Z =   -302.007  mm,
    W =  -179.977 deg,    P =   -0.079 deg,    R =   -0.997 deg
};
P[291]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  345.317  mm,    Y =   59.870  mm,    Z =   -302.602  mm,
    W =  -180.005 deg,    P =   -0.035 deg,    R =   -0.999 deg
};
P[292]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  301.338  mm,    Y =   94.359  mm,    Z =   -302.448  mm,
    W =  -179.890 deg,    P =   -0.064 deg,    R =   -0.992 deg
};
P[293]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  286.140  mm,    Y =   99.924  mm,    Z =   -302.421  mm,
    W =  -179.854 deg,    P =   -0.053 deg,    R =   -0.988 deg
};
P[294]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  377.128  mm,    Y =   8.249  mm,    Z =   -302.447  mm,
    W =  -179.951 deg,    P =   0.067 deg,    R =   -0.997 deg
};
P[295]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  279.304  mm,    Y =   95.097  mm,    Z =   -302.067  mm,
    W =  -179.869 deg,    P =   -0.020 deg,    R =   -0.991 deg
};
P[296]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  262.222  mm,    Y =   63.361  mm,    Z =   -302.032  mm,
    W =  -179.909 deg,    P =   0.033 deg,    R =   -0.995 deg
};
P[297]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  291.193  mm,    Y =   18.926  mm,    Z =   -302.723  mm,
    W =  -180.005 deg,    P =   0.066 deg,    R =   -0.998 deg
};
P[298]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  252.819  mm,    Y =   50.120  mm,    Z =   -301.987  mm,
    W =  -179.906 deg,    P =   0.069 deg,    R =   -0.993 deg
};
P[299]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  415.907  mm,    Y =   -116.002  mm,    Z =   -302.224  mm,
    W =  -180.011 deg,    P =   0.095 deg,    R =   -0.995 deg
};
P[300]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  344.877  mm,    Y =   -52.130  mm,    Z =   -302.106  mm,
    W =  -179.920 deg,    P =   0.131 deg,    R =   -0.988 deg
};
P[301]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  246.205  mm,    Y =   46.875  mm,    Z =   -302.707  mm,
    W =  -179.895 deg,    P =   0.085 deg,    R =   -0.991 deg
};
P[302]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  260.470  mm,    Y =   17.688  mm,    Z =   -302.056  mm,
    W =  -179.974 deg,    P =   0.157 deg,    R =   -0.987 deg
};
P[303]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  238.344  mm,    Y =   34.335  mm,    Z =   -302.013  mm,
    W =  -179.908 deg,    P =   0.137 deg,    R =   -0.986 deg
};
P[304]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  237.202  mm,    Y =   24.421  mm,    Z =   -302.504  mm,
    W =  -179.932 deg,    P =   0.163 deg,    R =   -0.984 deg
};
P[305]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  470.692  mm,    Y =   -38.588  mm,    Z =   -303.162  mm,
    W =  -180.035 deg,    P =   -0.074 deg,    R =   -0.997 deg
};
P[306]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  323.138  mm,    Y =   93.566  mm,    Z =   -303.233  mm,
    W =  -179.928 deg,    P =   -0.113 deg,    R =   -0.991 deg
};
P[307]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  348.959  mm,    Y =   51.431  mm,    Z =   -303.799  mm,
    W =  -180.008 deg,    P =   -0.007 deg,    R =   -1.000 deg
};
P[308]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349.710  mm,    Y =   47.277  mm,    Z =   -303.663  mm,
    W =  -180.005 deg,    P =   -0.002 deg,    R =   -1.000 deg
};
P[309]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  297.934  mm,    Y =   98.621  mm,    Z =   -303.258  mm,
    W =  -179.876 deg,    P =   -0.066 deg,    R =   -0.990 deg
};
P[310]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  279.795  mm,    Y =   104.515  mm,    Z =   -303.898  mm,
    W =  -179.836 deg,    P =   -0.052 deg,    R =   -0.985 deg
};
P[311]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  264.857  mm,    Y =   91.240  mm,    Z =   -303.746  mm,
    W =  -179.864 deg,    P =   0.008 deg,    R =   -0.991 deg
};
P[312]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  312.512  mm,    Y =   29.156  mm,    Z =   -303.763  mm,
    W =  -180.000 deg,    P =   0.036 deg,    R =   -0.999 deg
};
P[313]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  302.515  mm,    Y =   29.446  mm,    Z =   -303.761  mm,
    W =  -179.994 deg,    P =   0.042 deg,    R =   -0.999 deg
};
P[314]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  256.306  mm,    Y =   70.095  mm,    Z =   -303.640  mm,
    W =  -179.888 deg,    P =   0.034 deg,    R =   -0.993 deg
};
P[315]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  366.676  mm,    Y =   -45.842  mm,    Z =   -303.724  mm,
    W =  -179.916 deg,    P =   0.118 deg,    R =   -0.989 deg
};
P[316]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  431.688  mm,    Y =   -119.111  mm,    Z =   -303.638  mm,
    W =  -180.050 deg,    P =   0.045 deg,    R =   -0.998 deg
};
P[317]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  254.815  mm,    Y =   56.569  mm,    Z =   -303.458  mm,
    W =  -179.900 deg,    P =   0.052 deg,    R =   -0.994 deg
};
P[318]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  238.228  mm,    Y =   40.212  mm,    Z =   -303.020  mm,
    W =  -179.886 deg,    P =   0.122 deg,    R =   -0.986 deg
};
P[319]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  251.593  mm,    Y =   10.462  mm,    Z =   -303.111  mm,
    W =  -179.989 deg,    P =   0.190 deg,    R =   -0.982 deg
};
P[320]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  455.763  mm,    Y =   -27.263  mm,    Z =   -303.992  mm,
    W =  -179.974 deg,    P =   -0.072 deg,    R =   -0.997 deg
};
P[321]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  308.379  mm,    Y =   95.281  mm,    Z =   -304.072  mm,
    W =  -179.895 deg,    P =   -0.083 deg,    R =   -0.991 deg
};
P[322]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  393.257  mm,    Y =   2.299  mm,    Z =   -304.768  mm,
    W =  -179.930 deg,    P =   0.049 deg,    R =   -0.996 deg
};
P[323]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  469.160  mm,    Y =   -92.474  mm,    Z =   -303.936  mm,
    W =  -180.080 deg,    P =   -0.018 deg,    R =   -0.997 deg
};
P[324]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  356.403  mm,    Y =   -11.587  mm,    Z =   -304.758  mm,
    W =  -179.950 deg,    P =   0.098 deg,    R =   -0.994 deg
};
P[325]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  398.598  mm,    Y =   -54.992  mm,    Z =   -304.335  mm,
    W =  -179.934 deg,    P =   0.049 deg,    R =   -0.997 deg
};
P[326]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  348.627  mm,    Y =   -6.088  mm,    Z =   -304.708  mm,
    W =  -179.972 deg,    P =   0.092 deg,    R =   -0.995 deg
};
P[327]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  341.361  mm,    Y =   0.937  mm,    Z =   -304.452  mm,
    W =  -179.985 deg,    P =   0.075 deg,    R =   -0.997 deg
};
P[328]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  334.084  mm,    Y =   7.931  mm,    Z =   -304.142  mm,
    W =  -179.998 deg,    P =   0.057 deg,    R =   -0.998 deg
};
P[329]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  327.071  mm,    Y =   15.256  mm,    Z =   -304.463  mm,
    W =  -180.008 deg,    P =   0.053 deg,    R =   -0.999 deg
};
P[330]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  319.985  mm,    Y =   22.503  mm,    Z =   -304.634  mm,
    W =  -180.006 deg,    P =   0.041 deg,    R =   -0.999 deg
};
P[331]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  254.884  mm,    Y =   75.650  mm,    Z =   -304.458  mm,
    W =  -179.877 deg,    P =   0.032 deg,    R =   -0.992 deg
};
P[332]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  354.476  mm,    Y =   -41.977  mm,    Z =   -304.333  mm,
    W =  -179.920 deg,    P =   0.123 deg,    R =   -0.989 deg
};
P[333]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  423.990  mm,    Y =   -118.073  mm,    Z =   -304.494  mm,
    W =  -180.024 deg,    P =   0.073 deg,    R =   -0.997 deg
};
P[334]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  346.232  mm,    Y =   -44.867  mm,    Z =   -303.939  mm,
    W =  -179.932 deg,    P =   0.128 deg,    R =   -0.989 deg
};
P[335]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  247.187  mm,    Y =   53.734  mm,    Z =   -304.105  mm,
    W =  -179.886 deg,    P =   0.085 deg,    R =   -0.990 deg
};
P[336]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  286.410  mm,    Y =   13.619  mm,    Z =   -304.554  mm,
    W =  -180.011 deg,    P =   0.093 deg,    R =   -0.996 deg
};
P[337]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  280.898  mm,    Y =   12.719  mm,    Z =   -304.291  mm,
    W =  -180.012 deg,    P =   0.118 deg,    R =   -0.993 deg
};
P[338]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  343.759  mm,    Y =   -66.037  mm,    Z =   -304.504  mm,
    W =  -179.912 deg,    P =   0.179 deg,    R =   -0.980 deg
};
P[339]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  259.008  mm,    Y =   10.876  mm,    Z =   -304.449  mm,
    W =  -179.990 deg,    P =   0.181 deg,    R =   -0.984 deg
};
P[340]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  232.764  mm,    Y =   30.349  mm,    Z =   -304.899  mm,
    W =  -179.905 deg,    P =   0.153 deg,    R =   -0.984 deg
};
P[341]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  257.590  mm,    Y =   3.913  mm,    Z =   -304.526  mm,
    W =  -180.009 deg,    P =   0.210 deg,    R =   -0.978 deg
};
P[342]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  462.301  mm,    Y =   -29.254  mm,    Z =   -305.019  mm,
    W =  -179.981 deg,    P =   -0.091 deg,    R =   -0.996 deg
};
P[343]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  325.232  mm,    Y =   94.603  mm,    Z =   -305.265  mm,
    W =  -179.932 deg,    P =   -0.126 deg,    R =   -0.990 deg
};
P[344]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  367.972  mm,    Y =   25.507  mm,    Z =   -305.265  mm,
    W =  -179.976 deg,    P =   0.062 deg,    R =   -0.998 deg
};
P[345]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  272.929  mm,    Y =   101.804  mm,    Z =   -305.113  mm,
    W =  -179.835 deg,    P =   -0.035 deg,    R =   -0.986 deg
};
P[346]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  265.038  mm,    Y =   96.534  mm,    Z =   -305.681  mm,
    W =  -179.844 deg,    P =   -0.005 deg,    R =   -0.988 deg
};
P[347]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  365.706  mm,    Y =   -17.026  mm,    Z =   -305.191  mm,
    W =  -179.934 deg,    P =   0.088 deg,    R =   -0.994 deg
};
P[348]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  257.186  mm,    Y =   86.361  mm,    Z =   -305.763  mm,
    W =  -179.860 deg,    P =   0.025 deg,    R =   -0.990 deg
};
P[349]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  307.255  mm,    Y =   22.643  mm,    Z =   -305.451  mm,
    W =  -180.001 deg,    P =   0.046 deg,    R =   -0.999 deg
};
P[350]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  303.051  mm,    Y =   19.985  mm,    Z =   -305.380  mm,
    W =  -180.004 deg,    P =   0.052 deg,    R =   -0.999 deg
};
P[351]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  297.992  mm,    Y =   14.458  mm,    Z =   -305.818  mm,
    W =  -180.010 deg,    P =   0.069 deg,    R =   -0.998 deg
};
P[352]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  248.131  mm,    Y =   63.507  mm,    Z =   -305.280  mm,
    W =  -179.880 deg,    P =   0.060 deg,    R =   -0.991 deg
};
P[353]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  240.243  mm,    Y =   51.171  mm,    Z =   -305.540  mm,
    W =  -179.883 deg,    P =   0.089 deg,    R =   -0.989 deg
};
P[354]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  382.258  mm,    Y =   -98.603  mm,    Z =   -305.691  mm,
    W =  -179.935 deg,    P =   0.154 deg,    R =   -0.986 deg
};
P[355]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  373.941  mm,    Y =   -93.815  mm,    Z =   -305.319  mm,
    W =  -179.921 deg,    P =   0.173 deg,    R =   -0.982 deg
};
P[356]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  365.920  mm,    Y =   -87.290  mm,    Z =   -305.809  mm,
    W =  -179.914 deg,    P =   0.190 deg,    R =   -0.978 deg
};
P[357]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  267.341  mm,    Y =   12.085  mm,    Z =   -305.187  mm,
    W =  -179.994 deg,    P =   0.164 deg,    R =   -0.986 deg
};
P[358]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350.455  mm,    Y =   -74.236  mm,    Z =   -305.633  mm,
    W =  -179.906 deg,    P =   0.199 deg,    R =   -0.975 deg
};
P[359]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  237.265  mm,    Y =   9.877  mm,    Z =   -305.184  mm,
    W =  -179.970 deg,    P =   0.191 deg,    R =   -0.981 deg
};
P[360]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  479.245  mm,    Y =   -44.996  mm,    Z =   -306.078  mm,
    W =  -180.068 deg,    P =   -0.092 deg,    R =   -0.993 deg
};
P[361]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  331.263  mm,    Y =   88.761  mm,    Z =   -306.893  mm,
    W =  -179.951 deg,    P =   -0.123 deg,    R =   -0.991 deg
};
P[362]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  300.813  mm,    Y =   102.034  mm,    Z =   -306.717  mm,
    W =  -179.868 deg,    P =   -0.088 deg,    R =   -0.987 deg
};
P[363]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  361.060  mm,    Y =   38.933  mm,    Z =   -306.497  mm,
    W =  -179.992 deg,    P =   0.026 deg,    R =   -1.000 deg
};
P[364]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  356.343  mm,    Y =   43.364  mm,    Z =   -306.227  mm,
    W =  -179.999 deg,    P =   0.015 deg,    R =   -1.000 deg
};
P[365]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  290.173  mm,    Y =   106.113  mm,    Z =   -306.285  mm,
    W =  -179.846 deg,    P =   -0.075 deg,    R =   -0.985 deg
};
P[366]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  464.721  mm,    Y =   -100.490  mm,    Z =   -306.637  mm,
    W =  -180.070 deg,    P =   -0.016 deg,    R =   -0.997 deg
};
P[367]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  373.392  mm,    Y =   -22.593  mm,    Z =   -306.495  mm,
    W =  -179.928 deg,    P =   0.086 deg,    R =   -0.994 deg
};
P[368]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  320.490  mm,    Y =   8.398  mm,    Z =   -306.287  mm,
    W =  -180.011 deg,    P =   0.065 deg,    R =   -0.998 deg
};
P[369]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  313.107  mm,    Y =   15.166  mm,    Z =   -306.307  mm,
    W =  -180.007 deg,    P =   0.054 deg,    R =   -0.999 deg
};
P[370]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  317.577  mm,    Y =   4.673  mm,    Z =   -306.280  mm,
    W =  -180.013 deg,    P =   0.068 deg,    R =   -0.998 deg
};
P[371]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  249.498  mm,    Y =   72.748  mm,    Z =   -306.280  mm,
    W =  -179.870 deg,    P =   0.045 deg,    R =   -0.990 deg
};
P[372]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  290.962  mm,    Y =   6.715  mm,    Z =   -306.429  mm,
    W =  -180.025 deg,    P =   0.099 deg,    R =   -0.995 deg
};
P[373]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  338.685  mm,    Y =   -47.181  mm,    Z =   -306.166  mm,
    W =  -179.937 deg,    P =   0.123 deg,    R =   -0.990 deg
};
P[374]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  285.723  mm,    Y =   5.743  mm,    Z =   -306.528  mm,
    W =  -180.019 deg,    P =   0.118 deg,    R =   -0.993 deg
};
P[375]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  390.680  mm,    Y =   -104.256  mm,    Z =   -306.366  mm,
    W =  -179.944 deg,    P =   0.142 deg,    R =   -0.988 deg
};
P[376]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  338.847  mm,    Y =   -58.050  mm,    Z =   -306.842  mm,
    W =  -179.918 deg,    P =   0.146 deg,    R =   -0.986 deg
};
P[377]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  358.350  mm,    Y =   -81.087  mm,    Z =   -306.440  mm,
    W =  -179.907 deg,    P =   0.202 deg,    R =   -0.975 deg
};
P[378]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  262.927  mm,    Y =   4.381  mm,    Z =   -306.153  mm,
    W =  -180.014 deg,    P =   0.201 deg,    R =   -0.979 deg
};
P[379]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  230.747  mm,    Y =   35.030  mm,    Z =   -306.700  mm,
    W =  -179.887 deg,    P =   0.143 deg,    R =   -0.983 deg
};
P[380]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  231.008  mm,    Y =   17.753  mm,    Z =   -306.349  mm,
    W =  -179.929 deg,    P =   0.180 deg,    R =   -0.981 deg
};
P[381]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  387.899  mm,    Y =   6.412  mm,    Z =   -307.048  mm,
    W =  -179.934 deg,    P =   0.055 deg,    R =   -0.996 deg
};
P[382]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  381.037  mm,    Y =   12.249  mm,    Z =   -307.563  mm,
    W =  -179.955 deg,    P =   0.053 deg,    R =   -0.998 deg
};
P[383]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  249.914  mm,    Y =   79.737  mm,    Z =   -307.637  mm,
    W =  -179.855 deg,    P =   0.036 deg,    R =   -0.989 deg
};
P[384]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  319.792  mm,    Y =   1.424  mm,    Z =   -307.801  mm,
    W =  -180.009 deg,    P =   0.069 deg,    R =   -0.998 deg
};
P[385]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  310.411  mm,    Y =   10.805  mm,    Z =   -307.801  mm,
    W =  -180.014 deg,    P =   0.066 deg,    R =   -0.998 deg
};
P[386]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  313.050  mm,    Y =   0.566  mm,    Z =   -307.426  mm,
    W =  -180.017 deg,    P =   0.081 deg,    R =   -0.997 deg
};
P[387]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  305.646  mm,    Y =   7.674  mm,    Z =   -307.902  mm,
    W =  -180.018 deg,    P =   0.078 deg,    R =   -0.997 deg
};
P[388]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  242.240  mm,    Y =   70.955  mm,    Z =   -307.662  mm,
    W =  -179.851 deg,    P =   0.070 deg,    R =   -0.986 deg
};
P[389]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  240.827  mm,    Y =   57.371  mm,    Z =   -307.016  mm,
    W =  -179.868 deg,    P =   0.084 deg,    R =   -0.988 deg
};
P[390]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  254.306  mm,    Y =   0.938  mm,    Z =   -307.165  mm,
    W =  -180.017 deg,    P =   0.214 deg,    R =   -0.977 deg
};
P[391]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  245.241  mm,    Y =   5.574  mm,    Z =   -307.114  mm,
    W =  -180.000 deg,    P =   0.196 deg,    R =   -0.981 deg
};
P[392]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  477.266  mm,    Y =   -37.191  mm,    Z =   -308.795  mm,
    W =  -180.039 deg,    P =   -0.112 deg,    R =   -0.993 deg
};
P[393]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  348.625  mm,    Y =   66.854  mm,    Z =   -308.602  mm,
    W =  -180.004 deg,    P =   -0.072 deg,    R =   -0.997 deg
};
P[394]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  375.040  mm,    Y =   19.677  mm,    Z =   -308.103  mm,
    W =  -179.962 deg,    P =   0.065 deg,    R =   -0.997 deg
};
P[395]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  281.313  mm,    Y =   110.110  mm,    Z =   -308.119  mm,
    W =  -179.819 deg,    P =   -0.074 deg,    R =   -0.981 deg
};
P[396]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  274.018  mm,    Y =   108.625  mm,    Z =   -308.111  mm,
    W =  -179.816 deg,    P =   -0.057 deg,    R =   -0.981 deg
};
P[397]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  385.241  mm,    Y =   -29.808  mm,    Z =   -308.528  mm,
    W =  -179.920 deg,    P =   0.069 deg,    R =   -0.994 deg
};
P[398]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  258.694  mm,    Y =   94.566  mm,    Z =   -308.210  mm,
    W =  -179.840 deg,    P =   0.012 deg,    R =   -0.987 deg
};
P[399]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  462.602  mm,    Y =   -111.159  mm,    Z =   -308.897  mm,
    W =  -180.076 deg,    P =   -0.007 deg,    R =   -0.997 deg
};
P[400]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  386.736  mm,    Y =   -53.058  mm,    Z =   -307.930  mm,
    W =  -179.927 deg,    P =   0.076 deg,    R =   -0.994 deg
};
P[401]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  243.364  mm,    Y =   76.907  mm,    Z =   -308.533  mm,
    W =  -179.845 deg,    P =   0.053 deg,    R =   -0.986 deg
};
P[402]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  347.088  mm,    Y =   -37.551  mm,    Z =   -308.328  mm,
    W =  -179.936 deg,    P =   0.119 deg,    R =   -0.991 deg
};
P[403]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  317.622  mm,    Y =   -7.327  mm,    Z =   -308.450  mm,
    W =  -180.014 deg,    P =   0.082 deg,    R =   -0.997 deg
};
P[404]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  340.888  mm,    Y =   -41.278  mm,    Z =   -308.028  mm,
    W =  -179.938 deg,    P =   0.119 deg,    R =   -0.991 deg
};
P[405]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  311.948  mm,    Y =   -13.770  mm,    Z =   -308.246  mm,
    W =  -180.014 deg,    P =   0.096 deg,    R =   -0.995 deg
};
P[406]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  304.785  mm,    Y =   -6.599  mm,    Z =   -308.416  mm,
    W =  -180.024 deg,    P =   0.096 deg,    R =   -0.995 deg
};
P[407]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  297.731  mm,    Y =   0.463  mm,    Z =   -308.257  mm,
    W =  -180.027 deg,    P =   0.099 deg,    R =   -0.995 deg
};
P[408]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  318.821  mm,    Y =   -21.469  mm,    Z =   -308.075  mm,
    W =  -180.002 deg,    P =   0.095 deg,    R =   -0.995 deg
};
P[409]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  332.592  mm,    Y =   -50.508  mm,    Z =   -308.438  mm,
    W =  -179.939 deg,    P =   0.124 deg,    R =   -0.990 deg
};
P[410]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  275.706  mm,    Y =   6.623  mm,    Z =   -308.537  mm,
    W =  -180.017 deg,    P =   0.162 deg,    R =   -0.987 deg
};
P[411]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  233.333  mm,    Y =   47.596  mm,    Z =   -307.948  mm,
    W =  -179.870 deg,    P =   0.113 deg,    R =   -0.985 deg
};
P[412]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  227.008  mm,    Y =   25.482  mm,    Z =   -308.345  mm,
    W =  -179.900 deg,    P =   0.170 deg,    R =   -0.980 deg
};
P[413]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  293.194  mm,    Y =   110.230  mm,    Z =   -309.736  mm,
    W =  -179.838 deg,    P =   -0.099 deg,    R =   -0.982 deg
};
P[414]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  266.628  mm,    Y =   106.664  mm,    Z =   -308.984  mm,
    W =  -179.808 deg,    P =   -0.043 deg,    R =   -0.980 deg
};
P[415]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  396.985  mm,    Y =   -40.296  mm,    Z =   -309.188  mm,
    W =  -179.931 deg,    P =   0.056 deg,    R =   -0.996 deg
};
P[416]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  398.682  mm,    Y =   -49.201  mm,    Z =   -309.445  mm,
    W =  -179.940 deg,    P =   0.048 deg,    R =   -0.997 deg
};
P[417]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  252.564  mm,    Y =   90.416  mm,    Z =   -309.357  mm,
    W =  -179.844 deg,    P =   0.024 deg,    R =   -0.988 deg
};
P[418]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  392.206  mm,    Y =   -52.143  mm,    Z =   -309.022  mm,
    W =  -179.931 deg,    P =   0.066 deg,    R =   -0.995 deg
};
P[419]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  370.588  mm,    Y =   -39.833  mm,    Z =   -309.745  mm,
    W =  -179.917 deg,    P =   0.103 deg,    R =   -0.991 deg
};
P[420]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  324.762  mm,    Y =   -16.075  mm,    Z =   -309.761  mm,
    W =  -179.998 deg,    P =   0.086 deg,    R =   -0.996 deg
};
P[421]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  420.714  mm,    Y =   -116.108  mm,    Z =   -309.801  mm,
    W =  -180.020 deg,    P =   0.072 deg,    R =   -0.997 deg
};
P[422]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  403.034  mm,    Y =   -109.848  mm,    Z =   -309.847  mm,
    W =  -179.966 deg,    P =   0.129 deg,    R =   -0.991 deg
};
P[423]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  287.383  mm,    Y =   -4.303  mm,    Z =   -309.680  mm,
    W =  -180.028 deg,    P =   0.140 deg,    R =   -0.990 deg
};
P[424]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  283.483  mm,    Y =   0.146  mm,    Z =   -309.416  mm,
    W =  -180.030 deg,    P =   0.148 deg,    R =   -0.989 deg
};
P[425]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  327.261  mm,    Y =   -46.188  mm,    Z =   -309.832  mm,
    W =  -179.958 deg,    P =   0.122 deg,    R =   -0.992 deg
};
P[426]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  468.388  mm,    Y =   -26.806  mm,    Z =   -310.116  mm,
    W =  -180.003 deg,    P =   -0.126 deg,    R =   -0.992 deg
};
P[427]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  336.291  mm,    Y =   86.503  mm,    Z =   -310.382  mm,
    W =  -179.963 deg,    P =   -0.132 deg,    R =   -0.991 deg
};
P[428]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  259.909  mm,    Y =   103.063  mm,    Z =   -310.188  mm,
    W =  -179.800 deg,    P =   -0.022 deg,    R =   -0.979 deg
};
P[429]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  391.301  mm,    Y =   -33.777  mm,    Z =   -310.061  mm,
    W =  -179.922 deg,    P =   0.066 deg,    R =   -0.995 deg
};
P[430]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  377.960  mm,    Y =   -45.698  mm,    Z =   -310.255  mm,
    W =  -179.918 deg,    P =   0.093 deg,    R =   -0.992 deg
};
P[431]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  328.036  mm,    Y =   3.753  mm,    Z =   -310.421  mm,
    W =  -180.006 deg,    P =   0.066 deg,    R =   -0.998 deg
};
P[432]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  357.106  mm,    Y =   -36.363  mm,    Z =   -309.961  mm,
    W =  -179.928 deg,    P =   0.119 deg,    R =   -0.990 deg
};
P[433]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  236.573  mm,    Y =   74.501  mm,    Z =   -310.480  mm,
    W =  -179.836 deg,    P =   0.075 deg,    R =   -0.984 deg
};
P[434]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  331.705  mm,    Y =   -22.213  mm,    Z =   -310.699  mm,
    W =  -179.977 deg,    P =   0.093 deg,    R =   -0.995 deg
};
P[435]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  411.528  mm,    Y =   -112.897  mm,    Z =   -310.631  mm,
    W =  -179.998 deg,    P =   0.098 deg,    R =   -0.995 deg
};
P[436]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  233.143  mm,    Y =   53.449  mm,    Z =   -310.483  mm,
    W =  -179.861 deg,    P =   0.105 deg,    R =   -0.985 deg
};
P[437]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  226.434  mm,    Y =   41.672  mm,    Z =   -310.806  mm,
    W =  -179.866 deg,    P =   0.136 deg,    R =   -0.982 deg
};
P[438]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  344.317  mm,    Y =   79.652  mm,    Z =   -311.450  mm,
    W =  -180.000 deg,    P =   -0.133 deg,    R =   -0.991 deg
};
P[439]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  312.978  mm,    Y =   103.104  mm,    Z =   -311.206  mm,
    W =  -179.878 deg,    P =   -0.122 deg,    R =   -0.985 deg
};
P[440]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  305.617  mm,    Y =   106.322  mm,    Z =   -311.745  mm,
    W =  -179.862 deg,    P =   -0.115 deg,    R =   -0.984 deg
};
P[441]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  275.653  mm,    Y =   114.621  mm,    Z =   -311.565  mm,
    W =  -179.793 deg,    P =   -0.073 deg,    R =   -0.976 deg
};
P[442]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  268.722  mm,    Y =   112.624  mm,    Z =   -311.780  mm,
    W =  -179.788 deg,    P =   -0.059 deg,    R =   -0.975 deg
};
P[443]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  468.233  mm,    Y =   -107.293  mm,    Z =   -310.989  mm,
    W =  -180.077 deg,    P =   -0.014 deg,    R =   -0.997 deg
};
P[444]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  252.340  mm,    Y =   96.510  mm,    Z =   -311.658  mm,
    W =  -179.812 deg,    P =   0.009 deg,    R =   -0.982 deg
};
P[445]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  339.518  mm,    Y =   -0.589  mm,    Z =   -311.335  mm,
    W =  -179.989 deg,    P =   0.077 deg,    R =   -0.997 deg
};
P[446]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  243.617  mm,    Y =   86.532  mm,    Z =   -311.083  mm,
    W =  -179.827 deg,    P =   0.042 deg,    R =   -0.984 deg
};
P[447]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  363.377  mm,    Y =   -35.453  mm,    Z =   -311.438  mm,
    W =  -179.923 deg,    P =   0.112 deg,    R =   -0.991 deg
};
P[448]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  342.449  mm,    Y =   -32.712  mm,    Z =   -310.984  mm,
    W =  -179.946 deg,    P =   0.109 deg,    R =   -0.993 deg
};
P[449]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  327.635  mm,    Y =   -27.227  mm,    Z =   -311.239  mm,
    W =  -179.980 deg,    P =   0.093 deg,    R =   -0.995 deg
};
P[450]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  235.635  mm,    Y =   64.934  mm,    Z =   -311.275  mm,
    W =  -179.848 deg,    P =   0.084 deg,    R =   -0.985 deg
};
P[451]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  326.448  mm,    Y =   -40.844  mm,    Z =   -311.631  mm,
    W =  -179.966 deg,    P =   0.113 deg,    R =   -0.993 deg
};
P[452]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  312.663  mm,    Y =   -27.831  mm,    Z =   -311.603  mm,
    W =  -180.005 deg,    P =   0.104 deg,    R =   -0.995 deg
};
P[453]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  291.002  mm,    Y =   -6.810  mm,    Z =   -311.060  mm,
    W =  -180.034 deg,    P =   0.138 deg,    R =   -0.990 deg
};
P[454]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  283.325  mm,    Y =   -1.832  mm,    Z =   -311.410  mm,
    W =  -180.030 deg,    P =   0.159 deg,    R =   -0.987 deg
};
P[455]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  342.342  mm,    Y =   -67.432  mm,    Z =   -311.495  mm,
    W =  -179.913 deg,    P =   0.186 deg,    R =   -0.979 deg
};
P[456]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  335.798  mm,    Y =   -61.200  mm,    Z =   -311.900  mm,
    W =  -179.922 deg,    P =   0.169 deg,    R =   -0.983 deg
};
P[457]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  267.806  mm,    Y =   1.201  mm,    Z =   -311.731  mm,
    W =  -180.019 deg,    P =   0.202 deg,    R =   -0.979 deg
};
P[458]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  261.007  mm,    Y =   110.214  mm,    Z =   -312.028  mm,
    W =  -179.783 deg,    P =   -0.041 deg,    R =   -0.975 deg
};
P[459]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  380.009  mm,    Y =   -30.484  mm,    Z =   -312.506  mm,
    W =  -179.916 deg,    P =   0.081 deg,    R =   -0.993 deg
};
P[460]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  371.989  mm,    Y =   -24.517  mm,    Z =   -312.802  mm,
    W =  -179.927 deg,    P =   0.087 deg,    R =   -0.994 deg
};
P[461]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  345.477  mm,    Y =   -11.133  mm,    Z =   -312.714  mm,
    W =  -179.971 deg,    P =   0.093 deg,    R =   -0.995 deg
};
P[462]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  323.099  mm,    Y =   -3.670  mm,    Z =   -312.356  mm,
    W =  -180.010 deg,    P =   0.079 deg,    R =   -0.997 deg
};
P[463]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  236.168  mm,    Y =   80.682  mm,    Z =   -312.049  mm,
    W =  -179.817 deg,    P =   0.073 deg,    R =   -0.980 deg
};
P[464]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  334.539  mm,    Y =   -35.402  mm,    Z =   -312.172  mm,
    W =  -179.960 deg,    P =   0.109 deg,    R =   -0.993 deg
};
P[465]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  298.187  mm,    Y =   -13.024  mm,    Z =   -312.272  mm,
    W =  -180.030 deg,    P =   0.123 deg,    R =   -0.992 deg
};
P[466]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  277.051  mm,    Y =   1.453  mm,    Z =   -312.533  mm,
    W =  -180.019 deg,    P =   0.165 deg,    R =   -0.986 deg
};
P[467]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350.353  mm,    Y =   -74.486  mm,    Z =   -312.070  mm,
    W =  -179.905 deg,    P =   0.193 deg,    R =   -0.977 deg
};
P[468]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  324.470  mm,    Y =   -49.110  mm,    Z =   -312.584  mm,
    W =  -179.960 deg,    P =   0.137 deg,    R =   -0.990 deg
};
P[469]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  328.978  mm,    Y =   -54.136  mm,    Z =   -312.213  mm,
    W =  -179.941 deg,    P =   0.141 deg,    R =   -0.988 deg
};
P[470]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  224.138  mm,    Y =   26.910  mm,    Z =   -312.837  mm,
    W =  -179.901 deg,    P =   0.168 deg,    R =   -0.981 deg
};
P[471]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  234.733  mm,    Y =   6.960  mm,    Z =   -312.701  mm,
    W =  -179.967 deg,    P =   0.194 deg,    R =   -0.980 deg
};
P[472]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  404.698  mm,    Y =   7.474  mm,    Z =   -312.961  mm,
    W =  -179.916 deg,    P =   0.004 deg,    R =   -0.996 deg
};
P[473]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  365.301  mm,    Y =   45.184  mm,    Z =   -313.878  mm,
    W =  -179.994 deg,    P =   -0.000 deg,    R =   -1.000 deg
};
P[474]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  296.689  mm,    Y =   113.280  mm,    Z =   -313.080  mm,
    W =  -179.841 deg,    P =   -0.116 deg,    R =   -0.980 deg
};
P[475]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  287.104  mm,    Y =   115.867  mm,    Z =   -313.304  mm,
    W =  -179.811 deg,    P =   -0.097 deg,    R =   -0.977 deg
};
P[476]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  254.159  mm,    Y =   107.002  mm,    Z =   -313.545  mm,
    W =  -179.774 deg,    P =   -0.027 deg,    R =   -0.974 deg
};
P[477]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  366.514  mm,    Y =   -17.123  mm,    Z =   -313.472  mm,
    W =  -179.934 deg,    P =   0.091 deg,    R =   -0.994 deg
};
P[478]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  246.067  mm,    Y =   93.366  mm,    Z =   -312.955  mm,
    W =  -179.815 deg,    P =   0.019 deg,    R =   -0.982 deg
};
P[479]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  351.096  mm,    Y =   -32.006  mm,    Z =   -313.068  mm,
    W =  -179.934 deg,    P =   0.115 deg,    R =   -0.991 deg
};
P[480]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  336.871  mm,    Y =   -18.621  mm,    Z =   -313.411  mm,
    W =  -179.973 deg,    P =   0.088 deg,    R =   -0.996 deg
};
P[481]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  342.651  mm,    Y =   -25.509  mm,    Z =   -313.863  mm,
    W =  -179.957 deg,    P =   0.100 deg,    R =   -0.994 deg
};
P[482]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  337.276  mm,    Y =   -29.903  mm,    Z =   -313.383  mm,
    W =  -179.955 deg,    P =   0.100 deg,    R =   -0.994 deg
};
P[483]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  232.026  mm,    Y =   70.349  mm,    Z =   -313.427  mm,
    W =  -179.832 deg,    P =   0.083 deg,    R =   -0.982 deg
};
P[484]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  399.739  mm,    Y =   -108.172  mm,    Z =   -313.698  mm,
    W =  -179.956 deg,    P =   0.127 deg,    R =   -0.991 deg
};
P[485]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  320.534  mm,    Y =   -34.609  mm,    Z =   -313.211  mm,
    W =  -179.981 deg,    P =   0.104 deg,    R =   -0.994 deg
};
P[486]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  305.464  mm,    Y =   -19.984  mm,    Z =   -312.953  mm,
    W =  -180.021 deg,    P =   0.108 deg,    R =   -0.994 deg
};
P[487]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  373.608  mm,    Y =   -94.104  mm,    Z =   -313.433  mm,
    W =  -179.919 deg,    P =   0.180 deg,    R =   -0.980 deg
};
P[488]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  366.379  mm,    Y =   -87.526  mm,    Z =   -312.970  mm,
    W =  -179.912 deg,    P =   0.191 deg,    R =   -0.978 deg
};
P[489]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  227.436  mm,    Y =   18.500  mm,    Z =   -313.830  mm,
    W =  -179.923 deg,    P =   0.183 deg,    R =   -0.980 deg
};
P[490]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  239.039  mm,    Y =   4.321  mm,    Z =   -313.288  mm,
    W =  -179.994 deg,    P =   0.202 deg,    R =   -0.979 deg
};
P[491]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  231.235  mm,    Y =   12.124  mm,    Z =   -313.288  mm,
    W =  -179.949 deg,    P =   0.190 deg,    R =   -0.980 deg
};
P[492]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  376.477  mm,    Y =   29.343  mm,    Z =   -314.499  mm,
    W =  -179.975 deg,    P =   0.030 deg,    R =   -0.999 deg
};
P[493]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  382.650  mm,    Y =   20.417  mm,    Z =   -314.402  mm,
    W =  -179.957 deg,    P =   0.052 deg,    R =   -0.998 deg
};
P[494]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  396.725  mm,    Y =   -45.221  mm,    Z =   -313.925  mm,
    W =  -179.933 deg,    P =   0.056 deg,    R =   -0.996 deg
};
P[495]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  358.554  mm,    Y =   -12.811  mm,    Z =   -314.169  mm,
    W =  -179.947 deg,    P =   0.094 deg,    R =   -0.994 deg
};
P[496]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  388.655  mm,    Y =   -47.513  mm,    Z =   -314.807  mm,
    W =  -179.928 deg,    P =   0.065 deg,    R =   -0.995 deg
};
P[497]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  375.345  mm,    Y =   -34.600  mm,    Z =   -314.747  mm,
    W =  -179.915 deg,    P =   0.089 deg,    R =   -0.992 deg
};
P[498]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  238.302  mm,    Y =   91.409  mm,    Z =   -313.949  mm,
    W =  -179.800 deg,    P =   0.040 deg,    R =   -0.979 deg
};
P[499]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  328.639  mm,    Y =   -12.187  mm,    Z =   -314.349  mm,
    W =  -179.996 deg,    P =   0.082 deg,    R =   -0.997 deg
};
P[500]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  432.740  mm,    Y =   -118.121  mm,    Z =   -314.813  mm,
    W =  -180.041 deg,    P =   0.041 deg,    R =   -0.998 deg
};
P[501]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  391.453  mm,    Y =   -104.081  mm,    Z =   -314.268  mm,
    W =  -179.943 deg,    P =   0.141 deg,    R =   -0.988 deg
};
P[502]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  228.566  mm,    Y =   58.367  mm,    Z =   -314.460  mm,
    W =  -179.841 deg,    P =   0.103 deg,    R =   -0.982 deg
};
P[503]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  382.991  mm,    Y =   -99.537  mm,    Z =   -314.844  mm,
    W =  -179.937 deg,    P =   0.151 deg,    R =   -0.987 deg
};
P[504]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  222.123  mm,    Y =   46.935  mm,    Z =   -314.197  mm,
    W =  -179.858 deg,    P =   0.130 deg,    R =   -0.981 deg
};
P[505]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  246.774  mm,    Y =   2.975  mm,    Z =   -313.986  mm,
    W =  -180.011 deg,    P =   0.206 deg,    R =   -0.978 deg
};
P[506]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  357.468  mm,    Y =   57.084  mm,    Z =   -315.180  mm,
    W =  -180.012 deg,    P =   -0.037 deg,    R =   -0.999 deg
};
P[507]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  291.877  mm,    Y =   117.845  mm,    Z =   -315.674  mm,
    W =  -179.818 deg,    P =   -0.120 deg,    R =   -0.976 deg
};
P[508]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  374.360  mm,    Y =   34.865  mm,    Z =   -315.201  mm,
    W =  -179.983 deg,    P =   0.016 deg,    R =   -1.000 deg
};
P[509]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  379.969  mm,    Y =   25.330  mm,    Z =   -315.262  mm,
    W =  -179.971 deg,    P =   0.041 deg,    R =   -0.999 deg
};
P[510]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  270.868  mm,    Y =   119.250  mm,    Z =   -315.871  mm,
    W =  -179.771 deg,    P =   -0.082 deg,    R =   -0.970 deg
};
P[511]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  254.443  mm,    Y =   113.263  mm,    Z =   -315.363  mm,
    W =  -179.751 deg,    P =   -0.043 deg,    R =   -0.968 deg
};
P[512]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  246.833  mm,    Y =   103.583  mm,    Z =   -315.913  mm,
    W =  -179.767 deg,    P =   -0.007 deg,    R =   -0.972 deg
};
P[513]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  343.416  mm,    Y =   -9.199  mm,    Z =   -315.676  mm,
    W =  -179.976 deg,    P =   0.086 deg,    R =   -0.996 deg
};
P[514]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  229.124  mm,    Y =   74.494  mm,    Z =   -315.508  mm,
    W =  -179.813 deg,    P =   0.083 deg,    R =   -0.979 deg
};
P[515]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  272.578  mm,    Y =   -1.035  mm,    Z =   -315.717  mm,
    W =  -180.029 deg,    P =   0.193 deg,    R =   -0.981 deg
};
P[516]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  220.209  mm,    Y =   52.047  mm,    Z =   -315.722  mm,
    W =  -179.837 deg,    P =   0.123 deg,    R =   -0.979 deg
};
P[517]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  220.954  mm,    Y =   35.756  mm,    Z =   -315.690  mm,
    W =  -179.868 deg,    P =   0.152 deg,    R =   -0.980 deg
};
P[518]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  255.038  mm,    Y =   -0.933  mm,    Z =   -315.262  mm,
    W =  -180.020 deg,    P =   0.213 deg,    R =   -0.977 deg
};
P[519]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  456.817  mm,    Y =   -14.152  mm,    Z =   -315.938  mm,
    W =  -179.936 deg,    P =   -0.153 deg,    R =   -0.986 deg
};
P[520]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  342.919  mm,    Y =   89.525  mm,    Z =   -316.664  mm,
    W =  -179.965 deg,    P =   -0.167 deg,    R =   -0.985 deg
};
P[521]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  475.460  mm,    Y =   -94.135  mm,    Z =   -316.161  mm,
    W =  -180.091 deg,    P =   -0.034 deg,    R =   -0.995 deg
};
P[522]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  261.106  mm,    Y =   117.386  mm,    Z =   -315.918  mm,
    W =  -179.743 deg,    P =   -0.058 deg,    R =   -0.965 deg
};
P[523]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  386.816  mm,    Y =   -32.861  mm,    Z =   -316.162  mm,
    W =  -179.918 deg,    P =   0.065 deg,    R =   -0.995 deg
};
P[524]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  239.431  mm,    Y =   98.027  mm,    Z =   -316.768  mm,
    W =  -179.768 deg,    P =   0.020 deg,    R =   -0.973 deg
};
P[525]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  222.619  mm,    Y =   65.748  mm,    Z =   -316.647  mm,
    W =  -179.817 deg,    P =   0.100 deg,    R =   -0.978 deg
};
P[526]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  320.327  mm,    Y =   -48.351  mm,    Z =   -316.713  mm,
    W =  -179.965 deg,    P =   0.142 deg,    R =   -0.989 deg
};
P[527]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  277.957  mm,    Y =   -5.492  mm,    Z =   -316.661  mm,
    W =  -180.032 deg,    P =   0.193 deg,    R =   -0.981 deg
};
P[528]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  261.939  mm,    Y =   -3.518  mm,    Z =   -316.834  mm,
    W =  -180.030 deg,    P =   0.223 deg,    R =   -0.974 deg
};
P[529]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  338.933  mm,    Y =   96.295  mm,    Z =   -317.316  mm,
    W =  -179.954 deg,    P =   -0.177 deg,    R =   -0.983 deg
};
P[530]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  318.677  mm,    Y =   108.798  mm,    Z =   -317.116  mm,
    W =  -179.876 deg,    P =   -0.161 deg,    R =   -0.979 deg
};
P[531]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  395.395  mm,    Y =   14.486  mm,    Z =   -317.503  mm,
    W =  -179.936 deg,    P =   0.025 deg,    R =   -0.998 deg
};
P[532]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  380.597  mm,    Y =   28.217  mm,    Z =   -317.338  mm,
    W =  -179.972 deg,    P =   0.027 deg,    R =   -0.999 deg
};
P[533]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  277.319  mm,    Y =   121.756  mm,    Z =   -317.208  mm,
    W =  -179.772 deg,    P =   -0.092 deg,    R =   -0.969 deg
};
P[534]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  247.643  mm,    Y =   109.189  mm,    Z =   -317.222  mm,
    W =  -179.752 deg,    P =   -0.023 deg,    R =   -0.969 deg
};
P[535]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  383.508  mm,    Y =   -41.662  mm,    Z =   -317.196  mm,
    W =  -179.919 deg,    P =   0.077 deg,    R =   -0.994 deg
};
P[536]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  367.779  mm,    Y =   -28.740  mm,    Z =   -317.317  mm,
    W =  -179.923 deg,    P =   0.100 deg,    R =   -0.992 deg
};
P[537]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  332.453  mm,    Y =   2.520  mm,    Z =   -317.190  mm,
    W =  -180.001 deg,    P =   0.068 deg,    R =   -0.998 deg
};
P[538]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  231.106  mm,    Y =   87.279  mm,    Z =   -316.918  mm,
    W =  -179.790 deg,    P =   0.070 deg,    R =   -0.975 deg
};
P[539]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  224.095  mm,    Y =   72.046  mm,    Z =   -317.227  mm,
    W =  -179.810 deg,    P =   0.094 deg,    R =   -0.977 deg
};
P[540]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  215.183  mm,    Y =   58.739  mm,    Z =   -317.756  mm,
    W =  -179.817 deg,    P =   0.122 deg,    R =   -0.975 deg
};
P[541]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  314.255  mm,    Y =   -40.892  mm,    Z =   -317.634  mm,
    W =  -179.989 deg,    P =   0.134 deg,    R =   -0.991 deg
};
P[542]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  327.188  mm,    Y =   -55.981  mm,    Z =   -317.802  mm,
    W =  -179.944 deg,    P =   0.156 deg,    R =   -0.986 deg
};
P[543]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  218.598  mm,    Y =   43.230  mm,    Z =   -317.346  mm,
    W =  -179.860 deg,    P =   0.137 deg,    R =   -0.981 deg
};
P[544]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  334.347  mm,    Y =   105.758  mm,    Z =   -318.597  mm,
    W =  -179.915 deg,    P =   -0.206 deg,    R =   -0.975 deg
};
P[545]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  353.542  mm,    Y =   78.508  mm,    Z =   -318.794  mm,
    W =  -180.010 deg,    P =   -0.147 deg,    R =   -0.989 deg
};
P[546]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  492.789  mm,    Y =   -65.394  mm,    Z =   -318.282  mm,
    W =  -180.135 deg,    P =   -0.108 deg,    R =   -0.985 deg
};
P[547]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  309.822  mm,    Y =   112.883  mm,    Z =   -318.154  mm,
    W =  -179.844 deg,    P =   -0.140 deg,    R =   -0.978 deg
};
P[548]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  339.138  mm,    Y =   -0.598  mm,    Z =   -318.894  mm,
    W =  -179.988 deg,    P =   0.078 deg,    R =   -0.997 deg
};
P[549]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  351.848  mm,    Y =   -14.846  mm,    Z =   -318.526  mm,
    W =  -179.955 deg,    P =   0.094 deg,    R =   -0.995 deg
};
P[550]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  354.199  mm,    Y =   -26.278  mm,    Z =   -318.871  mm,
    W =  -179.932 deg,    P =   0.110 deg,    R =   -0.992 deg
};
P[551]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349.725  mm,    Y =   -22.061  mm,    Z =   -318.826  mm,
    W =  -179.953 deg,    P =   0.104 deg,    R =   -0.993 deg
};
P[552]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  338.520  mm,    Y =   -11.286  mm,    Z =   -317.996  mm,
    W =  -179.982 deg,    P =   0.088 deg,    R =   -0.996 deg
};
P[553]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  422.236  mm,    Y =   -115.037  mm,    Z =   -318.056  mm,
    W =  -180.020 deg,    P =   0.067 deg,    R =   -0.998 deg
};
P[554]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  223.844  mm,    Y =   81.366  mm,    Z =   -318.586  mm,
    W =  -179.782 deg,    P =   0.079 deg,    R =   -0.973 deg
};
P[555]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  217.091  mm,    Y =   70.261  mm,    Z =   -318.678  mm,
    W =  -179.798 deg,    P =   0.113 deg,    R =   -0.973 deg
};
P[556]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  357.933  mm,    Y =   -81.223  mm,    Z =   -318.666  mm,
    W =  -179.904 deg,    P =   0.204 deg,    R =   -0.974 deg
};
P[557]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  293.388  mm,    Y =   -18.978  mm,    Z =   -318.667  mm,
    W =  -180.037 deg,    P =   0.150 deg,    R =   -0.988 deg
};
P[558]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  285.629  mm,    Y =   -11.981  mm,    Z =   -318.201  mm,
    W =  -180.036 deg,    P =   0.172 deg,    R =   -0.984 deg
};
P[559]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  334.430  mm,    Y =   -62.763  mm,    Z =   -318.406  mm,
    W =  -179.920 deg,    P =   0.172 deg,    R =   -0.982 deg
};
P[560]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  265.210  mm,    Y =   123.350  mm,    Z =   -319.855  mm,
    W =  -179.736 deg,    P =   -0.078 deg,    R =   -0.961 deg
};
P[561]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  240.249  mm,    Y =   106.416  mm,    Z =   -319.750  mm,
    W =  -179.740 deg,    P =   -0.003 deg,    R =   -0.966 deg
};
P[562]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  329.608  mm,    Y =   -1.276  mm,    Z =   -319.471  mm,
    W =  -180.003 deg,    P =   0.071 deg,    R =   -0.997 deg
};
P[563]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  231.350  mm,    Y =   93.340  mm,    Z =   -319.329  mm,
    W =  -179.762 deg,    P =   0.056 deg,    R =   -0.970 deg
};
P[564]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  428.820  mm,    Y =   -116.825  mm,    Z =   -319.198  mm,
    W =  -180.020 deg,    P =   0.040 deg,    R =   -0.999 deg
};
P[565]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  373.438  mm,    Y =   -93.753  mm,    Z =   -319.390  mm,
    W =  -179.915 deg,    P =   0.184 deg,    R =   -0.979 deg
};
P[566]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  365.888  mm,    Y =   -87.322  mm,    Z =   -318.963  mm,
    W =  -179.904 deg,    P =   0.197 deg,    R =   -0.976 deg
};
P[567]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  308.032  mm,    Y =   -32.935  mm,    Z =   -319.894  mm,
    W =  -180.010 deg,    P =   0.126 deg,    R =   -0.992 deg
};
P[568]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  342.563  mm,    Y =   -68.707  mm,    Z =   -319.578  mm,
    W =  -179.910 deg,    P =   0.186 deg,    R =   -0.978 deg
};
P[569]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  228.591  mm,    Y =   15.472  mm,    Z =   -319.366  mm,
    W =  -179.928 deg,    P =   0.186 deg,    R =   -0.980 deg
};
P[570]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  334.967  mm,    Y =   107.366  mm,    Z =   -320.591  mm,
    W =  -179.909 deg,    P =   -0.235 deg,    R =   -0.968 deg
};
P[571]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  357.948  mm,    Y =   72.065  mm,    Z =   -320.693  mm,
    W =  -180.018 deg,    P =   -0.124 deg,    R =   -0.992 deg
};
P[572]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  360.431  mm,    Y =   62.031  mm,    Z =   -320.021  mm,
    W =  -180.021 deg,    P =   -0.073 deg,    R =   -0.997 deg
};
P[573]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  408.771  mm,    Y =   12.814  mm,    Z =   -320.465  mm,
    W =  -179.916 deg,    P =   -0.023 deg,    R =   -0.996 deg
};
P[574]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  365.674  mm,    Y =   54.008  mm,    Z =   -319.966  mm,
    W =  -180.015 deg,    P =   -0.049 deg,    R =   -0.999 deg
};
P[575]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  272.199  mm,    Y =   125.253  mm,    Z =   -320.475  mm,
    W =  -179.741 deg,    P =   -0.094 deg,    R =   -0.961 deg
};
P[576]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  479.459  mm,    Y =   -93.472  mm,    Z =   -320.826  mm,
    W =  -180.093 deg,    P =   -0.039 deg,    R =   -0.995 deg
};
P[577]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  249.311  mm,    Y =   119.016  mm,    Z =   -319.958  mm,
    W =  -179.720 deg,    P =   -0.048 deg,    R =   -0.959 deg
};
P[578]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  359.322  mm,    Y =   -25.548  mm,    Z =   -320.540  mm,
    W =  -179.933 deg,    P =   0.105 deg,    R =   -0.992 deg
};
P[579]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  413.834  mm,    Y =   -111.976  mm,    Z =   -320.602  mm,
    W =  -179.999 deg,    P =   0.079 deg,    R =   -0.997 deg
};
P[580]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  216.919  mm,    Y =   76.019  mm,    Z =   -320.540  mm,
    W =  -179.777 deg,    P =   0.098 deg,    R =   -0.970 deg
};
P[581]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  380.741  mm,    Y =   -98.501  mm,    Z =   -320.191  mm,
    W =  -179.930 deg,    P =   0.163 deg,    R =   -0.984 deg
};
P[582]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350.322  mm,    Y =   -74.763  mm,    Z =   -319.942  mm,
    W =  -179.905 deg,    P =   0.201 deg,    R =   -0.975 deg
};
P[583]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  223.231  mm,    Y =   24.270  mm,    Z =   -320.650  mm,
    W =  -179.899 deg,    P =   0.170 deg,    R =   -0.980 deg
};
P[584]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  241.996  mm,    Y =   0.923  mm,    Z =   -320.543  mm,
    W =  -180.006 deg,    P =   0.200 deg,    R =   -0.980 deg
};
P[585]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  233.415  mm,    Y =   6.574  mm,    Z =   -320.572  mm,
    W =  -179.970 deg,    P =   0.202 deg,    R =   -0.979 deg
};
P[586]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  483.145  mm,    Y =   -23.134  mm,    Z =   -321.308  mm,
    W =  -180.022 deg,    P =   -0.207 deg,    R =   -0.978 deg
};
P[587]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  468.723  mm,    Y =   -15.140  mm,    Z =   -321.459  mm,
    W =  -179.965 deg,    P =   -0.187 deg,    R =   -0.982 deg
};
P[588]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  315.910  mm,    Y =   113.835  mm,    Z =   -321.076  mm,
    W =  -179.857 deg,    P =   -0.170 deg,    R =   -0.975 deg
};
P[589]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  496.028  mm,    Y =   -66.543  mm,    Z =   -321.460  mm,
    W =  -180.191 deg,    P =   -0.127 deg,    R =   -0.973 deg
};
P[590]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  304.770  mm,    Y =   120.032  mm,    Z =   -321.178  mm,
    W =  -179.828 deg,    P =   -0.158 deg,    R =   -0.972 deg
};
P[591]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  294.558  mm,    Y =   124.284  mm,    Z =   -321.431  mm,
    W =  -179.803 deg,    P =   -0.152 deg,    R =   -0.969 deg
};
P[592]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  379.343  mm,    Y =   38.743  mm,    Z =   -321.638  mm,
    W =  -179.983 deg,    P =   -0.004 deg,    R =   -1.000 deg
};
P[593]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  396.324  mm,    Y =   -39.454  mm,    Z =   -321.888  mm,
    W =  -179.929 deg,    P =   0.055 deg,    R =   -0.996 deg
};
P[594]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  242.203  mm,    Y =   113.977  mm,    Z =   -321.802  mm,
    W =  -179.716 deg,    P =   -0.017 deg,    R =   -0.959 deg
};
P[595]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  390.545  mm,    Y =   -35.031  mm,    Z =   -321.450  mm,
    W =  -179.921 deg,    P =   0.067 deg,    R =   -0.995 deg
};
P[596]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  369.051  mm,    Y =   -20.832  mm,    Z =   -321.433  mm,
    W =  -179.927 deg,    P =   0.087 deg,    R =   -0.994 deg
};
P[597]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  361.681  mm,    Y =   -13.462  mm,    Z =   -321.433  mm,
    W =  -179.942 deg,    P =   0.088 deg,    R =   -0.994 deg
};
P[598]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  234.875  mm,    Y =   103.946  mm,    Z =   -321.441  mm,
    W =  -179.727 deg,    P =   0.017 deg,    R =   -0.962 deg
};
P[599]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  334.013  mm,    Y =   -5.433  mm,    Z =   -321.455  mm,
    W =  -179.995 deg,    P =   0.080 deg,    R =   -0.997 deg
};
P[600]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  301.488  mm,    Y =   -25.148  mm,    Z =   -321.131  mm,
    W =  -180.026 deg,    P =   0.135 deg,    R =   -0.991 deg
};
P[601]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  219.824  mm,    Y =   30.744  mm,    Z =   -321.054  mm,
    W =  -179.884 deg,    P =   0.169 deg,    R =   -0.979 deg
};
P[602]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  475.417  mm,    Y =   -16.478  mm,    Z =   -322.844  mm,
    W =  -180.001 deg,    P =   -0.201 deg,    R =   -0.980 deg
};
P[603]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  342.315  mm,    Y =   100.177  mm,    Z =   -322.230  mm,
    W =  -179.943 deg,    P =   -0.221 deg,    R =   -0.974 deg
};
P[604]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  373.081  mm,    Y =   49.692  mm,    Z =   -322.849  mm,
    W =  -179.995 deg,    P =   -0.027 deg,    R =   -1.000 deg
};
P[605]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  400.453  mm,    Y =   17.650  mm,    Z =   -322.718  mm,
    W =  -179.933 deg,    P =   -0.009 deg,    R =   -0.998 deg
};
P[606]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  385.448  mm,    Y =   30.033  mm,    Z =   -322.051  mm,
    W =  -179.968 deg,    P =   0.012 deg,    R =   -0.999 deg
};
P[607]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  392.138  mm,    Y =   22.481  mm,    Z =   -322.064  mm,
    W =  -179.951 deg,    P =   0.010 deg,    R =   -0.999 deg
};
P[608]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  280.627  mm,    Y =   128.181  mm,    Z =   -322.435  mm,
    W =  -179.753 deg,    P =   -0.130 deg,    R =   -0.960 deg
};
P[609]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  366.289  mm,    Y =   -16.237  mm,    Z =   -322.065  mm,
    W =  -179.935 deg,    P =   0.090 deg,    R =   -0.994 deg
};
P[610]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  367.799  mm,    Y =   -22.925  mm,    Z =   -322.691  mm,
    W =  -179.927 deg,    P =   0.097 deg,    R =   -0.993 deg
};
P[611]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  218.910  mm,    Y =   87.096  mm,    Z =   -322.503  mm,
    W =  -179.744 deg,    P =   0.078 deg,    R =   -0.963 deg
};
P[612]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  408.938  mm,    Y =   -110.413  mm,    Z =   -322.450  mm,
    W =  -179.973 deg,    P =   0.099 deg,    R =   -0.995 deg
};
P[613]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  211.262  mm,    Y =   66.016  mm,    Z =   -321.935  mm,
    W =  -179.794 deg,    P =   0.120 deg,    R =   -0.971 deg
};
P[614]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  215.019  mm,    Y =   45.314  mm,    Z =   -322.496  mm,
    W =  -179.835 deg,    P =   0.142 deg,    R =   -0.976 deg
};
P[615]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  265.957  mm,    Y =   -6.201  mm,    Z =   -321.954  mm,
    W =  -180.032 deg,    P =   0.225 deg,    R =   -0.974 deg
};
P[616]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  217.494  mm,    Y =   37.755  mm,    Z =   -322.126  mm,
    W =  -179.865 deg,    P =   0.155 deg,    R =   -0.979 deg
};
P[617]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  256.293  mm,    Y =   -7.963  mm,    Z =   -322.746  mm,
    W =  -180.037 deg,    P =   0.228 deg,    R =   -0.973 deg
};
P[618]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  251.341  mm,    Y =   -4.008  mm,    Z =   -322.440  mm,
    W =  -180.022 deg,    P =   0.213 deg,    R =   -0.977 deg
};
P[619]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  460.906  mm,    Y =   -8.229  mm,    Z =   -322.933  mm,
    W =  -179.929 deg,    P =   -0.177 deg,    R =   -0.982 deg
};
P[620]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349.503  mm,    Y =   93.684  mm,    Z =   -323.856  mm,
    W =  -179.977 deg,    P =   -0.215 deg,    R =   -0.976 deg
};
P[621]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  324.778  mm,    Y =   114.918  mm,    Z =   -323.847  mm,
    W =  -179.860 deg,    P =   -0.204 deg,    R =   -0.969 deg
};
P[622]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  305.944  mm,    Y =   123.329  mm,    Z =   -323.802  mm,
    W =  -179.824 deg,    P =   -0.179 deg,    R =   -0.968 deg
};
P[623]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  481.724  mm,    Y =   -95.376  mm,    Z =   -323.805  mm,
    W =  -180.135 deg,    P =   -0.056 deg,    R =   -0.989 deg
};
P[624]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  257.698  mm,    Y =   128.251  mm,    Z =   -323.856  mm,
    W =  -179.706 deg,    P =   -0.079 deg,    R =   -0.953 deg
};
P[625]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  250.539  mm,    Y =   125.055  mm,    Z =   -323.030  mm,
    W =  -179.704 deg,    P =   -0.065 deg,    R =   -0.953 deg
};
P[626]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  226.884  mm,    Y =   98.338  mm,    Z =   -323.817  mm,
    W =  -179.721 deg,    P =   0.046 deg,    R =   -0.959 deg
};
P[627]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  402.347  mm,    Y =   -108.073  mm,    Z =   -323.241  mm,
    W =  -179.957 deg,    P =   0.121 deg,    R =   -0.992 deg
};
P[628]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  497.855  mm,    Y =   -58.641  mm,    Z =   -324.031  mm,
    W =  -180.216 deg,    P =   -0.165 deg,    R =   -0.962 deg
};
P[629]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  364.548  mm,    Y =   64.004  mm,    Z =   -324.829  mm,
    W =  -180.026 deg,    P =   -0.101 deg,    R =   -0.995 deg
};
P[630]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  286.249  mm,    Y =   129.830  mm,    Z =   -324.232  mm,
    W =  -179.755 deg,    P =   -0.145 deg,    R =   -0.959 deg
};
P[631]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  358.500  mm,    Y =   -14.114  mm,    Z =   -324.535  mm,
    W =  -179.947 deg,    P =   0.095 deg,    R =   -0.994 deg
};
P[632]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  233.725  mm,    Y =   109.512  mm,    Z =   -324.193  mm,
    W =  -179.695 deg,    P =   0.007 deg,    R =   -0.952 deg
};
P[633]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  337.818  mm,    Y =   -0.891  mm,    Z =   -324.546  mm,
    W =  -179.992 deg,    P =   0.076 deg,    R =   -0.997 deg
};
P[634]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  393.094  mm,    Y =   -103.717  mm,    Z =   -323.980  mm,
    W =  -179.943 deg,    P =   0.138 deg,    R =   -0.989 deg
};
P[635]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  273.553  mm,    Y =   -8.254  mm,    Z =   -324.774  mm,
    W =  -180.038 deg,    P =   0.211 deg,    R =   -0.977 deg
};
P[636]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  211.193  mm,    Y =   53.280  mm,    Z =   -324.565  mm,
    W =  -179.815 deg,    P =   0.139 deg,    R =   -0.973 deg
};
P[637]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  308.979  mm,    Y =   -45.663  mm,    Z =   -324.474  mm,
    W =  -179.997 deg,    P =   0.153 deg,    R =   -0.988 deg
};
P[638]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  496.694  mm,    Y =   -46.581  mm,    Z =   -325.030  mm,
    W =  -180.190 deg,    P =   -0.200 deg,    R =   -0.961 deg
};
P[639]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  499.067  mm,    Y =   -50.934  mm,    Z =   -325.774  mm,
    W =  -180.214 deg,    P =   -0.216 deg,    R =   -0.952 deg
};
P[640]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  343.627  mm,    Y =   104.053  mm,    Z =   -325.375  mm,
    W =  -179.930 deg,    P =   -0.263 deg,    R =   -0.962 deg
};
P[641]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  332.826  mm,    Y =   114.408  mm,    Z =   -324.977  mm,
    W =  -179.888 deg,    P =   -0.248 deg,    R =   -0.962 deg
};
P[642]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  360.183  mm,    Y =   77.496  mm,    Z =   -325.172  mm,
    W =  -180.024 deg,    P =   -0.172 deg,    R =   -0.985 deg
};
P[643]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  266.816  mm,    Y =   130.140  mm,    Z =   -325.192  mm,
    W =  -179.712 deg,    P =   -0.096 deg,    R =   -0.953 deg
};
P[644]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  228.673  mm,    Y =   105.774  mm,    Z =   -325.476  mm,
    W =  -179.695 deg,    P =   0.028 deg,    R =   -0.952 deg
};
P[645]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  444.161  mm,    Y =   -118.362  mm,    Z =   -324.956  mm,
    W =  -180.045 deg,    P =   0.031 deg,    R =   -0.998 deg
};
P[646]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  218.486  mm,    Y =   92.821  mm,    Z =   -325.512  mm,
    W =  -179.710 deg,    P =   0.060 deg,    R =   -0.955 deg
};
P[647]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  333.300  mm,    Y =   -63.110  mm,    Z =   -325.476  mm,
    W =  -179.922 deg,    P =   0.180 deg,    R =   -0.981 deg
};
P[648]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  284.612  mm,    Y =   -15.316  mm,    Z =   -325.509  mm,
    W =  -180.044 deg,    P =   0.187 deg,    R =   -0.981 deg
};
P[649]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  208.729  mm,    Y =   60.859  mm,    Z =   -325.700  mm,
    W =  -179.792 deg,    P =   0.135 deg,    R =   -0.969 deg
};
P[650]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  324.774  mm,    Y =   -56.720  mm,    Z =   -325.071  mm,
    W =  -179.947 deg,    P =   0.171 deg,    R =   -0.984 deg
};
P[651]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  317.432  mm,    Y =   -51.345  mm,    Z =   -325.093  mm,
    W =  -179.966 deg,    P =   0.157 deg,    R =   -0.987 deg
};
P[652]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  0.000  mm,    Y =   0.000  mm,    Z =   -225.827  mm,
    W =  0.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
/END
