/PROG  B0001.LS
/ATTR
OWNER       = MNEDITOR;
COMMENT     = "";
PROG_SIZE   = 636;
CREATE      = DATE 23-01-07  TIME 11:59:14;
MODIFIED    = DATE 23-01-07  TIME 12:02:18;
FILE_NAME   = ;
VERSION     = 0;
LINE_COUNT  = 4;
MEMORY_SIZE = 992;
PROTECT     = READ_WRITE;
TCD:  STACK_SIZE    = 0,
      TASK_PRIORITY = 50,
      TIME_SLICE    = 0,
      BUSY_LAMP_OFF = 0,
      ABORT_REQUEST = 0,
      PAUSE_REQUEST = 0;
DEFAULT_GROUP    = 1,*,*,*,*;
CONTROL_CODE     = 00000000 00000000;
/MN
   1:J P[1] 100% FINE    ;
   2:L P[2] 100mm/sec CNT100    ;
   3:L P[3] 100mm/sec CNT100    ;
   4:L P[4] 100mm/sec CNT100    ;
   5:L P[5] 100mm/sec CNT100    ;
   6:L P[6] 100mm/sec CNT100    ;
   7:L P[7] 100mm/sec CNT100    ;
   8:L P[8] 100mm/sec CNT100    ;
   9:L P[9] 100mm/sec CNT100    ;
   10:L P[10] 100mm/sec CNT100    ;
   11:L P[11] 100mm/sec CNT100    ;
   12:L P[12] 100mm/sec CNT100    ;
   13:L P[13] 100mm/sec CNT100    ;
   14:L P[14] 100mm/sec CNT100    ;
   15:L P[15] 100mm/sec CNT100    ;
   16:L P[16] 100mm/sec CNT100    ;
   17:L P[17] 100mm/sec CNT100    ;
   18:L P[18] 100mm/sec CNT100    ;
   19:L P[19] 100mm/sec CNT100    ;
   20:L P[20] 100mm/sec CNT100    ;
   21:L P[21] 100mm/sec CNT100    ;
   22:L P[22] 100mm/sec CNT100    ;
   23:L P[23] 100mm/sec CNT100    ;
   24:L P[24] 100mm/sec CNT100    ;
   25:L P[25] 100mm/sec CNT100    ;
   26:L P[26] 100mm/sec CNT100    ;
   27:L P[27] 100mm/sec CNT100    ;
   28:L P[28] 100mm/sec CNT100    ;
   29:L P[29] 100mm/sec CNT100    ;
   30:L P[30] 100mm/sec CNT100    ;
   31:L P[31] 100mm/sec CNT100    ;
   32:L P[32] 100mm/sec CNT100    ;
   33:L P[33] 100mm/sec CNT100    ;
   34:L P[34] 100mm/sec CNT100    ;
   35:L P[35] 100mm/sec CNT100    ;
   36:L P[36] 100mm/sec CNT100    ;
   37:L P[37] 100mm/sec CNT100    ;
   38:L P[38] 100mm/sec CNT100    ;
   39:L P[39] 100mm/sec CNT100    ;
   40:L P[40] 100mm/sec CNT100    ;
   41:L P[41] 100mm/sec CNT100    ;
   42:L P[42] 100mm/sec CNT100    ;
   43:L P[43] 100mm/sec CNT100    ;
   44:L P[44] 100mm/sec CNT100    ;
   45:L P[45] 100mm/sec CNT100    ;
   46:L P[46] 100mm/sec CNT100    ;
   47:L P[47] 100mm/sec CNT100    ;
   48:L P[48] 100mm/sec CNT100    ;
   49:L P[49] 100mm/sec CNT100    ;
   50:L P[50] 100mm/sec CNT100    ;
   51:L P[51] 100mm/sec CNT100    ;
   52:L P[52] 100mm/sec CNT100    ;
   53:L P[53] 100mm/sec CNT100    ;
   54:L P[54] 100mm/sec CNT100    ;
   55:L P[55] 100mm/sec CNT100    ;
   56:L P[56] 100mm/sec CNT100    ;
   57:L P[57] 100mm/sec CNT100    ;
   58:L P[58] 100mm/sec CNT100    ;
   59:L P[59] 100mm/sec CNT100    ;
   60:L P[60] 100mm/sec CNT100    ;
   61:L P[61] 100mm/sec CNT100    ;
   62:L P[62] 100mm/sec CNT100    ;
   63:L P[63] 100mm/sec CNT100    ;
   64:L P[64] 100mm/sec CNT100    ;
   65:L P[65] 100mm/sec CNT100    ;
   66:L P[66] 100mm/sec CNT100    ;
   67:L P[67] 100mm/sec CNT100    ;
   68:L P[68] 100mm/sec CNT100    ;
   69:L P[69] 100mm/sec CNT100    ;
   70:L P[70] 100mm/sec CNT100    ;
   71:L P[71] 100mm/sec CNT100    ;
   72:L P[72] 100mm/sec CNT100    ;
   73:L P[73] 100mm/sec CNT100    ;
   74:L P[74] 100mm/sec CNT100    ;
   75:L P[75] 100mm/sec CNT100    ;
   76:L P[76] 100mm/sec CNT100    ;
   77:L P[77] 100mm/sec CNT100    ;
   78:L P[78] 100mm/sec CNT100    ;
   79:L P[79] 100mm/sec CNT100    ;
   80:L P[80] 100mm/sec CNT100    ;
   81:L P[81] 100mm/sec CNT100    ;
   82:L P[82] 100mm/sec CNT100    ;
   83:L P[83] 100mm/sec CNT100    ;
   84:L P[84] 100mm/sec CNT100    ;
   85:L P[85] 100mm/sec CNT100    ;
   86:L P[86] 100mm/sec CNT100    ;
   87:L P[87] 100mm/sec CNT100    ;
   88:L P[88] 100mm/sec CNT100    ;
   89:L P[89] 100mm/sec CNT100    ;
   90:L P[90] 100mm/sec CNT100    ;
   91:L P[91] 100mm/sec CNT100    ;
   92:L P[92] 100mm/sec CNT100    ;
   93:L P[93] 100mm/sec CNT100    ;
   94:L P[94] 100mm/sec CNT100    ;
   95:L P[95] 100mm/sec CNT100    ;
   96:L P[96] 100mm/sec CNT100    ;
   97:L P[97] 100mm/sec CNT100    ;
   98:L P[98] 100mm/sec CNT100    ;
   99:L P[99] 100mm/sec CNT100    ;
   100:L P[100] 100mm/sec CNT100    ;
   101:L P[101] 100mm/sec CNT100    ;
   102:L P[102] 100mm/sec CNT100    ;
   103:L P[103] 100mm/sec CNT100    ;
   104:L P[104] 100mm/sec CNT100    ;
   105:L P[105] 100mm/sec CNT100    ;
   106:L P[106] 100mm/sec CNT100    ;
   107:L P[107] 100mm/sec CNT100    ;
   108:L P[108] 100mm/sec CNT100    ;
   109:L P[109] 100mm/sec CNT100    ;
   110:L P[110] 100mm/sec CNT100    ;
   111:L P[111] 100mm/sec CNT100    ;
   112:L P[112] 100mm/sec CNT100    ;
   113:L P[113] 100mm/sec CNT100    ;
   114:L P[114] 100mm/sec CNT100    ;
   115:L P[115] 100mm/sec CNT100    ;
   116:L P[116] 100mm/sec CNT100    ;
   117:L P[117] 100mm/sec CNT100    ;
   118:L P[118] 100mm/sec CNT100    ;
   119:L P[119] 100mm/sec CNT100    ;
   120:L P[120] 100mm/sec CNT100    ;
   121:L P[121] 100mm/sec CNT100    ;
   122:L P[122] 100mm/sec CNT100    ;
   123:L P[123] 100mm/sec CNT100    ;
   124:L P[124] 100mm/sec CNT100    ;
   125:L P[125] 100mm/sec CNT100    ;
   126:L P[126] 100mm/sec CNT100    ;
   127:L P[127] 100mm/sec CNT100    ;
   128:L P[128] 100mm/sec CNT100    ;
   129:L P[129] 100mm/sec CNT100    ;
   130:L P[130] 100mm/sec CNT100    ;
   131:L P[131] 100mm/sec CNT100    ;
   132:L P[132] 100mm/sec CNT100    ;
   133:L P[133] 100mm/sec CNT100    ;
   134:L P[134] 100mm/sec CNT100    ;
   135:L P[135] 100mm/sec CNT100    ;
   136:L P[136] 100mm/sec CNT100    ;
   137:L P[137] 100mm/sec CNT100    ;
   138:L P[138] 100mm/sec CNT100    ;
   139:L P[139] 100mm/sec CNT100    ;
   140:L P[140] 100mm/sec CNT100    ;
   141:L P[141] 100mm/sec CNT100    ;
   142:L P[142] 100mm/sec CNT100    ;
   143:L P[143] 100mm/sec CNT100    ;
   144:L P[144] 100mm/sec CNT100    ;
   145:L P[145] 100mm/sec CNT100    ;
   146:L P[146] 100mm/sec CNT100    ;
   147:L P[147] 100mm/sec CNT100    ;
   148:L P[148] 100mm/sec CNT100    ;
   149:L P[149] 100mm/sec CNT100    ;
   150:L P[150] 100mm/sec CNT100    ;
   151:L P[151] 100mm/sec CNT100    ;
   152:L P[152] 100mm/sec CNT100    ;
   153:L P[153] 100mm/sec CNT100    ;
   154:L P[154] 100mm/sec CNT100    ;
   155:L P[155] 100mm/sec CNT100    ;
   156:L P[156] 100mm/sec CNT100    ;
   157:L P[157] 100mm/sec CNT100    ;
   158:L P[158] 100mm/sec CNT100    ;
   159:L P[159] 100mm/sec CNT100    ;
   160:L P[160] 100mm/sec CNT100    ;
   161:L P[161] 100mm/sec CNT100    ;
   162:L P[162] 100mm/sec CNT100    ;
   163:L P[163] 100mm/sec CNT100    ;
   164:L P[164] 100mm/sec CNT100    ;
   165:L P[165] 100mm/sec CNT100    ;
   166:L P[166] 100mm/sec CNT100    ;
   167:L P[167] 100mm/sec CNT100    ;
   168:L P[168] 100mm/sec CNT100    ;
   169:L P[169] 100mm/sec CNT100    ;
   170:L P[170] 100mm/sec CNT100    ;
   171:L P[171] 100mm/sec CNT100    ;
   172:L P[172] 100mm/sec CNT100    ;
   173:L P[173] 100mm/sec CNT100    ;
   174:L P[174] 100mm/sec CNT100    ;
   175:L P[175] 100mm/sec CNT100    ;
   176:L P[176] 100mm/sec CNT100    ;
   177:L P[177] 100mm/sec CNT100    ;
   178:L P[178] 100mm/sec CNT100    ;
   179:L P[179] 100mm/sec CNT100    ;
   180:L P[180] 100mm/sec CNT100    ;
   181:L P[181] 100mm/sec CNT100    ;
   182:L P[182] 100mm/sec CNT100    ;
   183:L P[183] 100mm/sec CNT100    ;
   184:L P[184] 100mm/sec CNT100    ;
   185:L P[185] 100mm/sec CNT100    ;
   186:L P[186] 100mm/sec CNT100    ;
   187:L P[187] 100mm/sec CNT100    ;
   188:L P[188] 100mm/sec CNT100    ;
   189:L P[189] 100mm/sec CNT100    ;
   190:L P[190] 100mm/sec CNT100    ;
   191:L P[191] 100mm/sec CNT100    ;
   192:L P[192] 100mm/sec CNT100    ;
   193:L P[193] 100mm/sec CNT100    ;
   194:L P[194] 100mm/sec CNT100    ;
   195:L P[195] 100mm/sec CNT100    ;
   196:L P[196] 100mm/sec CNT100    ;
   197:L P[197] 100mm/sec CNT100    ;
   198:L P[198] 100mm/sec CNT100    ;
   199:L P[199] 100mm/sec CNT100    ;
   200:L P[200] 100mm/sec CNT100    ;
   201:L P[201] 100mm/sec CNT100    ;
   202:L P[202] 100mm/sec CNT100    ;
   203:L P[203] 100mm/sec CNT100    ;
   204:L P[204] 100mm/sec CNT100    ;
   205:L P[205] 100mm/sec CNT100    ;
   206:L P[206] 100mm/sec CNT100    ;
   207:L P[207] 100mm/sec CNT100    ;
   208:L P[208] 100mm/sec CNT100    ;
   209:L P[209] 100mm/sec CNT100    ;
   210:L P[210] 100mm/sec CNT100    ;
   211:L P[211] 100mm/sec CNT100    ;
   212:L P[212] 100mm/sec CNT100    ;
   213:L P[213] 100mm/sec CNT100    ;
   214:L P[214] 100mm/sec CNT100    ;
   215:L P[215] 100mm/sec CNT100    ;
   216:L P[216] 100mm/sec CNT100    ;
   217:L P[217] 100mm/sec CNT100    ;
   218:L P[218] 100mm/sec CNT100    ;
   219:L P[219] 100mm/sec CNT100    ;
   220:L P[220] 100mm/sec CNT100    ;
   221:L P[221] 100mm/sec CNT100    ;
   222:L P[222] 100mm/sec CNT100    ;
   223:L P[223] 100mm/sec CNT100    ;
   224:L P[224] 100mm/sec CNT100    ;
   225:L P[225] 100mm/sec CNT100    ;
   226:L P[226] 100mm/sec CNT100    ;
   227:L P[227] 100mm/sec CNT100    ;
   228:L P[228] 100mm/sec CNT100    ;
   229:L P[229] 100mm/sec CNT100    ;
   230:L P[230] 100mm/sec CNT100    ;
   231:L P[231] 100mm/sec CNT100    ;
   232:L P[232] 100mm/sec CNT100    ;
   233:L P[233] 100mm/sec CNT100    ;
   234:L P[234] 100mm/sec CNT100    ;
   235:L P[235] 100mm/sec CNT100    ;
   236:L P[236] 100mm/sec CNT100    ;
   237:L P[237] 100mm/sec CNT100    ;
   238:L P[238] 100mm/sec CNT100    ;
   239:L P[239] 100mm/sec CNT100    ;
   240:L P[240] 100mm/sec CNT100    ;
   241:L P[241] 100mm/sec CNT100    ;
   242:L P[242] 100mm/sec CNT100    ;
   243:L P[243] 100mm/sec CNT100    ;
   244:L P[244] 100mm/sec CNT100    ;
   245:L P[245] 100mm/sec CNT100    ;
   246:L P[246] 100mm/sec CNT100    ;
   247:L P[247] 100mm/sec CNT100    ;
   248:L P[248] 100mm/sec CNT100    ;
   249:L P[249] 100mm/sec CNT100    ;
   250:L P[250] 100mm/sec CNT100    ;
   251:L P[251] 100mm/sec CNT100    ;
   252:L P[252] 100mm/sec CNT100    ;
   253:L P[253] 100mm/sec CNT100    ;
   254:L P[254] 100mm/sec CNT100    ;
   255:L P[255] 100mm/sec CNT100    ;
   256:L P[256] 100mm/sec CNT100    ;
   257:L P[257] 100mm/sec CNT100    ;
   258:L P[258] 100mm/sec CNT100    ;
   259:L P[259] 100mm/sec CNT100    ;
   260:L P[260] 100mm/sec CNT100    ;
   261:L P[261] 100mm/sec CNT100    ;
   262:L P[262] 100mm/sec CNT100    ;
   263:L P[263] 100mm/sec CNT100    ;
   264:L P[264] 100mm/sec CNT100    ;
   265:L P[265] 100mm/sec CNT100    ;
   266:L P[266] 100mm/sec CNT100    ;
   267:L P[267] 100mm/sec CNT100    ;
   268:L P[268] 100mm/sec CNT100    ;
   269:L P[269] 100mm/sec CNT100    ;
   270:L P[270] 100mm/sec CNT100    ;
   271:L P[271] 100mm/sec CNT100    ;
   272:L P[272] 100mm/sec CNT100    ;
   273:L P[273] 100mm/sec CNT100    ;
   274:L P[274] 100mm/sec CNT100    ;
   275:L P[275] 100mm/sec CNT100    ;
   276:L P[276] 100mm/sec CNT100    ;
   277:L P[277] 100mm/sec CNT100    ;
   278:L P[278] 100mm/sec CNT100    ;
   279:L P[279] 100mm/sec CNT100    ;
   280:L P[280] 100mm/sec CNT100    ;
   281:L P[281] 100mm/sec CNT100    ;
   282:L P[282] 100mm/sec CNT100    ;
   283:L P[283] 100mm/sec CNT100    ;
   284:L P[284] 100mm/sec CNT100    ;
   285:L P[285] 100mm/sec CNT100    ;
   286:L P[286] 100mm/sec CNT100    ;
   287:L P[287] 100mm/sec CNT100    ;
   288:L P[288] 100mm/sec CNT100    ;
   289:L P[289] 100mm/sec CNT100    ;
   290:L P[290] 100mm/sec CNT100    ;
   291:L P[291] 100mm/sec CNT100    ;
   292:L P[292] 100mm/sec CNT100    ;
   293:L P[293] 100mm/sec CNT100    ;
   294:L P[294] 100mm/sec CNT100    ;
   295:L P[295] 100mm/sec CNT100    ;
   296:L P[296] 100mm/sec CNT100    ;
   297:L P[297] 100mm/sec CNT100    ;
   298:L P[298] 100mm/sec CNT100    ;
   299:L P[299] 100mm/sec CNT100    ;
   300:L P[300] 100mm/sec CNT100    ;
   301:L P[301] 100mm/sec CNT100    ;
   302:L P[302] 100mm/sec CNT100    ;
   303:L P[303] 100mm/sec CNT100    ;
   304:L P[304] 100mm/sec CNT100    ;
   305:L P[305] 100mm/sec CNT100    ;
   306:L P[306] 100mm/sec CNT100    ;
   307:L P[307] 100mm/sec CNT100    ;
   308:L P[308] 100mm/sec CNT100    ;
   309:L P[309] 100mm/sec CNT100    ;
   310:L P[310] 100mm/sec CNT100    ;
   311:L P[311] 100mm/sec CNT100    ;
   312:L P[312] 100mm/sec CNT100    ;
   313:L P[313] 100mm/sec CNT100    ;
   314:L P[314] 100mm/sec CNT100    ;
   315:L P[315] 100mm/sec CNT100    ;
   316:L P[316] 100mm/sec CNT100    ;
   317:L P[317] 100mm/sec CNT100    ;
   318:L P[318] 100mm/sec CNT100    ;
   319:L P[319] 100mm/sec CNT100    ;
   320:L P[320] 100mm/sec CNT100    ;
   321:L P[321] 100mm/sec CNT100    ;
   322:L P[322] 100mm/sec CNT100    ;
   323:L P[323] 100mm/sec CNT100    ;
   324:L P[324] 100mm/sec CNT100    ;
   325:L P[325] 100mm/sec CNT100    ;
   326:L P[326] 100mm/sec CNT100    ;
   327:L P[327] 100mm/sec CNT100    ;
   328:L P[328] 100mm/sec CNT100    ;
   329:L P[329] 100mm/sec CNT100    ;
   330:L P[330] 100mm/sec CNT100    ;
   331:L P[331] 100mm/sec CNT100    ;
   332:L P[332] 100mm/sec CNT100    ;
   333:L P[333] 100mm/sec CNT100    ;
   334:L P[334] 100mm/sec CNT100    ;
   335:L P[335] 100mm/sec CNT100    ;
   336:L P[336] 100mm/sec CNT100    ;
   337:L P[337] 100mm/sec CNT100    ;
   338:L P[338] 100mm/sec CNT100    ;
   339:L P[339] 100mm/sec CNT100    ;
   340:L P[340] 100mm/sec CNT100    ;
   341:L P[341] 100mm/sec CNT100    ;
   342:L P[342] 100mm/sec CNT100    ;
   343:L P[343] 100mm/sec CNT100    ;
   344:L P[344] 100mm/sec CNT100    ;
   345:L P[345] 100mm/sec CNT100    ;
   346:L P[346] 100mm/sec CNT100    ;
   347:L P[347] 100mm/sec CNT100    ;
   348:L P[348] 100mm/sec CNT100    ;
   349:L P[349] 100mm/sec CNT100    ;
   350:L P[350] 100mm/sec CNT100    ;
   351:L P[351] 100mm/sec CNT100    ;
   352:L P[352] 100mm/sec CNT100    ;
   353:L P[353] 100mm/sec CNT100    ;
   354:L P[354] 100mm/sec CNT100    ;
   355:L P[355] 100mm/sec CNT100    ;
   356:L P[356] 100mm/sec CNT100    ;
   357:L P[357] 100mm/sec CNT100    ;
   358:L P[358] 100mm/sec CNT100    ;
   359:L P[359] 100mm/sec CNT100    ;
   360:L P[360] 100mm/sec CNT100    ;
   361:L P[361] 100mm/sec CNT100    ;
   362:L P[362] 100mm/sec CNT100    ;
   363:L P[363] 100mm/sec CNT100    ;
   364:L P[364] 100mm/sec CNT100    ;
   365:L P[365] 100mm/sec CNT100    ;
   366:L P[366] 100mm/sec CNT100    ;
   367:L P[367] 100mm/sec CNT100    ;
   368:L P[368] 100mm/sec CNT100    ;
   369:L P[369] 100mm/sec CNT100    ;
   370:L P[370] 100mm/sec CNT100    ;
   371:L P[371] 100mm/sec CNT100    ;
   372:L P[372] 100mm/sec CNT100    ;
   373:L P[373] 100mm/sec CNT100    ;
   374:L P[374] 100mm/sec CNT100    ;
   375:L P[375] 100mm/sec CNT100    ;
   376:L P[376] 100mm/sec CNT100    ;
   377:L P[377] 100mm/sec CNT100    ;
   378:L P[378] 100mm/sec CNT100    ;
   379:L P[379] 100mm/sec CNT100    ;
   380:L P[380] 100mm/sec CNT100    ;
   381:L P[381] 100mm/sec CNT100    ;
   382:L P[382] 100mm/sec CNT100    ;
   383:L P[383] 100mm/sec CNT100    ;
   384:L P[384] 100mm/sec CNT100    ;
   385:L P[385] 100mm/sec CNT100    ;
   386:L P[386] 100mm/sec CNT100    ;
   387:L P[387] 100mm/sec CNT100    ;
   388:L P[388] 100mm/sec CNT100    ;
   389:L P[389] 100mm/sec CNT100    ;
   390:L P[390] 100mm/sec CNT100    ;
   391:L P[391] 100mm/sec CNT100    ;
   392:L P[392] 100mm/sec CNT100    ;
   393:L P[393] 100mm/sec CNT100    ;
   394:L P[394] 100mm/sec CNT100    ;
   395:L P[395] 100mm/sec CNT100    ;
   396:L P[396] 100mm/sec CNT100    ;
   397:L P[397] 100mm/sec CNT100    ;
   398:L P[398] 100mm/sec CNT100    ;
   399:L P[399] 100mm/sec CNT100    ;
   400:L P[400] 100mm/sec CNT100    ;
   401:L P[401] 100mm/sec CNT100    ;
   402:L P[402] 100mm/sec CNT100    ;
   403:L P[403] 100mm/sec CNT100    ;
   404:L P[404] 100mm/sec CNT100    ;
   405:L P[405] 100mm/sec CNT100    ;
   406:L P[406] 100mm/sec CNT100    ;
   407:L P[407] 100mm/sec CNT100    ;
   408:L P[408] 100mm/sec CNT100    ;
   409:L P[409] 100mm/sec CNT100    ;
   410:L P[410] 100mm/sec CNT100    ;
   411:L P[411] 100mm/sec CNT100    ;
   412:L P[412] 100mm/sec CNT100    ;
   413:L P[413] 100mm/sec CNT100    ;
   414:L P[414] 100mm/sec CNT100    ;
   415:L P[415] 100mm/sec CNT100    ;
   416:L P[416] 100mm/sec CNT100    ;
   417:L P[417] 100mm/sec CNT100    ;
   418:L P[418] 100mm/sec CNT100    ;
   419:L P[419] 100mm/sec CNT100    ;
   420:L P[420] 100mm/sec CNT100    ;
   421:L P[421] 100mm/sec CNT100    ;
   422:L P[422] 100mm/sec CNT100    ;
   423:L P[423] 100mm/sec CNT100    ;
   424:L P[424] 100mm/sec CNT100    ;
   425:L P[425] 100mm/sec CNT100    ;
   426:L P[426] 100mm/sec CNT100    ;
   427:L P[427] 100mm/sec CNT100    ;
   428:L P[428] 100mm/sec CNT100    ;
   429:L P[429] 100mm/sec CNT100    ;
   430:L P[430] 100mm/sec CNT100    ;
   431:L P[431] 100mm/sec CNT100    ;
   432:L P[432] 100mm/sec CNT100    ;
   433:L P[433] 100mm/sec CNT100    ;
   434:L P[434] 100mm/sec CNT100    ;
   435:L P[435] 100mm/sec CNT100    ;
   436:L P[436] 100mm/sec CNT100    ;
   437:L P[437] 100mm/sec CNT100    ;
   438:L P[438] 100mm/sec CNT100    ;
   439:L P[439] 100mm/sec CNT100    ;
   440:L P[440] 100mm/sec CNT100    ;
   441:L P[441] 100mm/sec CNT100    ;
   442:L P[442] 100mm/sec CNT100    ;
   443:L P[443] 100mm/sec CNT100    ;
   444:L P[444] 100mm/sec CNT100    ;
   445:L P[445] 100mm/sec CNT100    ;
   446:L P[446] 100mm/sec CNT100    ;
   447:L P[447] 100mm/sec CNT100    ;
   448:L P[448] 100mm/sec CNT100    ;
   449:L P[449] 100mm/sec CNT100    ;
   450:L P[450] 100mm/sec CNT100    ;
   451:L P[451] 100mm/sec CNT100    ;
   452:L P[452] 100mm/sec CNT100    ;
   453:L P[453] 100mm/sec CNT100    ;
   454:L P[454] 100mm/sec CNT100    ;
   455:L P[455] 100mm/sec CNT100    ;
   456:L P[456] 100mm/sec CNT100    ;
   457:L P[457] 100mm/sec CNT100    ;
   458:L P[458] 100mm/sec CNT100    ;
   459:L P[459] 100mm/sec CNT100    ;
   460:L P[460] 100mm/sec CNT100    ;
   461:L P[461] 100mm/sec CNT100    ;
   462:L P[462] 100mm/sec CNT100    ;
   463:L P[463] 100mm/sec CNT100    ;
   464:L P[464] 100mm/sec CNT100    ;
   465:L P[465] 100mm/sec CNT100    ;
   466:L P[466] 100mm/sec CNT100    ;
   467:L P[467] 100mm/sec CNT100    ;
   468:L P[468] 100mm/sec CNT100    ;
   469:L P[469] 100mm/sec CNT100    ;
   470:L P[470] 100mm/sec CNT100    ;
   471:L P[471] 100mm/sec CNT100    ;
   472:L P[472] 100mm/sec CNT100    ;
   473:L P[473] 100mm/sec CNT100    ;
   474:L P[474] 100mm/sec CNT100    ;
   475:L P[475] 100mm/sec CNT100    ;
   476:L P[476] 100mm/sec CNT100    ;
   477:L P[477] 100mm/sec CNT100    ;
   478:L P[478] 100mm/sec CNT100    ;
   479:L P[479] 100mm/sec CNT100    ;
   480:L P[480] 100mm/sec CNT100    ;
   481:L P[481] 100mm/sec CNT100    ;
   482:L P[482] 100mm/sec CNT100    ;
   483:L P[483] 100mm/sec CNT100    ;
   484:L P[484] 100mm/sec CNT100    ;
   485:L P[485] 100mm/sec CNT100    ;
   486:L P[486] 100mm/sec CNT100    ;
   487:L P[487] 100mm/sec CNT100    ;
   488:L P[488] 100mm/sec CNT100    ;
   489:L P[489] 100mm/sec CNT100    ;
   490:L P[490] 100mm/sec CNT100    ;
   491:L P[491] 100mm/sec CNT100    ;
   492:L P[492] 100mm/sec CNT100    ;
   493:L P[493] 100mm/sec CNT100    ;
   494:L P[494] 100mm/sec CNT100    ;
   495:L P[495] 100mm/sec CNT100    ;
   496:L P[496] 100mm/sec CNT100    ;
   497:L P[497] 100mm/sec CNT100    ;
   498:L P[498] 100mm/sec CNT100    ;
   499:L P[499] 100mm/sec CNT100    ;
   500:L P[500] 100mm/sec CNT100    ;
   501:L P[501] 100mm/sec CNT100    ;
   502:L P[502] 100mm/sec CNT100    ;
   503:L P[503] 100mm/sec CNT100    ;
   504:L P[504] 100mm/sec CNT100    ;
   505:L P[505] 100mm/sec CNT100    ;
   506:L P[506] 100mm/sec CNT100    ;
   507:L P[507] 100mm/sec CNT100    ;
   508:L P[508] 100mm/sec CNT100    ;
   509:L P[509] 100mm/sec CNT100    ;
   510:L P[510] 100mm/sec CNT100    ;
   511:L P[511] 100mm/sec CNT100    ;
   512:L P[512] 100mm/sec CNT100    ;
   513:L P[513] 100mm/sec CNT100    ;
   514:L P[514] 100mm/sec CNT100    ;
   515:L P[515] 100mm/sec CNT100    ;
   516:L P[516] 100mm/sec CNT100    ;
   517:L P[517] 100mm/sec CNT100    ;
   518:L P[518] 100mm/sec CNT100    ;
   519:L P[519] 100mm/sec CNT100    ;
   520:L P[520] 100mm/sec CNT100    ;
   521:L P[521] 100mm/sec CNT100    ;
   522:L P[522] 100mm/sec CNT100    ;
   523:L P[523] 100mm/sec CNT100    ;
   524:L P[524] 100mm/sec CNT100    ;
   525:L P[525] 100mm/sec CNT100    ;
   526:L P[526] 100mm/sec CNT100    ;
   527:L P[527] 100mm/sec CNT100    ;
   528:L P[528] 100mm/sec CNT100    ;
   529:L P[529] 100mm/sec CNT100    ;
   530:L P[530] 100mm/sec CNT100    ;
   531:L P[531] 100mm/sec CNT100    ;
   532:L P[532] 100mm/sec CNT100    ;
   533:L P[533] 100mm/sec CNT100    ;
   534:L P[534] 100mm/sec CNT100    ;
   535:L P[535] 100mm/sec CNT100    ;
   536:L P[536] 100mm/sec CNT100    ;
   537:L P[537] 100mm/sec CNT100    ;
   538:L P[538] 100mm/sec CNT100    ;
   539:L P[539] 100mm/sec CNT100    ;
   540:L P[540] 100mm/sec CNT100    ;
   541:L P[541] 100mm/sec CNT100    ;
   542:L P[542] 100mm/sec CNT100    ;
   543:L P[543] 100mm/sec CNT100    ;
   544:L P[544] 100mm/sec CNT100    ;
   545:L P[545] 100mm/sec CNT100    ;
   546:L P[546] 100mm/sec CNT100    ;
   547:L P[547] 100mm/sec CNT100    ;
   548:L P[548] 100mm/sec CNT100    ;
   549:L P[549] 100mm/sec CNT100    ;
   550:L P[550] 100mm/sec CNT100    ;
   551:L P[551] 100mm/sec CNT100    ;
   552:L P[552] 100mm/sec CNT100    ;
   553:L P[553] 100mm/sec CNT100    ;
   554:L P[554] 100mm/sec CNT100    ;
   555:L P[555] 100mm/sec CNT100    ;
   556:L P[556] 100mm/sec CNT100    ;
   557:L P[557] 100mm/sec CNT100    ;
   558:L P[558] 100mm/sec CNT100    ;
   559:L P[559] 100mm/sec CNT100    ;
   560:L P[560] 100mm/sec CNT100    ;
   561:L P[561] 100mm/sec CNT100    ;
   562:L P[562] 100mm/sec CNT100    ;
   563:L P[563] 100mm/sec CNT100    ;
   564:L P[564] 100mm/sec CNT100    ;
   565:L P[565] 100mm/sec CNT100    ;
   566:L P[566] 100mm/sec CNT100    ;
   567:L P[567] 100mm/sec CNT100    ;
   568:L P[568] 100mm/sec CNT100    ;
   569:L P[569] 100mm/sec CNT100    ;
   570:L P[570] 100mm/sec CNT100    ;
   571:L P[571] 100mm/sec CNT100    ;
   572:L P[572] 100mm/sec CNT100    ;
   573:L P[573] 100mm/sec CNT100    ;
   574:L P[574] 100mm/sec CNT100    ;
   575:L P[575] 100mm/sec CNT100    ;
   576:L P[576] 100mm/sec CNT100    ;
   577:L P[577] 100mm/sec CNT100    ;
   578:L P[578] 100mm/sec CNT100    ;
   579:L P[579] 100mm/sec CNT100    ;
   580:L P[580] 100mm/sec CNT100    ;
   581:L P[581] 100mm/sec CNT100    ;
   582:L P[582] 100mm/sec CNT100    ;
   583:L P[583] 100mm/sec CNT100    ;
   584:L P[584] 100mm/sec CNT100    ;
   585:L P[585] 100mm/sec CNT100    ;
   586:L P[586] 100mm/sec CNT100    ;
   587:L P[587] 100mm/sec CNT100    ;
   588:L P[588] 100mm/sec CNT100    ;
   589:L P[589] 100mm/sec CNT100    ;
   590:L P[590] 100mm/sec CNT100    ;
   591:L P[591] 100mm/sec CNT100    ;
   592:L P[592] 100mm/sec CNT100    ;
   593:L P[593] 100mm/sec CNT100    ;
   594:L P[594] 100mm/sec CNT100    ;
   595:L P[595] 100mm/sec CNT100    ;
   596:L P[596] 100mm/sec CNT100    ;
   597:L P[597] 100mm/sec CNT100    ;
   598:L P[598] 100mm/sec CNT100    ;
   599:L P[599] 100mm/sec CNT100    ;
   600:L P[600] 100mm/sec CNT100    ;
   601:L P[601] 100mm/sec CNT100    ;
   602:L P[602] 100mm/sec CNT100    ;
   603:L P[603] 100mm/sec CNT100    ;
   604:L P[604] 100mm/sec CNT100    ;
   605:L P[605] 100mm/sec CNT100    ;
   606:L P[606] 100mm/sec CNT100    ;
   607:L P[607] 100mm/sec CNT100    ;
   608:L P[608] 100mm/sec CNT100    ;
   609:L P[609] 100mm/sec CNT100    ;
   610:L P[610] 100mm/sec CNT100    ;
   611:L P[611] 100mm/sec CNT100    ;
   612:L P[612] 100mm/sec CNT100    ;
   613:L P[613] 100mm/sec CNT100    ;
   614:L P[614] 100mm/sec CNT100    ;
   615:L P[615] 100mm/sec CNT100    ;
   616:L P[616] 100mm/sec CNT100    ;
   617:L P[617] 100mm/sec CNT100    ;
   618:L P[618] 100mm/sec CNT100    ;
   619:L P[619] 100mm/sec CNT100    ;
   620:L P[620] 100mm/sec CNT100    ;
   621:L P[621] 100mm/sec CNT100    ;
   622:L P[622] 100mm/sec CNT100    ;
   623:L P[623] 100mm/sec CNT100    ;
   624:L P[624] 100mm/sec CNT100    ;
   625:L P[625] 100mm/sec CNT100    ;
   626:L P[626] 100mm/sec CNT100    ;
   627:L P[627] 100mm/sec CNT100    ;
   628:L P[628] 100mm/sec CNT100    ;
   629:L P[629] 100mm/sec CNT100    ;
   630:L P[630] 100mm/sec CNT100    ;
   631:L P[631] 100mm/sec CNT100    ;
   632:L P[632] 100mm/sec CNT100    ;
   633:L P[633] 100mm/sec CNT100    ;
   634:L P[634] 100mm/sec CNT100    ;
   635:L P[635] 100mm/sec CNT100    ;
   636:L P[636] 100mm/sec CNT100    ;
   637:L P[637] 100mm/sec CNT100    ;
   638:L P[638] 100mm/sec CNT100    ;
   639:L P[639] 100mm/sec CNT100    ;
   640:L P[640] 100mm/sec CNT100    ;
   641:L P[641] 100mm/sec CNT100    ;
   642:L P[642] 100mm/sec CNT100    ;
   643:L P[643] 100mm/sec CNT100    ;
   644:L P[644] 100mm/sec CNT100    ;
   645:L P[645] 100mm/sec CNT100    ;
   646:L P[646] 100mm/sec CNT100    ;
   647:L P[647] 100mm/sec CNT100    ;
   648:L P[648] 100mm/sec CNT100    ;
   649:L P[649] 100mm/sec CNT100    ;
   650:L P[650] 100mm/sec CNT100    ;
   651:L P[651] 100mm/sec CNT100    ;
   652:L P[652] 100mm/sec CNT100    ;
/POS
P[1]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  0.000  mm,    Y =   0.000  mm,    Z =   -225827.000  mm,
    W =  0.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
P[2]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350065.701  mm,    Y =   -23.336  mm,    Z =   -325786.626  mm,
    W =  -179.933 deg,    P =   0.015 deg,    R =   -0.998 deg
};
P[3]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350076.035  mm,    Y =   -22.839  mm,    Z =   -325787.666  mm,
    W =  -179.954 deg,    P =   -0.006 deg,    R =   -0.999 deg
};
P[4]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350057.412  mm,    Y =   -18.324  mm,    Z =   -325787.185  mm,
    W =  -179.912 deg,    P =   0.043 deg,    R =   -0.995 deg
};
P[5]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350048.850  mm,    Y =   -11.447  mm,    Z =   -325787.575  mm,
    W =  -179.912 deg,    P =   0.047 deg,    R =   -0.995 deg
};
P[6]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350053.205  mm,    Y =   -22.723  mm,    Z =   -325787.494  mm,
    W =  -179.918 deg,    P =   0.055 deg,    R =   -0.995 deg
};
P[7]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350046.245  mm,    Y =   -14.974  mm,    Z =   -325787.528  mm,
    W =  -179.912 deg,    P =   0.049 deg,    R =   -0.995 deg
};
P[8]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350060.171  mm,    Y =   -30.920  mm,    Z =   -325787.697  mm,
    W =  -179.942 deg,    P =   0.022 deg,    R =   -0.998 deg
};
P[9]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350055.915  mm,    Y =   -31.962  mm,    Z =   -325787.548  mm,
    W =  -179.930 deg,    P =   0.046 deg,    R =   -0.997 deg
};
P[10]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350049.576  mm,    Y =   -26.158  mm,    Z =   -325787.712  mm,
    W =  -179.919 deg,    P =   0.057 deg,    R =   -0.995 deg
};
P[11]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350042.866  mm,    Y =   -18.788  mm,    Z =   -325787.327  mm,
    W =  -179.916 deg,    P =   0.059 deg,    R =   -0.995 deg
};
P[12]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350037.398  mm,    Y =   -15.093  mm,    Z =   -325788.634  mm,
    W =  -179.916 deg,    P =   0.066 deg,    R =   -0.994 deg
};
P[13]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350059.495  mm,    Y =   -99.354  mm,    Z =   -325789.041  mm,
    W =  -179.979 deg,    P =   0.097 deg,    R =   -0.995 deg
};
P[14]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350101.580  mm,    Y =   -58.839  mm,    Z =   -325790.012  mm,
    W =  -180.001 deg,    P =   -0.017 deg,    R =   -1.000 deg
};
P[15]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350072.480  mm,    Y =   -29.022  mm,    Z =   -325789.625  mm,
    W =  -179.951 deg,    P =   0.007 deg,    R =   -0.999 deg
};
P[16]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350093.727  mm,    Y =   -65.671  mm,    Z =   -325789.339  mm,
    W =  -179.995 deg,    P =   -0.002 deg,    R =   -1.000 deg
};
P[17]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350044.615  mm,    Y =   -30.992  mm,    Z =   -325789.819  mm,
    W =  -179.921 deg,    P =   0.065 deg,    R =   -0.995 deg
};
P[18]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350064.368  mm,    Y =   -96.278  mm,    Z =   -325789.128  mm,
    W =  -179.982 deg,    P =   0.081 deg,    R =   -0.997 deg
};
P[19]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350055.239  mm,    Y =   -95.006  mm,    Z =   -325789.179  mm,
    W =  -179.957 deg,    P =   0.099 deg,    R =   -0.994 deg
};
P[20]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350054.422  mm,    Y =   -105.119  mm,    Z =   -325789.734  mm,
    W =  -179.973 deg,    P =   0.122 deg,    R =   -0.992 deg
};
P[21]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350101.958  mm,    Y =   -43.582  mm,    Z =   -325790.787  mm,
    W =  -179.989 deg,    P =   -0.028 deg,    R =   -1.000 deg
};
P[22]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350108.693  mm,    Y =   -51.027  mm,    Z =   -325790.856  mm,
    W =  -180.014 deg,    P =   -0.028 deg,    R =   -0.999 deg
};
P[23]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350108.401  mm,    Y =   -65.467  mm,    Z =   -325790.191  mm,
    W =  -180.037 deg,    P =   -0.010 deg,    R =   -0.999 deg
};
P[24]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350094.930  mm,    Y =   -51.931  mm,    Z =   -325790.568  mm,
    W =  -179.978 deg,    P =   -0.015 deg,    R =   -1.000 deg
};
P[25]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350112.990  mm,    Y =   -70.984  mm,    Z =   -325790.855  mm,
    W =  -180.062 deg,    P =   -0.009 deg,    R =   -0.998 deg
};
P[26]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350101.500  mm,    Y =   -72.451  mm,    Z =   -325790.283  mm,
    W =  -180.034 deg,    P =   0.001 deg,    R =   -0.999 deg
};
P[27]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350087.376  mm,    Y =   -57.869  mm,    Z =   -325790.409  mm,
    W =  -179.970 deg,    P =   -0.006 deg,    R =   -1.000 deg
};
P[28]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350034.951  mm,    Y =   -18.264  mm,    Z =   -325790.746  mm,
    W =  -179.917 deg,    P =   0.067 deg,    R =   -0.994 deg
};
P[29]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350051.816  mm,    Y =   -37.050  mm,    Z =   -325790.529  mm,
    W =  -179.929 deg,    P =   0.056 deg,    R =   -0.996 deg
};
P[30]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350037.853  mm,    Y =   -23.670  mm,    Z =   -325790.370  mm,
    W =  -179.915 deg,    P =   0.071 deg,    R =   -0.994 deg
};
P[31]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350076.699  mm,    Y =   -96.979  mm,    Z =   -325790.974  mm,
    W =  -180.025 deg,    P =   0.031 deg,    R =   -0.999 deg
};
P[32]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350069.439  mm,    Y =   -90.027  mm,    Z =   -325790.429  mm,
    W =  -179.983 deg,    P =   0.030 deg,    R =   -0.999 deg
};
P[33]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350063.033  mm,    Y =   -83.261  mm,    Z =   -325790.743  mm,
    W =  -179.962 deg,    P =   0.036 deg,    R =   -0.999 deg
};
P[34]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350055.857  mm,    Y =   -89.086  mm,    Z =   -325790.335  mm,
    W =  -179.955 deg,    P =   0.091 deg,    R =   -0.995 deg
};
P[35]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350070.236  mm,    Y =   -103.955  mm,    Z =   -325790.563  mm,
    W =  -180.018 deg,    P =   0.085 deg,    R =   -0.996 deg
};
P[36]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350105.534  mm,    Y =   -53.652  mm,    Z =   -325791.279  mm,
    W =  -180.004 deg,    P =   -0.023 deg,    R =   -1.000 deg
};
P[37]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350097.475  mm,    Y =   -46.607  mm,    Z =   -325791.361  mm,
    W =  -179.982 deg,    P =   -0.022 deg,    R =   -1.000 deg
};
P[38]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349966.563  mm,    Y =   75.978  mm,    Z =   -325791.617  mm,
    W =  -179.950 deg,    P =   -0.050 deg,    R =   -0.997 deg
};
P[39]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350067.086  mm,    Y =   -36.321  mm,    Z =   -325791.594  mm,
    W =  -179.946 deg,    P =   0.016 deg,    R =   -0.998 deg
};
P[40]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350038.437  mm,    Y =   -10.004  mm,    Z =   -325791.993  mm,
    W =  -179.914 deg,    P =   0.059 deg,    R =   -0.994 deg
};
P[41]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350003.158  mm,    Y =   14.824  mm,    Z =   -325791.478  mm,
    W =  -179.980 deg,    P =   0.062 deg,    R =   -0.998 deg
};
P[42]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350082.528  mm,    Y =   -67.697  mm,    Z =   -325791.444  mm,
    W =  -179.969 deg,    P =   0.006 deg,    R =   -0.999 deg
};
P[43]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350007.845  mm,    Y =   4.368  mm,    Z =   -325791.929  mm,
    W =  -179.967 deg,    P =   0.084 deg,    R =   -0.996 deg
};
P[44]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350002.179  mm,    Y =   10.358  mm,    Z =   -325791.681  mm,
    W =  -179.980 deg,    P =   0.073 deg,    R =   -0.997 deg
};
P[45]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350082.980  mm,    Y =   -104.157  mm,    Z =   -325792.034  mm,
    W =  -180.043 deg,    P =   0.050 deg,    R =   -0.998 deg
};
P[46]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350030.432  mm,    Y =   -73.574  mm,    Z =   -325792.005  mm,
    W =  -179.924 deg,    P =   0.126 deg,    R =   -0.989 deg
};
P[47]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350061.356  mm,    Y =   -111.409  mm,    Z =   -325791.243  mm,
    W =  -180.000 deg,    P =   0.110 deg,    R =   -0.994 deg
};
P[48]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350048.414  mm,    Y =   -98.410  mm,    Z =   -325791.808  mm,
    W =  -179.948 deg,    P =   0.126 deg,    R =   -0.991 deg
};
P[49]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350115.281  mm,    Y =   -56.114  mm,    Z =   -325792.783  mm,
    W =  -180.045 deg,    P =   -0.031 deg,    R =   -0.999 deg
};
P[50]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350113.282  mm,    Y =   -60.656  mm,    Z =   -325792.133  mm,
    W =  -180.044 deg,    P =   -0.020 deg,    R =   -0.999 deg
};
P[51]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350079.131  mm,    Y =   -28.523  mm,    Z =   -325792.107  mm,
    W =  -179.960 deg,    P =   -0.001 deg,    R =   -0.999 deg
};
P[52]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350089.118  mm,    Y =   -47.765  mm,    Z =   -325792.798  mm,
    W =  -179.966 deg,    P =   -0.012 deg,    R =   -0.999 deg
};
P[53]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349972.807  mm,    Y =   67.995  mm,    Z =   -325793.004  mm,
    W =  -179.980 deg,    P =   -0.033 deg,    R =   -0.999 deg
};
P[54]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349961.856  mm,    Y =   78.946  mm,    Z =   -325793.004  mm,
    W =  -179.939 deg,    P =   -0.045 deg,    R =   -0.997 deg
};
P[55]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350109.166  mm,    Y =   -78.482  mm,    Z =   -325792.195  mm,
    W =  -180.058 deg,    P =   -0.000 deg,    R =   -0.998 deg
};
P[56]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350088.738  mm,    Y =   -73.067  mm,    Z =   -325792.479  mm,
    W =  -179.992 deg,    P =   0.006 deg,    R =   -1.000 deg
};
P[57]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350084.463  mm,    Y =   -71.744  mm,    Z =   -325792.239  mm,
    W =  -179.978 deg,    P =   0.007 deg,    R =   -1.000 deg
};
P[58]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350011.848  mm,    Y =   -1.164  mm,    Z =   -325793.002  mm,
    W =  -179.957 deg,    P =   0.089 deg,    R =   -0.995 deg
};
P[59]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350081.447  mm,    Y =   -92.908  mm,    Z =   -325792.647  mm,
    W =  -180.014 deg,    P =   0.019 deg,    R =   -1.000 deg
};
P[60]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350074.524  mm,    Y =   -86.311  mm,    Z =   -325792.392  mm,
    W =  -179.985 deg,    P =   0.022 deg,    R =   -1.000 deg
};
P[61]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350066.257  mm,    Y =   -77.901  mm,    Z =   -325792.791  mm,
    W =  -179.960 deg,    P =   0.030 deg,    R =   -0.999 deg
};
P[62]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350088.443  mm,    Y =   -101.021  mm,    Z =   -325792.815  mm,
    W =  -180.046 deg,    P =   0.020 deg,    R =   -0.999 deg
};
P[63]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350077.765  mm,    Y =   -111.117  mm,    Z =   -325793.025  mm,
    W =  -180.034 deg,    P =   0.063 deg,    R =   -0.997 deg
};
P[64]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350048.403  mm,    Y =   -92.740  mm,    Z =   -325792.851  mm,
    W =  -179.948 deg,    P =   0.118 deg,    R =   -0.992 deg
};
P[65]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350022.748  mm,    Y =   -66.598  mm,    Z =   -325792.342  mm,
    W =  -179.912 deg,    P =   0.134 deg,    R =   -0.987 deg
};
P[66]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350025.960  mm,    Y =   -76.793  mm,    Z =   -325792.211  mm,
    W =  -179.923 deg,    P =   0.146 deg,    R =   -0.986 deg
};
P[67]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350019.382  mm,    Y =   -70.606  mm,    Z =   -325792.231  mm,
    W =  -179.912 deg,    P =   0.151 deg,    R =   -0.985 deg
};
P[68]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350096.180  mm,    Y =   -36.772  mm,    Z =   -325793.130  mm,
    W =  -179.973 deg,    P =   -0.028 deg,    R =   -0.999 deg
};
P[69]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350089.640  mm,    Y =   -41.111  mm,    Z =   -325793.499  mm,
    W =  -179.964 deg,    P =   -0.014 deg,    R =   -0.999 deg
};
P[70]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350083.063  mm,    Y =   -34.885  mm,    Z =   -325793.819  mm,
    W =  -179.962 deg,    P =   -0.009 deg,    R =   -0.999 deg
};
P[71]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350058.843  mm,    Y =   -10.862  mm,    Z =   -325793.704  mm,
    W =  -179.911 deg,    P =   0.035 deg,    R =   -0.995 deg
};
P[72]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350057.290  mm,    Y =   -9.309  mm,    Z =   -325793.704  mm,
    W =  -179.909 deg,    P =   0.030 deg,    R =   -0.995 deg
};
P[73]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350076.331  mm,    Y =   -36.434  mm,    Z =   -325793.346  mm,
    W =  -179.958 deg,    P =   0.004 deg,    R =   -0.999 deg
};
P[74]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349968.764  mm,    Y =   63.020  mm,    Z =   -325793.550  mm,
    W =  -179.983 deg,    P =   -0.016 deg,    R =   -1.000 deg
};
P[75]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349962.018  mm,    Y =   70.255  mm,    Z =   -325793.344  mm,
    W =  -179.954 deg,    P =   -0.023 deg,    R =   -0.999 deg
};
P[76]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350001.352  mm,    Y =   25.860  mm,    Z =   -325793.584  mm,
    W =  -179.990 deg,    P =   0.045 deg,    R =   -0.999 deg
};
P[77]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349994.175  mm,    Y =   32.500  mm,    Z =   -325794.028  mm,
    W =  -180.005 deg,    P =   0.033 deg,    R =   -0.999 deg
};
P[78]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350013.152  mm,    Y =   6.201  mm,    Z =   -325793.274  mm,
    W =  -179.962 deg,    P =   0.081 deg,    R =   -0.996 deg
};
P[79]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350078.920  mm,    Y =   -63.721  mm,    Z =   -325793.642  mm,
    W =  -179.964 deg,    P =   0.008 deg,    R =   -0.999 deg
};
P[80]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350045.939  mm,    Y =   -37.934  mm,    Z =   -325794.011  mm,
    W =  -179.927 deg,    P =   0.069 deg,    R =   -0.995 deg
};
P[81]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350040.829  mm,    Y =   -34.049  mm,    Z =   -325793.810  mm,
    W =  -179.921 deg,    P =   0.066 deg,    R =   -0.995 deg
};
P[82]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350034.828  mm,    Y =   -27.848  mm,    Z =   -325793.881  mm,
    W =  -179.917 deg,    P =   0.072 deg,    R =   -0.994 deg
};
P[83]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350080.033  mm,    Y =   -79.790  mm,    Z =   -325794.000  mm,
    W =  -179.982 deg,    P =   0.013 deg,    R =   -1.000 deg
};
P[84]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350056.828  mm,    Y =   -78.932  mm,    Z =   -325793.326  mm,
    W =  -179.948 deg,    P =   0.050 deg,    R =   -0.997 deg
};
P[85]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350087.464  mm,    Y =   -110.112  mm,    Z =   -325793.758  mm,
    W =  -180.049 deg,    P =   0.048 deg,    R =   -0.998 deg
};
P[86]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350066.176  mm,    Y =   -112.018  mm,    Z =   -325793.417  mm,
    W =  -180.013 deg,    P =   0.094 deg,    R =   -0.996 deg
};
P[87]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350036.028  mm,    Y =   -82.468  mm,    Z =   -325793.828  mm,
    W =  -179.935 deg,    P =   0.138 deg,    R =   -0.988 deg
};
P[88]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350030.897  mm,    Y =   -83.069  mm,    Z =   -325793.418  mm,
    W =  -179.931 deg,    P =   0.147 deg,    R =   -0.987 deg
};
P[89]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350055.728  mm,    Y =   -113.199  mm,    Z =   -325793.429  mm,
    W =  -179.994 deg,    P =   0.132 deg,    R =   -0.991 deg
};
P[90]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350049.709  mm,    Y =   -109.136  mm,    Z =   -325793.184  mm,
    W =  -179.971 deg,    P =   0.138 deg,    R =   -0.990 deg
};
P[91]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350012.670  mm,    Y =   -76.422  mm,    Z =   -325794.010  mm,
    W =  -179.910 deg,    P =   0.180 deg,    R =   -0.980 deg
};
P[92]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350082.367  mm,    Y =   -22.968  mm,    Z =   -325794.168  mm,
    W =  -179.958 deg,    P =   -0.018 deg,    R =   -0.999 deg
};
P[93]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349971.374  mm,    Y =   79.362  mm,    Z =   -325795.045  mm,
    W =  -179.953 deg,    P =   -0.069 deg,    R =   -0.997 deg
};
P[94]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349975.910  mm,    Y =   70.290  mm,    Z =   -325794.982  mm,
    W =  -179.981 deg,    P =   -0.053 deg,    R =   -0.998 deg
};
P[95]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350046.379  mm,    Y =   -5.619  mm,    Z =   -325794.153  mm,
    W =  -179.914 deg,    P =   0.041 deg,    R =   -0.995 deg
};
P[96]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350083.158  mm,    Y =   -44.219  mm,    Z =   -325794.839  mm,
    W =  -179.965 deg,    P =   -0.002 deg,    R =   -0.999 deg
};
P[97]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350082.135  mm,    Y =   -50.253  mm,    Z =   -325794.260  mm,
    W =  -179.957 deg,    P =   -0.004 deg,    R =   -0.999 deg
};
P[98]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350115.282  mm,    Y =   -84.404  mm,    Z =   -325794.516  mm,
    W =  -180.072 deg,    P =   -0.013 deg,    R =   -0.997 deg
};
P[99]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349975.452  mm,    Y =   55.766  mm,    Z =   -325794.618  mm,
    W =  -179.998 deg,    P =   -0.010 deg,    R =   -1.000 deg
};
P[100]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350007.829  mm,    Y =   18.635  mm,    Z =   -325794.494  mm,
    W =  -179.980 deg,    P =   0.065 deg,    R =   -0.998 deg
};
P[101]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350018.131  mm,    Y =   -1.414  mm,    Z =   -325794.787  mm,
    W =  -179.950 deg,    P =   0.085 deg,    R =   -0.995 deg
};
P[102]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349996.081  mm,    Y =   19.785  mm,    Z =   -325794.452  mm,
    W =  -179.994 deg,    P =   0.056 deg,    R =   -0.998 deg
};
P[103]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349960.563  mm,    Y =   55.367  mm,    Z =   -325794.357  mm,
    W =  -179.977 deg,    P =   0.017 deg,    R =   -1.000 deg
};
P[104]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349953.505  mm,    Y =   62.768  mm,    Z =   -325794.166  mm,
    W =  -179.955 deg,    P =   0.017 deg,    R =   -0.999 deg
};
P[105]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350094.750  mm,    Y =   -78.982  mm,    Z =   -325794.352  mm,
    W =  -180.016 deg,    P =   0.009 deg,    R =   -1.000 deg
};
P[106]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350031.284  mm,    Y =   -15.566  mm,    Z =   -325794.586  mm,
    W =  -179.925 deg,    P =   0.073 deg,    R =   -0.995 deg
};
P[107]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350052.463  mm,    Y =   -40.537  mm,    Z =   -325794.235  mm,
    W =  -179.934 deg,    P =   0.048 deg,    R =   -0.997 deg
};
P[108]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350009.736  mm,    Y =   -3.955  mm,    Z =   -325794.657  mm,
    W =  -179.956 deg,    P =   0.093 deg,    R =   -0.995 deg
};
P[109]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350005.048  mm,    Y =   0.126  mm,    Z =   -325794.872  mm,
    W =  -179.968 deg,    P =   0.087 deg,    R =   -0.996 deg
};
P[110]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349998.580  mm,    Y =   7.031  mm,    Z =   -325794.614  mm,
    W =  -179.982 deg,    P =   0.074 deg,    R =   -0.997 deg
};
P[111]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350073.336  mm,    Y =   -73.450  mm,    Z =   -325794.151  mm,
    W =  -179.960 deg,    P =   0.017 deg,    R =   -0.999 deg
};
P[112]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350093.043  mm,    Y =   -95.151  mm,    Z =   -325794.689  mm,
    W =  -180.046 deg,    P =   0.013 deg,    R =   -0.999 deg
};
P[113]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350086.366  mm,    Y =   -87.656  mm,    Z =   -325794.795  mm,
    W =  -180.015 deg,    P =   0.019 deg,    R =   -1.000 deg
};
P[114]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350094.091  mm,    Y =   -108.822  mm,    Z =   -325794.963  mm,
    W =  -180.056 deg,    P =   0.023 deg,    R =   -0.998 deg
};
P[115]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350049.794  mm,    Y =   -82.241  mm,    Z =   -325794.520  mm,
    W =  -179.943 deg,    P =   0.095 deg,    R =   -0.994 deg
};
P[116]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350042.741  mm,    Y =   -75.805  mm,    Z =   -325794.858  mm,
    W =  -179.934 deg,    P =   0.100 deg,    R =   -0.993 deg
};
P[117]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350034.531  mm,    Y =   -69.084  mm,    Z =   -325794.297  mm,
    W =  -179.925 deg,    P =   0.104 deg,    R =   -0.992 deg
};
P[118]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350014.134  mm,    Y =   -60.338  mm,    Z =   -325794.557  mm,
    W =  -179.904 deg,    P =   0.140 deg,    R =   -0.985 deg
};
P[119]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350041.645  mm,    Y =   -96.031  mm,    Z =   -325794.817  mm,
    W =  -179.946 deg,    P =   0.134 deg,    R =   -0.990 deg
};
P[120]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350011.080  mm,    Y =   -65.025  mm,    Z =   -325794.226  mm,
    W =  -179.904 deg,    P =   0.151 deg,    R =   -0.984 deg
};
P[121]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350004.129  mm,    Y =   -59.090  mm,    Z =   -325795.033  mm,
    W =  -179.908 deg,    P =   0.141 deg,    R =   -0.986 deg
};
P[122]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350043.033  mm,    Y =   -102.973  mm,    Z =   -325794.846  mm,
    W =  -179.953 deg,    P =   0.141 deg,    R =   -0.989 deg
};
P[123]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350019.567  mm,    Y =   -83.125  mm,    Z =   -325794.240  mm,
    W =  -179.916 deg,    P =   0.177 deg,    R =   -0.981 deg
};
P[124]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350005.837  mm,    Y =   -69.870  mm,    Z =   -325794.797  mm,
    W =  -179.907 deg,    P =   0.181 deg,    R =   -0.979 deg
};
P[125]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350089.404  mm,    Y =   -28.626  mm,    Z =   -325795.877  mm,
    W =  -179.968 deg,    P =   -0.022 deg,    R =   -0.999 deg
};
P[126]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350119.204  mm,    Y =   -69.753  mm,    Z =   -325795.488  mm,
    W =  -180.073 deg,    P =   -0.022 deg,    R =   -0.997 deg
};
P[127]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349982.082  mm,    Y =   62.736  mm,    Z =   -325795.539  mm,
    W =  -180.001 deg,    P =   -0.034 deg,    R =   -0.999 deg
};
P[128]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350080.112  mm,    Y =   -41.585  mm,    Z =   -325795.479  mm,
    W =  -179.958 deg,    P =   -0.002 deg,    R =   -0.999 deg
};
P[129]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349986.261  mm,    Y =   52.416  mm,    Z =   -325795.596  mm,
    W =  -180.007 deg,    P =   -0.011 deg,    R =   -1.000 deg
};
P[130]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349980.719  mm,    Y =   58.198  mm,    Z =   -325795.222  mm,
    W =  -179.998 deg,    P =   -0.018 deg,    R =   -1.000 deg
};
P[131]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350074.544  mm,    Y =   -42.523  mm,    Z =   -325795.304  mm,
    W =  -179.951 deg,    P =   0.009 deg,    R =   -0.999 deg
};
P[132]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349982.907  mm,    Y =   48.665  mm,    Z =   -325795.868  mm,
    W =  -180.004 deg,    P =   -0.002 deg,    R =   -1.000 deg
};
P[133]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349988.203  mm,    Y =   41.836  mm,    Z =   -325796.044  mm,
    W =  -180.008 deg,    P =   0.012 deg,    R =   -1.000 deg
};
P[134]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349955.281  mm,    Y =   75.820  mm,    Z =   -325795.272  mm,
    W =  -179.939 deg,    P =   -0.010 deg,    R =   -0.998 deg
};
P[135]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350060.021  mm,    Y =   -43.487  mm,    Z =   -325795.281  mm,
    W =  -179.942 deg,    P =   0.027 deg,    R =   -0.998 deg
};
P[136]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349968.097  mm,    Y =   48.847  mm,    Z =   -325795.360  mm,
    W =  -179.998 deg,    P =   0.016 deg,    R =   -1.000 deg
};
P[137]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350090.537  mm,    Y =   -83.517  mm,    Z =   -325795.797  mm,
    W =  -180.016 deg,    P =   0.009 deg,    R =   -1.000 deg
};
P[138]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350073.947  mm,    Y =   -67.232  mm,    Z =   -325796.006  mm,
    W =  -179.960 deg,    P =   0.014 deg,    R =   -0.999 deg
};
P[139]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349952.006  mm,    Y =   49.275  mm,    Z =   -325796.039  mm,
    W =  -179.971 deg,    P =   0.027 deg,    R =   -0.999 deg
};
P[140]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349946.780  mm,    Y =   54.769  mm,    Z =   -325795.231  mm,
    W =  -179.960 deg,    P =   0.023 deg,    R =   -0.999 deg
};
P[141]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350099.216  mm,    Y =   -101.778  mm,    Z =   -325796.003  mm,
    W =  -180.052 deg,    P =   -0.002 deg,    R =   -0.999 deg
};
P[142]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350058.418  mm,    Y =   -72.361  mm,    Z =   -325795.468  mm,
    W =  -179.952 deg,    P =   0.033 deg,    R =   -0.998 deg
};
P[143]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350050.859  mm,    Y =   -74.875  mm,    Z =   -325795.857  mm,
    W =  -179.943 deg,    P =   0.062 deg,    R =   -0.996 deg
};
P[144]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350085.152  mm,    Y =   -116.761  mm,    Z =   -325795.286  mm,
    W =  -180.052 deg,    P =   0.047 deg,    R =   -0.998 deg
};
P[145]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350026.542  mm,    Y =   -63.128  mm,    Z =   -325795.392  mm,
    W =  -179.918 deg,    P =   0.116 deg,    R =   -0.990 deg
};
P[146]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350070.752  mm,    Y =   -116.169  mm,    Z =   -325795.862  mm,
    W =  -180.023 deg,    P =   0.085 deg,    R =   -0.996 deg
};
P[147]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350041.736  mm,    Y =   -89.500  mm,    Z =   -325795.295  mm,
    W =  -179.945 deg,    P =   0.130 deg,    R =   -0.990 deg
};
P[148]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350108.320  mm,    Y =   -36.942  mm,    Z =   -325797.083  mm,
    W =  -179.992 deg,    P =   -0.046 deg,    R =   -0.999 deg
};
P[149]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349962.656  mm,    Y =   84.753  mm,    Z =   -325796.182  mm,
    W =  -179.928 deg,    P =   -0.059 deg,    R =   -0.996 deg
};
P[150]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350033.298  mm,    Y =   -4.714  mm,    Z =   -325796.466  mm,
    W =  -179.930 deg,    P =   0.063 deg,    R =   -0.996 deg
};
P[151]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350102.811  mm,    Y =   -85.196  mm,    Z =   -325796.447  mm,
    W =  -180.054 deg,    P =   0.006 deg,    R =   -0.999 deg
};
P[152]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350074.807  mm,    Y =   -56.709  mm,    Z =   -325796.642  mm,
    W =  -179.955 deg,    P =   0.009 deg,    R =   -0.999 deg
};
P[153]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350025.665  mm,    Y =   -7.673  mm,    Z =   -325796.542  mm,
    W =  -179.931 deg,    P =   0.075 deg,    R =   -0.995 deg
};
P[154]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349989.943  mm,    Y =   28.215  mm,    Z =   -325796.710  mm,
    W =  -180.007 deg,    P =   0.035 deg,    R =   -0.999 deg
};
P[155]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349947.203  mm,    Y =   70.366  mm,    Z =   -325796.227  mm,
    W =  -179.937 deg,    P =   0.014 deg,    R =   -0.998 deg
};
P[156]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350097.411  mm,    Y =   -90.442  mm,    Z =   -325796.579  mm,
    W =  -180.051 deg,    P =   0.010 deg,    R =   -0.999 deg
};
P[157]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349940.223  mm,    Y =   65.052  mm,    Z =   -325796.923  mm,
    W =  -179.939 deg,    P =   0.019 deg,    R =   -0.998 deg
};
P[158]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349956.261  mm,    Y =   46.838  mm,    Z =   -325797.049  mm,
    W =  -179.980 deg,    P =   0.025 deg,    R =   -0.999 deg
};
P[159]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349939.169  mm,    Y =   59.905  mm,    Z =   -325796.665  mm,
    W =  -179.942 deg,    P =   0.020 deg,    R =   -0.998 deg
};
P[160]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350065.844  mm,    Y =   -67.838  mm,    Z =   -325796.571  mm,
    W =  -179.950 deg,    P =   0.025 deg,    R =   -0.998 deg
};
P[161]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349938.750  mm,    Y =   47.580  mm,    Z =   -325796.608  mm,
    W =  -179.963 deg,    P =   0.029 deg,    R =   -0.999 deg
};
P[162]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350091.962  mm,    Y =   -115.589  mm,    Z =   -325796.277  mm,
    W =  -180.064 deg,    P =   0.039 deg,    R =   -0.997 deg
};
P[163]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349928.891  mm,    Y =   37.414  mm,    Z =   -325797.019  mm,
    W =  -179.958 deg,    P =   0.037 deg,    R =   -0.998 deg
};
P[164]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350006.721  mm,    Y =   -53.917  mm,    Z =   -325796.382  mm,
    W =  -179.911 deg,    P =   0.137 deg,    R =   -0.987 deg
};
P[165]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350036.275  mm,    Y =   -95.966  mm,    Z =   -325796.768  mm,
    W =  -179.942 deg,    P =   0.144 deg,    R =   -0.988 deg
};
P[166]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350026.995  mm,    Y =   -89.439  mm,    Z =   -325796.529  mm,
    W =  -179.925 deg,    P =   0.167 deg,    R =   -0.983 deg
};
P[167]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350000.751  mm,    Y =   -63.206  mm,    Z =   -325796.749  mm,
    W =  -179.906 deg,    P =   0.152 deg,    R =   -0.984 deg
};
P[168]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350114.780  mm,    Y =   -43.892  mm,    Z =   -325797.299  mm,
    W =  -180.029 deg,    P =   -0.053 deg,    R =   -0.998 deg
};
P[169]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349989.027  mm,    Y =   56.996  mm,    Z =   -325797.513  mm,
    W =  -180.002 deg,    P =   -0.023 deg,    R =   -1.000 deg
};
P[170]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349955.992  mm,    Y =   81.749  mm,    Z =   -325797.148  mm,
    W =  -179.932 deg,    P =   -0.032 deg,    R =   -0.997 deg
};
P[171]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350120.612  mm,    Y =   -84.944  mm,    Z =   -325797.768  mm,
    W =  -180.079 deg,    P =   -0.023 deg,    R =   -0.997 deg
};
P[172]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350013.663  mm,    Y =   15.310  mm,    Z =   -325797.452  mm,
    W =  -179.969 deg,    P =   0.068 deg,    R =   -0.997 deg
};
P[173]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350068.272  mm,    Y =   -49.138  mm,    Z =   -325797.662  mm,
    W =  -179.945 deg,    P =   0.017 deg,    R =   -0.998 deg
};
P[174]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349976.095  mm,    Y =   43.096  mm,    Z =   -325797.873  mm,
    W =  -180.004 deg,    P =   0.014 deg,    R =   -1.000 deg
};
P[175]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350068.045  mm,    Y =   -62.359  mm,    Z =   -325797.819  mm,
    W =  -179.954 deg,    P =   0.023 deg,    R =   -0.999 deg
};
P[176]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350104.859  mm,    Y =   -107.577  mm,    Z =   -325798.043  mm,
    W =  -180.069 deg,    P =   0.001 deg,    R =   -0.998 deg
};
P[177]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350060.317  mm,    Y =   -63.037  mm,    Z =   -325798.043  mm,
    W =  -179.944 deg,    P =   0.026 deg,    R =   -0.998 deg
};
P[178]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349932.258  mm,    Y =   65.016  mm,    Z =   -325798.043  mm,
    W =  -179.933 deg,    P =   0.022 deg,    R =   -0.997 deg
};
P[179]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350100.244  mm,    Y =   -112.324  mm,    Z =   -325797.536  mm,
    W =  -180.065 deg,    P =   0.032 deg,    R =   -0.997 deg
};
P[180]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349932.006  mm,    Y =   55.104  mm,    Z =   -325797.696  mm,
    W =  -179.938 deg,    P =   0.026 deg,    R =   -0.998 deg
};
P[181]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350046.145  mm,    Y =   -69.989  mm,    Z =   -325797.113  mm,
    W =  -179.933 deg,    P =   0.068 deg,    R =   -0.995 deg
};
P[182]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349932.957  mm,    Y =   41.667  mm,    Z =   -325797.190  mm,
    W =  -179.961 deg,    P =   0.034 deg,    R =   -0.999 deg
};
P[183]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349934.739  mm,    Y =   30.524  mm,    Z =   -325797.281  mm,
    W =  -179.979 deg,    P =   0.045 deg,    R =   -0.999 deg
};
P[184]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350020.616  mm,    Y =   -57.078  mm,    Z =   -325797.705  mm,
    W =  -179.909 deg,    P =   0.124 deg,    R =   -0.988 deg
};
P[185]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349922.737  mm,    Y =   31.620  mm,    Z =   -325797.838  mm,
    W =  -179.961 deg,    P =   0.081 deg,    R =   -0.996 deg
};
P[186]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350121.772  mm,    Y =   -53.439  mm,    Z =   -325798.700  mm,
    W =  -180.056 deg,    P =   -0.049 deg,    R =   -0.997 deg
};
P[187]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349993.367  mm,    Y =   45.181  mm,    Z =   -325798.582  mm,
    W =  -180.007 deg,    P =   0.006 deg,    R =   -1.000 deg
};
P[188]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349983.760  mm,    Y =   36.745  mm,    Z =   -325799.017  mm,
    W =  -180.007 deg,    P =   0.020 deg,    R =   -1.000 deg
};
P[189]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350110.260  mm,    Y =   -90.274  mm,    Z =   -325798.170  mm,
    W =  -180.062 deg,    P =   -0.004 deg,    R =   -0.998 deg
};
P[190]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349940.988  mm,    Y =   77.598  mm,    Z =   -325798.133  mm,
    W =  -179.927 deg,    P =   0.012 deg,    R =   -0.997 deg
};
P[191]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350104.680  mm,    Y =   -98.060  mm,    Z =   -325798.811  mm,
    W =  -180.053 deg,    P =   -0.006 deg,    R =   -0.999 deg
};
P[192]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349933.159  mm,    Y =   70.876  mm,    Z =   -325798.362  mm,
    W =  -179.929 deg,    P =   0.019 deg,    R =   -0.997 deg
};
P[193]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350010.590  mm,    Y =   -8.625  mm,    Z =   -325798.971  mm,
    W =  -179.947 deg,    P =   0.093 deg,    R =   -0.994 deg
};
P[194]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349961.292  mm,    Y =   41.780  mm,    Z =   -325798.813  mm,
    W =  -179.990 deg,    P =   0.028 deg,    R =   -1.000 deg
};
P[195]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349946.454  mm,    Y =   41.544  mm,    Z =   -325799.039  mm,
    W =  -179.975 deg,    P =   0.032 deg,    R =   -0.999 deg
};
P[196]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350052.801  mm,    Y =   -65.629  mm,    Z =   -325798.420  mm,
    W =  -179.940 deg,    P =   0.041 deg,    R =   -0.997 deg
};
P[197]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349923.409  mm,    Y =   42.305  mm,    Z =   -325798.395  mm,
    W =  -179.947 deg,    P =   0.039 deg,    R =   -0.998 deg
};
P[198]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349939.264  mm,    Y =   25.407  mm,    Z =   -325798.976  mm,
    W =  -179.995 deg,    P =   0.051 deg,    R =   -0.999 deg
};
P[199]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350078.916  mm,    Y =   -118.626  mm,    Z =   -325798.644  mm,
    W =  -180.039 deg,    P =   0.069 deg,    R =   -0.997 deg
};
P[200]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349930.123  mm,    Y =   24.892  mm,    Z =   -325798.337  mm,
    W =  -179.988 deg,    P =   0.079 deg,    R =   -0.997 deg
};
P[201]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349997.641  mm,    Y =   -58.727  mm,    Z =   -325798.808  mm,
    W =  -179.910 deg,    P =   0.139 deg,    R =   -0.986 deg
};
P[202]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350008.533  mm,    Y =   -80.466  mm,    Z =   -325798.922  mm,
    W =  -179.908 deg,    P =   0.204 deg,    R =   -0.975 deg
};
P[203]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350001.534  mm,    Y =   -74.136  mm,    Z =   -325798.928  mm,
    W =  -179.905 deg,    P =   0.199 deg,    R =   -0.976 deg
};
P[204]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350100.244  mm,    Y =   -30.564  mm,    Z =   -325799.703  mm,
    W =  -179.973 deg,    P =   -0.044 deg,    R =   -0.999 deg
};
P[205]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350123.221  mm,    Y =   -76.371  mm,    Z =   -325799.227  mm,
    W =  -180.084 deg,    P =   -0.028 deg,    R =   -0.996 deg
};
P[206]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350041.013  mm,    Y =   -2.841  mm,    Z =   -325799.430  mm,
    W =  -179.929 deg,    P =   0.054 deg,    R =   -0.996 deg
};
P[207]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350007.308  mm,    Y =   31.079  mm,    Z =   -325799.953  mm,
    W =  -179.989 deg,    P =   0.043 deg,    R =   -0.999 deg
};
P[208]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350000.076  mm,    Y =   37.715  mm,    Z =   -325799.902  mm,
    W =  -180.000 deg,    P =   0.027 deg,    R =   -1.000 deg
};
P[209]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349942.672  mm,    Y =   83.916  mm,    Z =   -325800.046  mm,
    W =  -179.913 deg,    P =   0.005 deg,    R =   -0.996 deg
};
P[210]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349933.699  mm,    Y =   83.877  mm,    Z =   -325799.942  mm,
    W =  -179.905 deg,    P =   0.008 deg,    R =   -0.995 deg
};
P[211]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350060.463  mm,    Y =   -56.167  mm,    Z =   -325799.483  mm,
    W =  -179.942 deg,    P =   0.027 deg,    R =   -0.998 deg
};
P[212]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349989.949  mm,    Y =   13.692  mm,    Z =   -325799.557  mm,
    W =  -179.995 deg,    P =   0.053 deg,    R =   -0.999 deg
};
P[213]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349995.319  mm,    Y =   5.265  mm,    Z =   -325799.168  mm,
    W =  -179.984 deg,    P =   0.074 deg,    R =   -0.997 deg
};
P[214]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350002.213  mm,    Y =   -2.636  mm,    Z =   -325799.161  mm,
    W =  -179.968 deg,    P =   0.085 deg,    R =   -0.996 deg
};
P[215]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349926.060  mm,    Y =   62.868  mm,    Z =   -325799.117  mm,
    W =  -179.930 deg,    P =   0.026 deg,    R =   -0.997 deg
};
P[216]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350040.265  mm,    Y =   -63.102  mm,    Z =   -325799.705  mm,
    W =  -179.926 deg,    P =   0.082 deg,    R =   -0.994 deg
};
P[217]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349940.610  mm,    Y =   34.255  mm,    Z =   -325799.090  mm,
    W =  -179.981 deg,    P =   0.036 deg,    R =   -0.999 deg
};
P[218]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349924.778  mm,    Y =   48.244  mm,    Z =   -325799.178  mm,
    W =  -179.939 deg,    P =   0.035 deg,    R =   -0.998 deg
};
P[219]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349916.293  mm,    Y =   39.147  mm,    Z =   -325799.728  mm,
    W =  -179.938 deg,    P =   0.061 deg,    R =   -0.996 deg
};
P[220]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350034.123  mm,    Y =   -96.518  mm,    Z =   -325799.689  mm,
    W =  -179.938 deg,    P =   0.146 deg,    R =   -0.987 deg
};
P[221]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350021.961  mm,    Y =   -91.329  mm,    Z =   -325799.997  mm,
    W =  -179.921 deg,    P =   0.174 deg,    R =   -0.982 deg
};
P[222]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350016.196  mm,    Y =   -86.809  mm,    Z =   -325799.300  mm,
    W =  -179.912 deg,    P =   0.186 deg,    R =   -0.979 deg
};
P[223]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349996.900  mm,    Y =   -67.699  mm,    Z =   -325799.760  mm,
    W =  -179.911 deg,    P =   0.187 deg,    R =   -0.978 deg
};
P[224]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350093.929  mm,    Y =   -24.699  mm,    Z =   -325800.439  mm,
    W =  -179.971 deg,    P =   -0.041 deg,    R =   -0.999 deg
};
P[225]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349975.260  mm,    Y =   84.142  mm,    Z =   -325800.410  mm,
    W =  -179.949 deg,    P =   -0.086 deg,    R =   -0.995 deg
};
P[226]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349995.104  mm,    Y =   51.652  mm,    Z =   -325800.959  mm,
    W =  -180.005 deg,    P =   -0.008 deg,    R =   -1.000 deg
};
P[227]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350012.827  mm,    Y =   23.326  mm,    Z =   -325800.982  mm,
    W =  -179.977 deg,    P =   0.061 deg,    R =   -0.998 deg
};
P[228]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349949.586  mm,    Y =   86.494  mm,    Z =   -325800.190  mm,
    W =  -179.911 deg,    P =   -0.024 deg,    R =   -0.996 deg
};
P[229]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349942.138  mm,    Y =   93.029  mm,    Z =   -325801.025  mm,
    W =  -179.877 deg,    P =   -0.032 deg,    R =   -0.992 deg
};
P[230]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349936.613  mm,    Y =   89.090  mm,    Z =   -325800.945  mm,
    W =  -179.893 deg,    P =   -0.011 deg,    R =   -0.994 deg
};
P[231]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350040.884  mm,    Y =   -34.530  mm,    Z =   -325800.685  mm,
    W =  -179.923 deg,    P =   0.065 deg,    R =   -0.995 deg
};
P[232]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349969.141  mm,    Y =   35.957  mm,    Z =   -325801.042  mm,
    W =  -180.002 deg,    P =   0.030 deg,    R =   -1.000 deg
};
P[233]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349926.587  mm,    Y =   78.162  mm,    Z =   -325800.122  mm,
    W =  -179.907 deg,    P =   0.014 deg,    R =   -0.996 deg
};
P[234]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350053.775  mm,    Y =   -59.042  mm,    Z =   -325800.888  mm,
    W =  -179.940 deg,    P =   0.030 deg,    R =   -0.998 deg
};
P[235]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349921.470  mm,    Y =   73.573  mm,    Z =   -325800.156  mm,
    W =  -179.911 deg,    P =   0.015 deg,    R =   -0.996 deg
};
P[236]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349952.588  mm,    Y =   41.013  mm,    Z =   -325800.557  mm,
    W =  -179.984 deg,    P =   0.032 deg,    R =   -0.999 deg
};
P[237]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349918.811  mm,    Y =   68.908  mm,    Z =   -325800.258  mm,
    W =  -179.914 deg,    P =   0.023 deg,    R =   -0.996 deg
};
P[238]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350095.370  mm,    Y =   -117.440  mm,    Z =   -325800.978  mm,
    W =  -180.071 deg,    P =   0.042 deg,    R =   -0.997 deg
};
P[239]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349918.247  mm,    Y =   45.422  mm,    Z =   -325800.485  mm,
    W =  -179.939 deg,    P =   0.041 deg,    R =   -0.997 deg
};
P[240]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349935.760  mm,    Y =   20.409  mm,    Z =   -325800.804  mm,
    W =  -180.008 deg,    P =   0.082 deg,    R =   -0.997 deg
};
P[241]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350000.938  mm,    Y =   -48.363  mm,    Z =   -325800.127  mm,
    W =  -179.920 deg,    P =   0.133 deg,    R =   -0.988 deg
};
P[242]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350058.869  mm,    Y =   -113.800  mm,    Z =   -325801.009  mm,
    W =  -179.994 deg,    P =   0.111 deg,    R =   -0.994 deg
};
P[243]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349915.853  mm,    Y =   24.448  mm,    Z =   -325800.455  mm,
    W =  -179.964 deg,    P =   0.127 deg,    R =   -0.991 deg
};
P[244]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349908.929  mm,    Y =   31.760  mm,    Z =   -325800.699  mm,
    W =  -179.945 deg,    P =   0.110 deg,    R =   -0.992 deg
};
P[245]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350028.299  mm,    Y =   -94.604  mm,    Z =   -325800.431  mm,
    W =  -179.930 deg,    P =   0.166 deg,    R =   -0.984 deg
};
P[246]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350089.327  mm,    Y =   -19.717  mm,    Z =   -325801.428  mm,
    W =  -179.964 deg,    P =   -0.049 deg,    R =   -0.998 deg
};
P[247]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349966.781  mm,    Y =   91.903  mm,    Z =   -325801.813  mm,
    W =  -179.926 deg,    P =   -0.091 deg,    R =   -0.993 deg
};
P[248]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349957.022  mm,    Y =   90.164  mm,    Z =   -325801.363  mm,
    W =  -179.921 deg,    P =   -0.058 deg,    R =   -0.995 deg
};
P[249]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350034.245  mm,    Y =   1.222  mm,    Z =   -325802.058  mm,
    W =  -179.933 deg,    P =   0.058 deg,    R =   -0.996 deg
};
P[250]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350115.093  mm,    Y =   -92.009  mm,    Z =   -325801.556  mm,
    W =  -180.060 deg,    P =   -0.012 deg,    R =   -0.998 deg
};
P[251]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349927.287  mm,    Y =   89.274  mm,    Z =   -325801.740  mm,
    W =  -179.887 deg,    P =   -0.001 deg,    R =   -0.994 deg
};
P[252]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350048.495  mm,    Y =   -41.044  mm,    Z =   -325802.025  mm,
    W =  -179.931 deg,    P =   0.057 deg,    R =   -0.996 deg
};
P[253]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350054.482  mm,    Y =   -48.491  mm,    Z =   -325801.956  mm,
    W =  -179.941 deg,    P =   0.031 deg,    R =   -0.998 deg
};
P[254]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350026.638  mm,    Y =   -20.631  mm,    Z =   -325801.655  mm,
    W =  -179.925 deg,    P =   0.084 deg,    R =   -0.994 deg
};
P[255]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350032.965  mm,    Y =   -27.381  mm,    Z =   -325801.744  mm,
    W =  -179.920 deg,    P =   0.073 deg,    R =   -0.994 deg
};
P[256]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350018.973  mm,    Y =   -14.170  mm,    Z =   -325801.485  mm,
    W =  -179.930 deg,    P =   0.089 deg,    R =   -0.994 deg
};
P[257]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349983.551  mm,    Y =   21.796  mm,    Z =   -325801.296  mm,
    W =  -180.004 deg,    P =   0.036 deg,    R =   -0.999 deg
};
P[258]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349912.591  mm,    Y =   73.693  mm,    Z =   -325801.557  mm,
    W =  -179.892 deg,    P =   0.028 deg,    R =   -0.994 deg
};
P[259]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350046.053  mm,    Y =   -61.602  mm,    Z =   -325801.545  mm,
    W =  -179.931 deg,    P =   0.058 deg,    R =   -0.996 deg
};
P[260]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350031.829  mm,    Y =   -58.185  mm,    Z =   -325801.995  mm,
    W =  -179.923 deg,    P =   0.083 deg,    R =   -0.994 deg
};
P[261]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349918.395  mm,    Y =   55.961  mm,    Z =   -325801.852  mm,
    W =  -179.933 deg,    P =   0.027 deg,    R =   -0.997 deg
};
P[262]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349908.282  mm,    Y =   44.936  mm,    Z =   -325801.866  mm,
    W =  -179.926 deg,    P =   0.069 deg,    R =   -0.995 deg
};
P[263]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349923.350  mm,    Y =   18.244  mm,    Z =   -325801.735  mm,
    W =  -179.990 deg,    P =   0.131 deg,    R =   -0.991 deg
};
P[264]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349902.315  mm,    Y =   39.201  mm,    Z =   -325801.570  mm,
    W =  -179.923 deg,    P =   0.093 deg,    R =   -0.993 deg
};
P[265]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350041.065  mm,    Y =   -104.388  mm,    Z =   -325801.305  mm,
    W =  -179.946 deg,    P =   0.141 deg,    R =   -0.989 deg
};
P[266]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349904.039  mm,    Y =   27.407  mm,    Z =   -325801.274  mm,
    W =  -179.951 deg,    P =   0.128 deg,    R =   -0.991 deg
};
P[267]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349896.616  mm,    Y =   34.615  mm,    Z =   -325801.760  mm,
    W =  -179.922 deg,    P =   0.123 deg,    R =   -0.989 deg
};
P[268]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349900.661  mm,    Y =   23.415  mm,    Z =   -325801.577  mm,
    W =  -179.958 deg,    P =   0.153 deg,    R =   -0.987 deg
};
P[269]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349893.820  mm,    Y =   29.941  mm,    Z =   -325801.963  mm,
    W =  -179.924 deg,    P =   0.140 deg,    R =   -0.987 deg
};
P[270]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350126.183  mm,    Y =   -60.909  mm,    Z =   -325802.304  mm,
    W =  -180.072 deg,    P =   -0.045 deg,    R =   -0.996 deg
};
P[271]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349988.268  mm,    Y =   70.254  mm,    Z =   -325802.575  mm,
    W =  -179.997 deg,    P =   -0.067 deg,    R =   -0.998 deg
};
P[272]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350126.928  mm,    Y =   -73.297  mm,    Z =   -325802.907  mm,
    W =  -180.075 deg,    P =   -0.037 deg,    R =   -0.996 deg
};
P[273]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350123.968  mm,    Y =   -88.138  mm,    Z =   -325802.578  mm,
    W =  -180.097 deg,    P =   -0.033 deg,    R =   -0.995 deg
};
P[274]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350019.522  mm,    Y =   15.595  mm,    Z =   -325802.246  mm,
    W =  -179.964 deg,    P =   0.061 deg,    R =   -0.997 deg
};
P[275]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349976.894  mm,    Y =   29.660  mm,    Z =   -325802.529  mm,
    W =  -180.005 deg,    P =   0.030 deg,    R =   -1.000 deg
};
P[276]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349920.446  mm,    Y =   85.739  mm,    Z =   -325802.251  mm,
    W =  -179.885 deg,    P =   0.009 deg,    R =   -0.993 deg
};
P[277]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350109.456  mm,    Y =   -105.461  mm,    Z =   -325802.428  mm,
    W =  -180.071 deg,    P =   -0.010 deg,    R =   -0.997 deg
};
P[278]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350105.297  mm,    Y =   -113.109  mm,    Z =   -325802.904  mm,
    W =  -180.086 deg,    P =   0.019 deg,    R =   -0.996 deg
};
P[279]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349955.310  mm,    Y =   35.452  mm,    Z =   -325802.599  mm,
    W =  -179.990 deg,    P =   0.033 deg,    R =   -0.999 deg
};
P[280]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349912.387  mm,    Y =   79.245  mm,    Z =   -325802.874  mm,
    W =  -179.879 deg,    P =   0.024 deg,    R =   -0.992 deg
};
P[281]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349949.791  mm,    Y =   34.971  mm,    Z =   -325802.748  mm,
    W =  -179.985 deg,    P =   0.036 deg,    R =   -0.999 deg
};
P[282]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349946.425  mm,    Y =   27.664  mm,    Z =   -325802.986  mm,
    W =  -179.993 deg,    P =   0.043 deg,    R =   -0.999 deg
};
P[283]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350022.591  mm,    Y =   -52.553  mm,    Z =   -325802.849  mm,
    W =  -179.912 deg,    P =   0.114 deg,    R =   -0.990 deg
};
P[284]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350011.681  mm,    Y =   -46.792  mm,    Z =   -325802.293  mm,
    W =  -179.914 deg,    P =   0.129 deg,    R =   -0.988 deg
};
P[285]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349912.211  mm,    Y =   49.948  mm,    Z =   -325802.898  mm,
    W =  -179.923 deg,    P =   0.051 deg,    R =   -0.996 deg
};
P[286]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350049.810  mm,    Y =   -109.602  mm,    Z =   -325802.297  mm,
    W =  -179.966 deg,    P =   0.136 deg,    R =   -0.990 deg
};
P[287]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349905.210  mm,    Y =   18.028  mm,    Z =   -325802.699  mm,
    W =  -179.972 deg,    P =   0.163 deg,    R =   -0.986 deg
};
P[288]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349894.102  mm,    Y =   16.890  mm,    Z =   -325802.735  mm,
    W =  -179.964 deg,    P =   0.174 deg,    R =   -0.984 deg
};
P[289]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349978.342  mm,    Y =   86.078  mm,    Z =   -325803.944  mm,
    W =  -179.953 deg,    P =   -0.097 deg,    R =   -0.994 deg
};
P[290]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349983.144  mm,    Y =   76.598  mm,    Z =   -325803.180  mm,
    W =  -179.977 deg,    P =   -0.079 deg,    R =   -0.997 deg
};
P[291]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349995.317  mm,    Y =   59.870  mm,    Z =   -325803.775  mm,
    W =  -180.005 deg,    P =   -0.035 deg,    R =   -0.999 deg
};
P[292]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349951.338  mm,    Y =   94.359  mm,    Z =   -325803.621  mm,
    W =  -179.890 deg,    P =   -0.064 deg,    R =   -0.992 deg
};
P[293]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349936.140  mm,    Y =   99.924  mm,    Z =   -325803.594  mm,
    W =  -179.854 deg,    P =   -0.053 deg,    R =   -0.988 deg
};
P[294]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350027.128  mm,    Y =   8.249  mm,    Z =   -325803.620  mm,
    W =  -179.951 deg,    P =   0.067 deg,    R =   -0.997 deg
};
P[295]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349929.304  mm,    Y =   95.097  mm,    Z =   -325803.240  mm,
    W =  -179.869 deg,    P =   -0.020 deg,    R =   -0.991 deg
};
P[296]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349912.222  mm,    Y =   63.361  mm,    Z =   -325803.205  mm,
    W =  -179.909 deg,    P =   0.033 deg,    R =   -0.995 deg
};
P[297]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349941.193  mm,    Y =   18.926  mm,    Z =   -325803.896  mm,
    W =  -180.005 deg,    P =   0.066 deg,    R =   -0.998 deg
};
P[298]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349902.819  mm,    Y =   50.120  mm,    Z =   -325803.160  mm,
    W =  -179.906 deg,    P =   0.069 deg,    R =   -0.993 deg
};
P[299]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350065.907  mm,    Y =   -116.002  mm,    Z =   -325803.397  mm,
    W =  -180.011 deg,    P =   0.095 deg,    R =   -0.995 deg
};
P[300]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349994.877  mm,    Y =   -52.130  mm,    Z =   -325803.279  mm,
    W =  -179.920 deg,    P =   0.131 deg,    R =   -0.988 deg
};
P[301]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349896.205  mm,    Y =   46.875  mm,    Z =   -325803.880  mm,
    W =  -179.895 deg,    P =   0.085 deg,    R =   -0.991 deg
};
P[302]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349910.470  mm,    Y =   17.688  mm,    Z =   -325803.229  mm,
    W =  -179.974 deg,    P =   0.157 deg,    R =   -0.987 deg
};
P[303]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349888.344  mm,    Y =   34.335  mm,    Z =   -325803.186  mm,
    W =  -179.908 deg,    P =   0.137 deg,    R =   -0.986 deg
};
P[304]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349887.202  mm,    Y =   24.421  mm,    Z =   -325803.677  mm,
    W =  -179.932 deg,    P =   0.163 deg,    R =   -0.984 deg
};
P[305]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350120.692  mm,    Y =   -38.588  mm,    Z =   -325804.335  mm,
    W =  -180.035 deg,    P =   -0.074 deg,    R =   -0.997 deg
};
P[306]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349973.138  mm,    Y =   93.566  mm,    Z =   -325804.406  mm,
    W =  -179.928 deg,    P =   -0.113 deg,    R =   -0.991 deg
};
P[307]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349998.959  mm,    Y =   51.431  mm,    Z =   -325804.972  mm,
    W =  -180.008 deg,    P =   -0.007 deg,    R =   -1.000 deg
};
P[308]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349999.710  mm,    Y =   47.277  mm,    Z =   -325804.836  mm,
    W =  -180.005 deg,    P =   -0.002 deg,    R =   -1.000 deg
};
P[309]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349947.934  mm,    Y =   98.621  mm,    Z =   -325804.431  mm,
    W =  -179.876 deg,    P =   -0.066 deg,    R =   -0.990 deg
};
P[310]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349929.795  mm,    Y =   104.515  mm,    Z =   -325805.071  mm,
    W =  -179.836 deg,    P =   -0.052 deg,    R =   -0.985 deg
};
P[311]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349914.857  mm,    Y =   91.240  mm,    Z =   -325804.919  mm,
    W =  -179.864 deg,    P =   0.008 deg,    R =   -0.991 deg
};
P[312]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349962.512  mm,    Y =   29.156  mm,    Z =   -325804.936  mm,
    W =  -180.000 deg,    P =   0.036 deg,    R =   -0.999 deg
};
P[313]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349952.515  mm,    Y =   29.446  mm,    Z =   -325804.934  mm,
    W =  -179.994 deg,    P =   0.042 deg,    R =   -0.999 deg
};
P[314]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349906.306  mm,    Y =   70.095  mm,    Z =   -325804.813  mm,
    W =  -179.888 deg,    P =   0.034 deg,    R =   -0.993 deg
};
P[315]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350016.676  mm,    Y =   -45.842  mm,    Z =   -325804.897  mm,
    W =  -179.916 deg,    P =   0.118 deg,    R =   -0.989 deg
};
P[316]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350081.688  mm,    Y =   -119.111  mm,    Z =   -325804.811  mm,
    W =  -180.050 deg,    P =   0.045 deg,    R =   -0.998 deg
};
P[317]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349904.815  mm,    Y =   56.569  mm,    Z =   -325804.631  mm,
    W =  -179.900 deg,    P =   0.052 deg,    R =   -0.994 deg
};
P[318]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349888.228  mm,    Y =   40.212  mm,    Z =   -325804.193  mm,
    W =  -179.886 deg,    P =   0.122 deg,    R =   -0.986 deg
};
P[319]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349901.593  mm,    Y =   10.462  mm,    Z =   -325804.284  mm,
    W =  -179.989 deg,    P =   0.190 deg,    R =   -0.982 deg
};
P[320]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350105.763  mm,    Y =   -27.263  mm,    Z =   -325805.165  mm,
    W =  -179.974 deg,    P =   -0.072 deg,    R =   -0.997 deg
};
P[321]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349958.379  mm,    Y =   95.281  mm,    Z =   -325805.245  mm,
    W =  -179.895 deg,    P =   -0.083 deg,    R =   -0.991 deg
};
P[322]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350043.257  mm,    Y =   2.299  mm,    Z =   -325805.941  mm,
    W =  -179.930 deg,    P =   0.049 deg,    R =   -0.996 deg
};
P[323]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350119.160  mm,    Y =   -92.474  mm,    Z =   -325805.109  mm,
    W =  -180.080 deg,    P =   -0.018 deg,    R =   -0.997 deg
};
P[324]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350006.403  mm,    Y =   -11.587  mm,    Z =   -325805.931  mm,
    W =  -179.950 deg,    P =   0.098 deg,    R =   -0.994 deg
};
P[325]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350048.598  mm,    Y =   -54.992  mm,    Z =   -325805.508  mm,
    W =  -179.934 deg,    P =   0.049 deg,    R =   -0.997 deg
};
P[326]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349998.627  mm,    Y =   -6.088  mm,    Z =   -325805.881  mm,
    W =  -179.972 deg,    P =   0.092 deg,    R =   -0.995 deg
};
P[327]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349991.361  mm,    Y =   0.937  mm,    Z =   -325805.625  mm,
    W =  -179.985 deg,    P =   0.075 deg,    R =   -0.997 deg
};
P[328]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349984.084  mm,    Y =   7.931  mm,    Z =   -325805.315  mm,
    W =  -179.998 deg,    P =   0.057 deg,    R =   -0.998 deg
};
P[329]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349977.071  mm,    Y =   15.256  mm,    Z =   -325805.636  mm,
    W =  -180.008 deg,    P =   0.053 deg,    R =   -0.999 deg
};
P[330]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349969.985  mm,    Y =   22.503  mm,    Z =   -325805.807  mm,
    W =  -180.006 deg,    P =   0.041 deg,    R =   -0.999 deg
};
P[331]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349904.884  mm,    Y =   75.650  mm,    Z =   -325805.631  mm,
    W =  -179.877 deg,    P =   0.032 deg,    R =   -0.992 deg
};
P[332]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350004.476  mm,    Y =   -41.977  mm,    Z =   -325805.506  mm,
    W =  -179.920 deg,    P =   0.123 deg,    R =   -0.989 deg
};
P[333]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350073.990  mm,    Y =   -118.073  mm,    Z =   -325805.667  mm,
    W =  -180.024 deg,    P =   0.073 deg,    R =   -0.997 deg
};
P[334]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349996.232  mm,    Y =   -44.867  mm,    Z =   -325805.112  mm,
    W =  -179.932 deg,    P =   0.128 deg,    R =   -0.989 deg
};
P[335]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349897.187  mm,    Y =   53.734  mm,    Z =   -325805.278  mm,
    W =  -179.886 deg,    P =   0.085 deg,    R =   -0.990 deg
};
P[336]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349936.410  mm,    Y =   13.619  mm,    Z =   -325805.727  mm,
    W =  -180.011 deg,    P =   0.093 deg,    R =   -0.996 deg
};
P[337]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349930.898  mm,    Y =   12.719  mm,    Z =   -325805.464  mm,
    W =  -180.012 deg,    P =   0.118 deg,    R =   -0.993 deg
};
P[338]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349993.759  mm,    Y =   -66.037  mm,    Z =   -325805.677  mm,
    W =  -179.912 deg,    P =   0.179 deg,    R =   -0.980 deg
};
P[339]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349909.008  mm,    Y =   10.876  mm,    Z =   -325805.622  mm,
    W =  -179.990 deg,    P =   0.181 deg,    R =   -0.984 deg
};
P[340]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349882.764  mm,    Y =   30.349  mm,    Z =   -325806.072  mm,
    W =  -179.905 deg,    P =   0.153 deg,    R =   -0.984 deg
};
P[341]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349907.590  mm,    Y =   3.913  mm,    Z =   -325805.699  mm,
    W =  -180.009 deg,    P =   0.210 deg,    R =   -0.978 deg
};
P[342]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350112.301  mm,    Y =   -29.254  mm,    Z =   -325806.192  mm,
    W =  -179.981 deg,    P =   -0.091 deg,    R =   -0.996 deg
};
P[343]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349975.232  mm,    Y =   94.603  mm,    Z =   -325806.438  mm,
    W =  -179.932 deg,    P =   -0.126 deg,    R =   -0.990 deg
};
P[344]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350017.972  mm,    Y =   25.507  mm,    Z =   -325806.438  mm,
    W =  -179.976 deg,    P =   0.062 deg,    R =   -0.998 deg
};
P[345]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349922.929  mm,    Y =   101.804  mm,    Z =   -325806.286  mm,
    W =  -179.835 deg,    P =   -0.035 deg,    R =   -0.986 deg
};
P[346]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349915.038  mm,    Y =   96.534  mm,    Z =   -325806.854  mm,
    W =  -179.844 deg,    P =   -0.005 deg,    R =   -0.988 deg
};
P[347]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350015.706  mm,    Y =   -17.026  mm,    Z =   -325806.364  mm,
    W =  -179.934 deg,    P =   0.088 deg,    R =   -0.994 deg
};
P[348]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349907.186  mm,    Y =   86.361  mm,    Z =   -325806.936  mm,
    W =  -179.860 deg,    P =   0.025 deg,    R =   -0.990 deg
};
P[349]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349957.255  mm,    Y =   22.643  mm,    Z =   -325806.624  mm,
    W =  -180.001 deg,    P =   0.046 deg,    R =   -0.999 deg
};
P[350]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349953.051  mm,    Y =   19.985  mm,    Z =   -325806.553  mm,
    W =  -180.004 deg,    P =   0.052 deg,    R =   -0.999 deg
};
P[351]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349947.992  mm,    Y =   14.458  mm,    Z =   -325806.991  mm,
    W =  -180.010 deg,    P =   0.069 deg,    R =   -0.998 deg
};
P[352]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349898.131  mm,    Y =   63.507  mm,    Z =   -325806.453  mm,
    W =  -179.880 deg,    P =   0.060 deg,    R =   -0.991 deg
};
P[353]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349890.243  mm,    Y =   51.171  mm,    Z =   -325806.713  mm,
    W =  -179.883 deg,    P =   0.089 deg,    R =   -0.989 deg
};
P[354]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350032.258  mm,    Y =   -98.603  mm,    Z =   -325806.864  mm,
    W =  -179.935 deg,    P =   0.154 deg,    R =   -0.986 deg
};
P[355]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350023.941  mm,    Y =   -93.815  mm,    Z =   -325806.492  mm,
    W =  -179.921 deg,    P =   0.173 deg,    R =   -0.982 deg
};
P[356]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350015.920  mm,    Y =   -87.290  mm,    Z =   -325806.982  mm,
    W =  -179.914 deg,    P =   0.190 deg,    R =   -0.978 deg
};
P[357]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349917.341  mm,    Y =   12.085  mm,    Z =   -325806.360  mm,
    W =  -179.994 deg,    P =   0.164 deg,    R =   -0.986 deg
};
P[358]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350000.455  mm,    Y =   -74.236  mm,    Z =   -325806.806  mm,
    W =  -179.906 deg,    P =   0.199 deg,    R =   -0.975 deg
};
P[359]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349887.265  mm,    Y =   9.877  mm,    Z =   -325806.357  mm,
    W =  -179.970 deg,    P =   0.191 deg,    R =   -0.981 deg
};
P[360]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350129.245  mm,    Y =   -44.996  mm,    Z =   -325807.251  mm,
    W =  -180.068 deg,    P =   -0.092 deg,    R =   -0.993 deg
};
P[361]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349981.263  mm,    Y =   88.761  mm,    Z =   -325808.066  mm,
    W =  -179.951 deg,    P =   -0.123 deg,    R =   -0.991 deg
};
P[362]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349950.813  mm,    Y =   102.034  mm,    Z =   -325807.890  mm,
    W =  -179.868 deg,    P =   -0.088 deg,    R =   -0.987 deg
};
P[363]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350011.060  mm,    Y =   38.933  mm,    Z =   -325807.670  mm,
    W =  -179.992 deg,    P =   0.026 deg,    R =   -1.000 deg
};
P[364]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350006.343  mm,    Y =   43.364  mm,    Z =   -325807.400  mm,
    W =  -179.999 deg,    P =   0.015 deg,    R =   -1.000 deg
};
P[365]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349940.173  mm,    Y =   106.113  mm,    Z =   -325807.458  mm,
    W =  -179.846 deg,    P =   -0.075 deg,    R =   -0.985 deg
};
P[366]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350114.721  mm,    Y =   -100.490  mm,    Z =   -325807.810  mm,
    W =  -180.070 deg,    P =   -0.016 deg,    R =   -0.997 deg
};
P[367]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350023.392  mm,    Y =   -22.593  mm,    Z =   -325807.668  mm,
    W =  -179.928 deg,    P =   0.086 deg,    R =   -0.994 deg
};
P[368]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349970.490  mm,    Y =   8.398  mm,    Z =   -325807.460  mm,
    W =  -180.011 deg,    P =   0.065 deg,    R =   -0.998 deg
};
P[369]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349963.107  mm,    Y =   15.166  mm,    Z =   -325807.480  mm,
    W =  -180.007 deg,    P =   0.054 deg,    R =   -0.999 deg
};
P[370]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349967.577  mm,    Y =   4.673  mm,    Z =   -325807.453  mm,
    W =  -180.013 deg,    P =   0.068 deg,    R =   -0.998 deg
};
P[371]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349899.498  mm,    Y =   72.748  mm,    Z =   -325807.453  mm,
    W =  -179.870 deg,    P =   0.045 deg,    R =   -0.990 deg
};
P[372]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349940.962  mm,    Y =   6.715  mm,    Z =   -325807.602  mm,
    W =  -180.025 deg,    P =   0.099 deg,    R =   -0.995 deg
};
P[373]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349988.685  mm,    Y =   -47.181  mm,    Z =   -325807.339  mm,
    W =  -179.937 deg,    P =   0.123 deg,    R =   -0.990 deg
};
P[374]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349935.723  mm,    Y =   5.743  mm,    Z =   -325807.701  mm,
    W =  -180.019 deg,    P =   0.118 deg,    R =   -0.993 deg
};
P[375]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350040.680  mm,    Y =   -104.256  mm,    Z =   -325807.539  mm,
    W =  -179.944 deg,    P =   0.142 deg,    R =   -0.988 deg
};
P[376]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349988.847  mm,    Y =   -58.050  mm,    Z =   -325808.015  mm,
    W =  -179.918 deg,    P =   0.146 deg,    R =   -0.986 deg
};
P[377]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350008.350  mm,    Y =   -81.087  mm,    Z =   -325807.613  mm,
    W =  -179.907 deg,    P =   0.202 deg,    R =   -0.975 deg
};
P[378]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349912.927  mm,    Y =   4.381  mm,    Z =   -325807.326  mm,
    W =  -180.014 deg,    P =   0.201 deg,    R =   -0.979 deg
};
P[379]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349880.747  mm,    Y =   35.030  mm,    Z =   -325807.873  mm,
    W =  -179.887 deg,    P =   0.143 deg,    R =   -0.983 deg
};
P[380]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349881.008  mm,    Y =   17.753  mm,    Z =   -325807.522  mm,
    W =  -179.929 deg,    P =   0.180 deg,    R =   -0.981 deg
};
P[381]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350037.899  mm,    Y =   6.412  mm,    Z =   -325808.221  mm,
    W =  -179.934 deg,    P =   0.055 deg,    R =   -0.996 deg
};
P[382]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350031.037  mm,    Y =   12.249  mm,    Z =   -325808.736  mm,
    W =  -179.955 deg,    P =   0.053 deg,    R =   -0.998 deg
};
P[383]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349899.914  mm,    Y =   79.737  mm,    Z =   -325808.810  mm,
    W =  -179.855 deg,    P =   0.036 deg,    R =   -0.989 deg
};
P[384]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349969.792  mm,    Y =   1.424  mm,    Z =   -325808.974  mm,
    W =  -180.009 deg,    P =   0.069 deg,    R =   -0.998 deg
};
P[385]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349960.411  mm,    Y =   10.805  mm,    Z =   -325808.974  mm,
    W =  -180.014 deg,    P =   0.066 deg,    R =   -0.998 deg
};
P[386]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349963.050  mm,    Y =   0.566  mm,    Z =   -325808.599  mm,
    W =  -180.017 deg,    P =   0.081 deg,    R =   -0.997 deg
};
P[387]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349955.646  mm,    Y =   7.674  mm,    Z =   -325809.075  mm,
    W =  -180.018 deg,    P =   0.078 deg,    R =   -0.997 deg
};
P[388]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349892.240  mm,    Y =   70.955  mm,    Z =   -325808.835  mm,
    W =  -179.851 deg,    P =   0.070 deg,    R =   -0.986 deg
};
P[389]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349890.827  mm,    Y =   57.371  mm,    Z =   -325808.189  mm,
    W =  -179.868 deg,    P =   0.084 deg,    R =   -0.988 deg
};
P[390]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349904.306  mm,    Y =   0.938  mm,    Z =   -325808.338  mm,
    W =  -180.017 deg,    P =   0.214 deg,    R =   -0.977 deg
};
P[391]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349895.241  mm,    Y =   5.574  mm,    Z =   -325808.287  mm,
    W =  -180.000 deg,    P =   0.196 deg,    R =   -0.981 deg
};
P[392]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350127.266  mm,    Y =   -37.191  mm,    Z =   -325809.968  mm,
    W =  -180.039 deg,    P =   -0.112 deg,    R =   -0.993 deg
};
P[393]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349998.625  mm,    Y =   66.854  mm,    Z =   -325809.775  mm,
    W =  -180.004 deg,    P =   -0.072 deg,    R =   -0.997 deg
};
P[394]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350025.040  mm,    Y =   19.677  mm,    Z =   -325809.276  mm,
    W =  -179.962 deg,    P =   0.065 deg,    R =   -0.997 deg
};
P[395]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349931.313  mm,    Y =   110.110  mm,    Z =   -325809.292  mm,
    W =  -179.819 deg,    P =   -0.074 deg,    R =   -0.981 deg
};
P[396]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349924.018  mm,    Y =   108.625  mm,    Z =   -325809.284  mm,
    W =  -179.816 deg,    P =   -0.057 deg,    R =   -0.981 deg
};
P[397]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350035.241  mm,    Y =   -29.808  mm,    Z =   -325809.701  mm,
    W =  -179.920 deg,    P =   0.069 deg,    R =   -0.994 deg
};
P[398]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349908.694  mm,    Y =   94.566  mm,    Z =   -325809.383  mm,
    W =  -179.840 deg,    P =   0.012 deg,    R =   -0.987 deg
};
P[399]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350112.602  mm,    Y =   -111.159  mm,    Z =   -325810.070  mm,
    W =  -180.076 deg,    P =   -0.007 deg,    R =   -0.997 deg
};
P[400]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350036.736  mm,    Y =   -53.058  mm,    Z =   -325809.103  mm,
    W =  -179.927 deg,    P =   0.076 deg,    R =   -0.994 deg
};
P[401]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349893.364  mm,    Y =   76.907  mm,    Z =   -325809.706  mm,
    W =  -179.845 deg,    P =   0.053 deg,    R =   -0.986 deg
};
P[402]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349997.088  mm,    Y =   -37.551  mm,    Z =   -325809.501  mm,
    W =  -179.936 deg,    P =   0.119 deg,    R =   -0.991 deg
};
P[403]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349967.622  mm,    Y =   -7.327  mm,    Z =   -325809.623  mm,
    W =  -180.014 deg,    P =   0.082 deg,    R =   -0.997 deg
};
P[404]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349990.888  mm,    Y =   -41.278  mm,    Z =   -325809.201  mm,
    W =  -179.938 deg,    P =   0.119 deg,    R =   -0.991 deg
};
P[405]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349961.948  mm,    Y =   -13.770  mm,    Z =   -325809.419  mm,
    W =  -180.014 deg,    P =   0.096 deg,    R =   -0.995 deg
};
P[406]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349954.785  mm,    Y =   -6.599  mm,    Z =   -325809.589  mm,
    W =  -180.024 deg,    P =   0.096 deg,    R =   -0.995 deg
};
P[407]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349947.731  mm,    Y =   0.463  mm,    Z =   -325809.430  mm,
    W =  -180.027 deg,    P =   0.099 deg,    R =   -0.995 deg
};
P[408]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349968.821  mm,    Y =   -21.469  mm,    Z =   -325809.248  mm,
    W =  -180.002 deg,    P =   0.095 deg,    R =   -0.995 deg
};
P[409]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349982.592  mm,    Y =   -50.508  mm,    Z =   -325809.611  mm,
    W =  -179.939 deg,    P =   0.124 deg,    R =   -0.990 deg
};
P[410]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349925.706  mm,    Y =   6.623  mm,    Z =   -325809.710  mm,
    W =  -180.017 deg,    P =   0.162 deg,    R =   -0.987 deg
};
P[411]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349883.333  mm,    Y =   47.596  mm,    Z =   -325809.121  mm,
    W =  -179.870 deg,    P =   0.113 deg,    R =   -0.985 deg
};
P[412]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349877.008  mm,    Y =   25.482  mm,    Z =   -325809.518  mm,
    W =  -179.900 deg,    P =   0.170 deg,    R =   -0.980 deg
};
P[413]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349943.194  mm,    Y =   110.230  mm,    Z =   -325810.909  mm,
    W =  -179.838 deg,    P =   -0.099 deg,    R =   -0.982 deg
};
P[414]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349916.628  mm,    Y =   106.664  mm,    Z =   -325810.157  mm,
    W =  -179.808 deg,    P =   -0.043 deg,    R =   -0.980 deg
};
P[415]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350046.985  mm,    Y =   -40.296  mm,    Z =   -325810.361  mm,
    W =  -179.931 deg,    P =   0.056 deg,    R =   -0.996 deg
};
P[416]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350048.682  mm,    Y =   -49.201  mm,    Z =   -325810.618  mm,
    W =  -179.940 deg,    P =   0.048 deg,    R =   -0.997 deg
};
P[417]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349902.564  mm,    Y =   90.416  mm,    Z =   -325810.530  mm,
    W =  -179.844 deg,    P =   0.024 deg,    R =   -0.988 deg
};
P[418]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350042.206  mm,    Y =   -52.143  mm,    Z =   -325810.195  mm,
    W =  -179.931 deg,    P =   0.066 deg,    R =   -0.995 deg
};
P[419]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350020.588  mm,    Y =   -39.833  mm,    Z =   -325810.918  mm,
    W =  -179.917 deg,    P =   0.103 deg,    R =   -0.991 deg
};
P[420]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349974.762  mm,    Y =   -16.075  mm,    Z =   -325810.934  mm,
    W =  -179.998 deg,    P =   0.086 deg,    R =   -0.996 deg
};
P[421]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350070.714  mm,    Y =   -116.108  mm,    Z =   -325810.974  mm,
    W =  -180.020 deg,    P =   0.072 deg,    R =   -0.997 deg
};
P[422]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350053.034  mm,    Y =   -109.848  mm,    Z =   -325811.020  mm,
    W =  -179.966 deg,    P =   0.129 deg,    R =   -0.991 deg
};
P[423]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349937.383  mm,    Y =   -4.303  mm,    Z =   -325810.853  mm,
    W =  -180.028 deg,    P =   0.140 deg,    R =   -0.990 deg
};
P[424]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349933.483  mm,    Y =   0.146  mm,    Z =   -325810.589  mm,
    W =  -180.030 deg,    P =   0.148 deg,    R =   -0.989 deg
};
P[425]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349977.261  mm,    Y =   -46.188  mm,    Z =   -325811.005  mm,
    W =  -179.958 deg,    P =   0.122 deg,    R =   -0.992 deg
};
P[426]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350118.388  mm,    Y =   -26.806  mm,    Z =   -325811.289  mm,
    W =  -180.003 deg,    P =   -0.126 deg,    R =   -0.992 deg
};
P[427]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349986.291  mm,    Y =   86.503  mm,    Z =   -325811.555  mm,
    W =  -179.963 deg,    P =   -0.132 deg,    R =   -0.991 deg
};
P[428]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349909.909  mm,    Y =   103.063  mm,    Z =   -325811.361  mm,
    W =  -179.800 deg,    P =   -0.022 deg,    R =   -0.979 deg
};
P[429]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350041.301  mm,    Y =   -33.777  mm,    Z =   -325811.234  mm,
    W =  -179.922 deg,    P =   0.066 deg,    R =   -0.995 deg
};
P[430]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350027.960  mm,    Y =   -45.698  mm,    Z =   -325811.428  mm,
    W =  -179.918 deg,    P =   0.093 deg,    R =   -0.992 deg
};
P[431]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349978.036  mm,    Y =   3.753  mm,    Z =   -325811.594  mm,
    W =  -180.006 deg,    P =   0.066 deg,    R =   -0.998 deg
};
P[432]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350007.106  mm,    Y =   -36.363  mm,    Z =   -325811.134  mm,
    W =  -179.928 deg,    P =   0.119 deg,    R =   -0.990 deg
};
P[433]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349886.573  mm,    Y =   74.501  mm,    Z =   -325811.653  mm,
    W =  -179.836 deg,    P =   0.075 deg,    R =   -0.984 deg
};
P[434]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349981.705  mm,    Y =   -22.213  mm,    Z =   -325811.872  mm,
    W =  -179.977 deg,    P =   0.093 deg,    R =   -0.995 deg
};
P[435]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350061.528  mm,    Y =   -112.897  mm,    Z =   -325811.804  mm,
    W =  -179.998 deg,    P =   0.098 deg,    R =   -0.995 deg
};
P[436]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349883.143  mm,    Y =   53.449  mm,    Z =   -325811.656  mm,
    W =  -179.861 deg,    P =   0.105 deg,    R =   -0.985 deg
};
P[437]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349876.434  mm,    Y =   41.672  mm,    Z =   -325811.979  mm,
    W =  -179.866 deg,    P =   0.136 deg,    R =   -0.982 deg
};
P[438]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349994.317  mm,    Y =   79.652  mm,    Z =   -325812.623  mm,
    W =  -180.000 deg,    P =   -0.133 deg,    R =   -0.991 deg
};
P[439]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349962.978  mm,    Y =   103.104  mm,    Z =   -325812.379  mm,
    W =  -179.878 deg,    P =   -0.122 deg,    R =   -0.985 deg
};
P[440]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349955.617  mm,    Y =   106.322  mm,    Z =   -325812.918  mm,
    W =  -179.862 deg,    P =   -0.115 deg,    R =   -0.984 deg
};
P[441]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349925.653  mm,    Y =   114.621  mm,    Z =   -325812.738  mm,
    W =  -179.793 deg,    P =   -0.073 deg,    R =   -0.976 deg
};
P[442]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349918.722  mm,    Y =   112.624  mm,    Z =   -325812.953  mm,
    W =  -179.788 deg,    P =   -0.059 deg,    R =   -0.975 deg
};
P[443]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350118.233  mm,    Y =   -107.293  mm,    Z =   -325812.162  mm,
    W =  -180.077 deg,    P =   -0.014 deg,    R =   -0.997 deg
};
P[444]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349902.340  mm,    Y =   96.510  mm,    Z =   -325812.831  mm,
    W =  -179.812 deg,    P =   0.009 deg,    R =   -0.982 deg
};
P[445]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349989.518  mm,    Y =   -0.589  mm,    Z =   -325812.508  mm,
    W =  -179.989 deg,    P =   0.077 deg,    R =   -0.997 deg
};
P[446]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349893.617  mm,    Y =   86.532  mm,    Z =   -325812.256  mm,
    W =  -179.827 deg,    P =   0.042 deg,    R =   -0.984 deg
};
P[447]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350013.377  mm,    Y =   -35.453  mm,    Z =   -325812.611  mm,
    W =  -179.923 deg,    P =   0.112 deg,    R =   -0.991 deg
};
P[448]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349992.449  mm,    Y =   -32.712  mm,    Z =   -325812.157  mm,
    W =  -179.946 deg,    P =   0.109 deg,    R =   -0.993 deg
};
P[449]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349977.635  mm,    Y =   -27.227  mm,    Z =   -325812.412  mm,
    W =  -179.980 deg,    P =   0.093 deg,    R =   -0.995 deg
};
P[450]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349885.635  mm,    Y =   64.934  mm,    Z =   -325812.448  mm,
    W =  -179.848 deg,    P =   0.084 deg,    R =   -0.985 deg
};
P[451]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349976.448  mm,    Y =   -40.844  mm,    Z =   -325812.804  mm,
    W =  -179.966 deg,    P =   0.113 deg,    R =   -0.993 deg
};
P[452]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349962.663  mm,    Y =   -27.831  mm,    Z =   -325812.776  mm,
    W =  -180.005 deg,    P =   0.104 deg,    R =   -0.995 deg
};
P[453]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349941.002  mm,    Y =   -6.810  mm,    Z =   -325812.233  mm,
    W =  -180.034 deg,    P =   0.138 deg,    R =   -0.990 deg
};
P[454]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349933.325  mm,    Y =   -1.832  mm,    Z =   -325812.583  mm,
    W =  -180.030 deg,    P =   0.159 deg,    R =   -0.987 deg
};
P[455]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349992.342  mm,    Y =   -67.432  mm,    Z =   -325812.668  mm,
    W =  -179.913 deg,    P =   0.186 deg,    R =   -0.979 deg
};
P[456]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349985.798  mm,    Y =   -61.200  mm,    Z =   -325813.073  mm,
    W =  -179.922 deg,    P =   0.169 deg,    R =   -0.983 deg
};
P[457]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349917.806  mm,    Y =   1.201  mm,    Z =   -325812.904  mm,
    W =  -180.019 deg,    P =   0.202 deg,    R =   -0.979 deg
};
P[458]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349911.007  mm,    Y =   110.214  mm,    Z =   -325813.201  mm,
    W =  -179.783 deg,    P =   -0.041 deg,    R =   -0.975 deg
};
P[459]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350030.009  mm,    Y =   -30.484  mm,    Z =   -325813.679  mm,
    W =  -179.916 deg,    P =   0.081 deg,    R =   -0.993 deg
};
P[460]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350021.989  mm,    Y =   -24.517  mm,    Z =   -325813.975  mm,
    W =  -179.927 deg,    P =   0.087 deg,    R =   -0.994 deg
};
P[461]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349995.477  mm,    Y =   -11.133  mm,    Z =   -325813.887  mm,
    W =  -179.971 deg,    P =   0.093 deg,    R =   -0.995 deg
};
P[462]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349973.099  mm,    Y =   -3.670  mm,    Z =   -325813.529  mm,
    W =  -180.010 deg,    P =   0.079 deg,    R =   -0.997 deg
};
P[463]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349886.168  mm,    Y =   80.682  mm,    Z =   -325813.222  mm,
    W =  -179.817 deg,    P =   0.073 deg,    R =   -0.980 deg
};
P[464]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349984.539  mm,    Y =   -35.402  mm,    Z =   -325813.345  mm,
    W =  -179.960 deg,    P =   0.109 deg,    R =   -0.993 deg
};
P[465]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349948.187  mm,    Y =   -13.024  mm,    Z =   -325813.445  mm,
    W =  -180.030 deg,    P =   0.123 deg,    R =   -0.992 deg
};
P[466]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349927.051  mm,    Y =   1.453  mm,    Z =   -325813.706  mm,
    W =  -180.019 deg,    P =   0.165 deg,    R =   -0.986 deg
};
P[467]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350000.353  mm,    Y =   -74.486  mm,    Z =   -325813.243  mm,
    W =  -179.905 deg,    P =   0.193 deg,    R =   -0.977 deg
};
P[468]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349974.470  mm,    Y =   -49.110  mm,    Z =   -325813.757  mm,
    W =  -179.960 deg,    P =   0.137 deg,    R =   -0.990 deg
};
P[469]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349978.978  mm,    Y =   -54.136  mm,    Z =   -325813.386  mm,
    W =  -179.941 deg,    P =   0.141 deg,    R =   -0.988 deg
};
P[470]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349874.138  mm,    Y =   26.910  mm,    Z =   -325814.010  mm,
    W =  -179.901 deg,    P =   0.168 deg,    R =   -0.981 deg
};
P[471]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349884.733  mm,    Y =   6.960  mm,    Z =   -325813.874  mm,
    W =  -179.967 deg,    P =   0.194 deg,    R =   -0.980 deg
};
P[472]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350054.698  mm,    Y =   7.474  mm,    Z =   -325814.134  mm,
    W =  -179.916 deg,    P =   0.004 deg,    R =   -0.996 deg
};
P[473]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350015.301  mm,    Y =   45.184  mm,    Z =   -325815.051  mm,
    W =  -179.994 deg,    P =   -0.000 deg,    R =   -1.000 deg
};
P[474]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349946.689  mm,    Y =   113.280  mm,    Z =   -325814.253  mm,
    W =  -179.841 deg,    P =   -0.116 deg,    R =   -0.980 deg
};
P[475]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349937.104  mm,    Y =   115.867  mm,    Z =   -325814.477  mm,
    W =  -179.811 deg,    P =   -0.097 deg,    R =   -0.977 deg
};
P[476]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349904.159  mm,    Y =   107.002  mm,    Z =   -325814.718  mm,
    W =  -179.774 deg,    P =   -0.027 deg,    R =   -0.974 deg
};
P[477]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350016.514  mm,    Y =   -17.123  mm,    Z =   -325814.645  mm,
    W =  -179.934 deg,    P =   0.091 deg,    R =   -0.994 deg
};
P[478]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349896.067  mm,    Y =   93.366  mm,    Z =   -325814.128  mm,
    W =  -179.815 deg,    P =   0.019 deg,    R =   -0.982 deg
};
P[479]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350001.096  mm,    Y =   -32.006  mm,    Z =   -325814.241  mm,
    W =  -179.934 deg,    P =   0.115 deg,    R =   -0.991 deg
};
P[480]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349986.871  mm,    Y =   -18.621  mm,    Z =   -325814.584  mm,
    W =  -179.973 deg,    P =   0.088 deg,    R =   -0.996 deg
};
P[481]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349992.651  mm,    Y =   -25.509  mm,    Z =   -325815.036  mm,
    W =  -179.957 deg,    P =   0.100 deg,    R =   -0.994 deg
};
P[482]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349987.276  mm,    Y =   -29.903  mm,    Z =   -325814.556  mm,
    W =  -179.955 deg,    P =   0.100 deg,    R =   -0.994 deg
};
P[483]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349882.026  mm,    Y =   70.349  mm,    Z =   -325814.600  mm,
    W =  -179.832 deg,    P =   0.083 deg,    R =   -0.982 deg
};
P[484]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350049.739  mm,    Y =   -108.172  mm,    Z =   -325814.871  mm,
    W =  -179.956 deg,    P =   0.127 deg,    R =   -0.991 deg
};
P[485]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349970.534  mm,    Y =   -34.609  mm,    Z =   -325814.384  mm,
    W =  -179.981 deg,    P =   0.104 deg,    R =   -0.994 deg
};
P[486]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349955.464  mm,    Y =   -19.984  mm,    Z =   -325814.126  mm,
    W =  -180.021 deg,    P =   0.108 deg,    R =   -0.994 deg
};
P[487]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350023.608  mm,    Y =   -94.104  mm,    Z =   -325814.606  mm,
    W =  -179.919 deg,    P =   0.180 deg,    R =   -0.980 deg
};
P[488]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350016.379  mm,    Y =   -87.526  mm,    Z =   -325814.143  mm,
    W =  -179.912 deg,    P =   0.191 deg,    R =   -0.978 deg
};
P[489]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349877.436  mm,    Y =   18.500  mm,    Z =   -325815.003  mm,
    W =  -179.923 deg,    P =   0.183 deg,    R =   -0.980 deg
};
P[490]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349889.039  mm,    Y =   4.321  mm,    Z =   -325814.461  mm,
    W =  -179.994 deg,    P =   0.202 deg,    R =   -0.979 deg
};
P[491]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349881.235  mm,    Y =   12.124  mm,    Z =   -325814.461  mm,
    W =  -179.949 deg,    P =   0.190 deg,    R =   -0.980 deg
};
P[492]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350026.477  mm,    Y =   29.343  mm,    Z =   -325815.672  mm,
    W =  -179.975 deg,    P =   0.030 deg,    R =   -0.999 deg
};
P[493]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350032.650  mm,    Y =   20.417  mm,    Z =   -325815.575  mm,
    W =  -179.957 deg,    P =   0.052 deg,    R =   -0.998 deg
};
P[494]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350046.725  mm,    Y =   -45.221  mm,    Z =   -325815.098  mm,
    W =  -179.933 deg,    P =   0.056 deg,    R =   -0.996 deg
};
P[495]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350008.554  mm,    Y =   -12.811  mm,    Z =   -325815.342  mm,
    W =  -179.947 deg,    P =   0.094 deg,    R =   -0.994 deg
};
P[496]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350038.655  mm,    Y =   -47.513  mm,    Z =   -325815.980  mm,
    W =  -179.928 deg,    P =   0.065 deg,    R =   -0.995 deg
};
P[497]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350025.345  mm,    Y =   -34.600  mm,    Z =   -325815.920  mm,
    W =  -179.915 deg,    P =   0.089 deg,    R =   -0.992 deg
};
P[498]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349888.302  mm,    Y =   91.409  mm,    Z =   -325815.122  mm,
    W =  -179.800 deg,    P =   0.040 deg,    R =   -0.979 deg
};
P[499]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349978.639  mm,    Y =   -12.187  mm,    Z =   -325815.522  mm,
    W =  -179.996 deg,    P =   0.082 deg,    R =   -0.997 deg
};
P[500]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350082.740  mm,    Y =   -118.121  mm,    Z =   -325815.986  mm,
    W =  -180.041 deg,    P =   0.041 deg,    R =   -0.998 deg
};
P[501]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350041.453  mm,    Y =   -104.081  mm,    Z =   -325815.441  mm,
    W =  -179.943 deg,    P =   0.141 deg,    R =   -0.988 deg
};
P[502]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349878.566  mm,    Y =   58.367  mm,    Z =   -325815.633  mm,
    W =  -179.841 deg,    P =   0.103 deg,    R =   -0.982 deg
};
P[503]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350032.991  mm,    Y =   -99.537  mm,    Z =   -325816.017  mm,
    W =  -179.937 deg,    P =   0.151 deg,    R =   -0.987 deg
};
P[504]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349872.123  mm,    Y =   46.935  mm,    Z =   -325815.370  mm,
    W =  -179.858 deg,    P =   0.130 deg,    R =   -0.981 deg
};
P[505]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349896.774  mm,    Y =   2.975  mm,    Z =   -325815.159  mm,
    W =  -180.011 deg,    P =   0.206 deg,    R =   -0.978 deg
};
P[506]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350007.468  mm,    Y =   57.084  mm,    Z =   -325816.353  mm,
    W =  -180.012 deg,    P =   -0.037 deg,    R =   -0.999 deg
};
P[507]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349941.877  mm,    Y =   117.845  mm,    Z =   -325816.847  mm,
    W =  -179.818 deg,    P =   -0.120 deg,    R =   -0.976 deg
};
P[508]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350024.360  mm,    Y =   34.865  mm,    Z =   -325816.374  mm,
    W =  -179.983 deg,    P =   0.016 deg,    R =   -1.000 deg
};
P[509]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350029.969  mm,    Y =   25.330  mm,    Z =   -325816.435  mm,
    W =  -179.971 deg,    P =   0.041 deg,    R =   -0.999 deg
};
P[510]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349920.868  mm,    Y =   119.250  mm,    Z =   -325817.044  mm,
    W =  -179.771 deg,    P =   -0.082 deg,    R =   -0.970 deg
};
P[511]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349904.443  mm,    Y =   113.263  mm,    Z =   -325816.536  mm,
    W =  -179.751 deg,    P =   -0.043 deg,    R =   -0.968 deg
};
P[512]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349896.833  mm,    Y =   103.583  mm,    Z =   -325817.086  mm,
    W =  -179.767 deg,    P =   -0.007 deg,    R =   -0.972 deg
};
P[513]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349993.416  mm,    Y =   -9.199  mm,    Z =   -325816.849  mm,
    W =  -179.976 deg,    P =   0.086 deg,    R =   -0.996 deg
};
P[514]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349879.124  mm,    Y =   74.494  mm,    Z =   -325816.681  mm,
    W =  -179.813 deg,    P =   0.083 deg,    R =   -0.979 deg
};
P[515]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349922.578  mm,    Y =   -1.035  mm,    Z =   -325816.890  mm,
    W =  -180.029 deg,    P =   0.193 deg,    R =   -0.981 deg
};
P[516]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349870.209  mm,    Y =   52.047  mm,    Z =   -325816.895  mm,
    W =  -179.837 deg,    P =   0.123 deg,    R =   -0.979 deg
};
P[517]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349870.954  mm,    Y =   35.756  mm,    Z =   -325816.863  mm,
    W =  -179.868 deg,    P =   0.152 deg,    R =   -0.980 deg
};
P[518]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349905.038  mm,    Y =   -0.933  mm,    Z =   -325816.435  mm,
    W =  -180.020 deg,    P =   0.213 deg,    R =   -0.977 deg
};
P[519]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350106.817  mm,    Y =   -14.152  mm,    Z =   -325817.111  mm,
    W =  -179.936 deg,    P =   -0.153 deg,    R =   -0.986 deg
};
P[520]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349992.919  mm,    Y =   89.525  mm,    Z =   -325817.837  mm,
    W =  -179.965 deg,    P =   -0.167 deg,    R =   -0.985 deg
};
P[521]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350125.460  mm,    Y =   -94.135  mm,    Z =   -325817.334  mm,
    W =  -180.091 deg,    P =   -0.034 deg,    R =   -0.995 deg
};
P[522]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349911.106  mm,    Y =   117.386  mm,    Z =   -325817.091  mm,
    W =  -179.743 deg,    P =   -0.058 deg,    R =   -0.965 deg
};
P[523]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350036.816  mm,    Y =   -32.861  mm,    Z =   -325817.335  mm,
    W =  -179.918 deg,    P =   0.065 deg,    R =   -0.995 deg
};
P[524]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349889.431  mm,    Y =   98.027  mm,    Z =   -325817.941  mm,
    W =  -179.768 deg,    P =   0.020 deg,    R =   -0.973 deg
};
P[525]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349872.619  mm,    Y =   65.748  mm,    Z =   -325817.820  mm,
    W =  -179.817 deg,    P =   0.100 deg,    R =   -0.978 deg
};
P[526]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349970.327  mm,    Y =   -48.351  mm,    Z =   -325817.886  mm,
    W =  -179.965 deg,    P =   0.142 deg,    R =   -0.989 deg
};
P[527]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349927.957  mm,    Y =   -5.492  mm,    Z =   -325817.834  mm,
    W =  -180.032 deg,    P =   0.193 deg,    R =   -0.981 deg
};
P[528]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349911.939  mm,    Y =   -3.518  mm,    Z =   -325818.007  mm,
    W =  -180.030 deg,    P =   0.223 deg,    R =   -0.974 deg
};
P[529]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349988.933  mm,    Y =   96.295  mm,    Z =   -325818.489  mm,
    W =  -179.954 deg,    P =   -0.177 deg,    R =   -0.983 deg
};
P[530]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349968.677  mm,    Y =   108.798  mm,    Z =   -325818.289  mm,
    W =  -179.876 deg,    P =   -0.161 deg,    R =   -0.979 deg
};
P[531]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350045.395  mm,    Y =   14.486  mm,    Z =   -325818.676  mm,
    W =  -179.936 deg,    P =   0.025 deg,    R =   -0.998 deg
};
P[532]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350030.597  mm,    Y =   28.217  mm,    Z =   -325818.511  mm,
    W =  -179.972 deg,    P =   0.027 deg,    R =   -0.999 deg
};
P[533]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349927.319  mm,    Y =   121.756  mm,    Z =   -325818.381  mm,
    W =  -179.772 deg,    P =   -0.092 deg,    R =   -0.969 deg
};
P[534]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349897.643  mm,    Y =   109.189  mm,    Z =   -325818.395  mm,
    W =  -179.752 deg,    P =   -0.023 deg,    R =   -0.969 deg
};
P[535]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350033.508  mm,    Y =   -41.662  mm,    Z =   -325818.369  mm,
    W =  -179.919 deg,    P =   0.077 deg,    R =   -0.994 deg
};
P[536]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350017.779  mm,    Y =   -28.740  mm,    Z =   -325818.490  mm,
    W =  -179.923 deg,    P =   0.100 deg,    R =   -0.992 deg
};
P[537]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349982.453  mm,    Y =   2.520  mm,    Z =   -325818.363  mm,
    W =  -180.001 deg,    P =   0.068 deg,    R =   -0.998 deg
};
P[538]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349881.106  mm,    Y =   87.279  mm,    Z =   -325818.091  mm,
    W =  -179.790 deg,    P =   0.070 deg,    R =   -0.975 deg
};
P[539]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349874.095  mm,    Y =   72.046  mm,    Z =   -325818.400  mm,
    W =  -179.810 deg,    P =   0.094 deg,    R =   -0.977 deg
};
P[540]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349865.183  mm,    Y =   58.739  mm,    Z =   -325818.929  mm,
    W =  -179.817 deg,    P =   0.122 deg,    R =   -0.975 deg
};
P[541]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349964.255  mm,    Y =   -40.892  mm,    Z =   -325818.807  mm,
    W =  -179.989 deg,    P =   0.134 deg,    R =   -0.991 deg
};
P[542]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349977.188  mm,    Y =   -55.981  mm,    Z =   -325818.975  mm,
    W =  -179.944 deg,    P =   0.156 deg,    R =   -0.986 deg
};
P[543]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349868.598  mm,    Y =   43.230  mm,    Z =   -325818.519  mm,
    W =  -179.860 deg,    P =   0.137 deg,    R =   -0.981 deg
};
P[544]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349984.347  mm,    Y =   105.758  mm,    Z =   -325819.770  mm,
    W =  -179.915 deg,    P =   -0.206 deg,    R =   -0.975 deg
};
P[545]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350003.542  mm,    Y =   78.508  mm,    Z =   -325819.967  mm,
    W =  -180.010 deg,    P =   -0.147 deg,    R =   -0.989 deg
};
P[546]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350142.789  mm,    Y =   -65.394  mm,    Z =   -325819.455  mm,
    W =  -180.135 deg,    P =   -0.108 deg,    R =   -0.985 deg
};
P[547]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349959.822  mm,    Y =   112.883  mm,    Z =   -325819.327  mm,
    W =  -179.844 deg,    P =   -0.140 deg,    R =   -0.978 deg
};
P[548]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349989.138  mm,    Y =   -0.598  mm,    Z =   -325820.067  mm,
    W =  -179.988 deg,    P =   0.078 deg,    R =   -0.997 deg
};
P[549]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350001.848  mm,    Y =   -14.846  mm,    Z =   -325819.699  mm,
    W =  -179.955 deg,    P =   0.094 deg,    R =   -0.995 deg
};
P[550]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350004.199  mm,    Y =   -26.278  mm,    Z =   -325820.044  mm,
    W =  -179.932 deg,    P =   0.110 deg,    R =   -0.992 deg
};
P[551]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349999.725  mm,    Y =   -22.061  mm,    Z =   -325819.999  mm,
    W =  -179.953 deg,    P =   0.104 deg,    R =   -0.993 deg
};
P[552]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349988.520  mm,    Y =   -11.286  mm,    Z =   -325819.169  mm,
    W =  -179.982 deg,    P =   0.088 deg,    R =   -0.996 deg
};
P[553]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350072.236  mm,    Y =   -115.037  mm,    Z =   -325819.229  mm,
    W =  -180.020 deg,    P =   0.067 deg,    R =   -0.998 deg
};
P[554]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349873.844  mm,    Y =   81.366  mm,    Z =   -325819.759  mm,
    W =  -179.782 deg,    P =   0.079 deg,    R =   -0.973 deg
};
P[555]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349867.091  mm,    Y =   70.261  mm,    Z =   -325819.851  mm,
    W =  -179.798 deg,    P =   0.113 deg,    R =   -0.973 deg
};
P[556]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350007.933  mm,    Y =   -81.223  mm,    Z =   -325819.839  mm,
    W =  -179.904 deg,    P =   0.204 deg,    R =   -0.974 deg
};
P[557]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349943.388  mm,    Y =   -18.978  mm,    Z =   -325819.840  mm,
    W =  -180.037 deg,    P =   0.150 deg,    R =   -0.988 deg
};
P[558]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349935.629  mm,    Y =   -11.981  mm,    Z =   -325819.374  mm,
    W =  -180.036 deg,    P =   0.172 deg,    R =   -0.984 deg
};
P[559]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349984.430  mm,    Y =   -62.763  mm,    Z =   -325819.579  mm,
    W =  -179.920 deg,    P =   0.172 deg,    R =   -0.982 deg
};
P[560]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349915.210  mm,    Y =   123.350  mm,    Z =   -325821.028  mm,
    W =  -179.736 deg,    P =   -0.078 deg,    R =   -0.961 deg
};
P[561]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349890.249  mm,    Y =   106.416  mm,    Z =   -325820.923  mm,
    W =  -179.740 deg,    P =   -0.003 deg,    R =   -0.966 deg
};
P[562]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349979.608  mm,    Y =   -1.276  mm,    Z =   -325820.644  mm,
    W =  -180.003 deg,    P =   0.071 deg,    R =   -0.997 deg
};
P[563]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349881.350  mm,    Y =   93.340  mm,    Z =   -325820.502  mm,
    W =  -179.762 deg,    P =   0.056 deg,    R =   -0.970 deg
};
P[564]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350078.820  mm,    Y =   -116.825  mm,    Z =   -325820.371  mm,
    W =  -180.020 deg,    P =   0.040 deg,    R =   -0.999 deg
};
P[565]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350023.438  mm,    Y =   -93.753  mm,    Z =   -325820.563  mm,
    W =  -179.915 deg,    P =   0.184 deg,    R =   -0.979 deg
};
P[566]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350015.888  mm,    Y =   -87.322  mm,    Z =   -325820.136  mm,
    W =  -179.904 deg,    P =   0.197 deg,    R =   -0.976 deg
};
P[567]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349958.032  mm,    Y =   -32.935  mm,    Z =   -325821.067  mm,
    W =  -180.010 deg,    P =   0.126 deg,    R =   -0.992 deg
};
P[568]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349992.563  mm,    Y =   -68.707  mm,    Z =   -325820.751  mm,
    W =  -179.910 deg,    P =   0.186 deg,    R =   -0.978 deg
};
P[569]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349878.591  mm,    Y =   15.472  mm,    Z =   -325820.539  mm,
    W =  -179.928 deg,    P =   0.186 deg,    R =   -0.980 deg
};
P[570]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349984.967  mm,    Y =   107.366  mm,    Z =   -325821.764  mm,
    W =  -179.909 deg,    P =   -0.235 deg,    R =   -0.968 deg
};
P[571]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350007.948  mm,    Y =   72.065  mm,    Z =   -325821.866  mm,
    W =  -180.018 deg,    P =   -0.124 deg,    R =   -0.992 deg
};
P[572]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350010.431  mm,    Y =   62.031  mm,    Z =   -325821.194  mm,
    W =  -180.021 deg,    P =   -0.073 deg,    R =   -0.997 deg
};
P[573]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350058.771  mm,    Y =   12.814  mm,    Z =   -325821.638  mm,
    W =  -179.916 deg,    P =   -0.023 deg,    R =   -0.996 deg
};
P[574]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350015.674  mm,    Y =   54.008  mm,    Z =   -325821.139  mm,
    W =  -180.015 deg,    P =   -0.049 deg,    R =   -0.999 deg
};
P[575]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349922.199  mm,    Y =   125.253  mm,    Z =   -325821.648  mm,
    W =  -179.741 deg,    P =   -0.094 deg,    R =   -0.961 deg
};
P[576]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350129.459  mm,    Y =   -93.472  mm,    Z =   -325821.999  mm,
    W =  -180.093 deg,    P =   -0.039 deg,    R =   -0.995 deg
};
P[577]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349899.311  mm,    Y =   119.016  mm,    Z =   -325821.131  mm,
    W =  -179.720 deg,    P =   -0.048 deg,    R =   -0.959 deg
};
P[578]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350009.322  mm,    Y =   -25.548  mm,    Z =   -325821.713  mm,
    W =  -179.933 deg,    P =   0.105 deg,    R =   -0.992 deg
};
P[579]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350063.834  mm,    Y =   -111.976  mm,    Z =   -325821.775  mm,
    W =  -179.999 deg,    P =   0.079 deg,    R =   -0.997 deg
};
P[580]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349866.919  mm,    Y =   76.019  mm,    Z =   -325821.713  mm,
    W =  -179.777 deg,    P =   0.098 deg,    R =   -0.970 deg
};
P[581]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350030.741  mm,    Y =   -98.501  mm,    Z =   -325821.364  mm,
    W =  -179.930 deg,    P =   0.163 deg,    R =   -0.984 deg
};
P[582]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350000.322  mm,    Y =   -74.763  mm,    Z =   -325821.115  mm,
    W =  -179.905 deg,    P =   0.201 deg,    R =   -0.975 deg
};
P[583]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349873.231  mm,    Y =   24.270  mm,    Z =   -325821.823  mm,
    W =  -179.899 deg,    P =   0.170 deg,    R =   -0.980 deg
};
P[584]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349891.996  mm,    Y =   0.923  mm,    Z =   -325821.716  mm,
    W =  -180.006 deg,    P =   0.200 deg,    R =   -0.980 deg
};
P[585]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349883.415  mm,    Y =   6.574  mm,    Z =   -325821.745  mm,
    W =  -179.970 deg,    P =   0.202 deg,    R =   -0.979 deg
};
P[586]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350133.145  mm,    Y =   -23.134  mm,    Z =   -325822.481  mm,
    W =  -180.022 deg,    P =   -0.207 deg,    R =   -0.978 deg
};
P[587]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350118.723  mm,    Y =   -15.140  mm,    Z =   -325822.632  mm,
    W =  -179.965 deg,    P =   -0.187 deg,    R =   -0.982 deg
};
P[588]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349965.910  mm,    Y =   113.835  mm,    Z =   -325822.249  mm,
    W =  -179.857 deg,    P =   -0.170 deg,    R =   -0.975 deg
};
P[589]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350146.028  mm,    Y =   -66.543  mm,    Z =   -325822.633  mm,
    W =  -180.191 deg,    P =   -0.127 deg,    R =   -0.973 deg
};
P[590]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349954.770  mm,    Y =   120.032  mm,    Z =   -325822.351  mm,
    W =  -179.828 deg,    P =   -0.158 deg,    R =   -0.972 deg
};
P[591]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349944.558  mm,    Y =   124.284  mm,    Z =   -325822.604  mm,
    W =  -179.803 deg,    P =   -0.152 deg,    R =   -0.969 deg
};
P[592]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350029.343  mm,    Y =   38.743  mm,    Z =   -325822.811  mm,
    W =  -179.983 deg,    P =   -0.004 deg,    R =   -1.000 deg
};
P[593]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350046.324  mm,    Y =   -39.454  mm,    Z =   -325823.061  mm,
    W =  -179.929 deg,    P =   0.055 deg,    R =   -0.996 deg
};
P[594]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349892.203  mm,    Y =   113.977  mm,    Z =   -325822.975  mm,
    W =  -179.716 deg,    P =   -0.017 deg,    R =   -0.959 deg
};
P[595]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350040.545  mm,    Y =   -35.031  mm,    Z =   -325822.623  mm,
    W =  -179.921 deg,    P =   0.067 deg,    R =   -0.995 deg
};
P[596]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350019.051  mm,    Y =   -20.832  mm,    Z =   -325822.606  mm,
    W =  -179.927 deg,    P =   0.087 deg,    R =   -0.994 deg
};
P[597]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350011.681  mm,    Y =   -13.462  mm,    Z =   -325822.606  mm,
    W =  -179.942 deg,    P =   0.088 deg,    R =   -0.994 deg
};
P[598]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349884.875  mm,    Y =   103.946  mm,    Z =   -325822.614  mm,
    W =  -179.727 deg,    P =   0.017 deg,    R =   -0.962 deg
};
P[599]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349984.013  mm,    Y =   -5.433  mm,    Z =   -325822.628  mm,
    W =  -179.995 deg,    P =   0.080 deg,    R =   -0.997 deg
};
P[600]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349951.488  mm,    Y =   -25.148  mm,    Z =   -325822.304  mm,
    W =  -180.026 deg,    P =   0.135 deg,    R =   -0.991 deg
};
P[601]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349869.824  mm,    Y =   30.744  mm,    Z =   -325822.227  mm,
    W =  -179.884 deg,    P =   0.169 deg,    R =   -0.979 deg
};
P[602]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350125.417  mm,    Y =   -16.478  mm,    Z =   -325824.017  mm,
    W =  -180.001 deg,    P =   -0.201 deg,    R =   -0.980 deg
};
P[603]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349992.315  mm,    Y =   100.177  mm,    Z =   -325823.403  mm,
    W =  -179.943 deg,    P =   -0.221 deg,    R =   -0.974 deg
};
P[604]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350023.081  mm,    Y =   49.692  mm,    Z =   -325824.022  mm,
    W =  -179.995 deg,    P =   -0.027 deg,    R =   -1.000 deg
};
P[605]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350050.453  mm,    Y =   17.650  mm,    Z =   -325823.891  mm,
    W =  -179.933 deg,    P =   -0.009 deg,    R =   -0.998 deg
};
P[606]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350035.448  mm,    Y =   30.033  mm,    Z =   -325823.224  mm,
    W =  -179.968 deg,    P =   0.012 deg,    R =   -0.999 deg
};
P[607]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350042.138  mm,    Y =   22.481  mm,    Z =   -325823.237  mm,
    W =  -179.951 deg,    P =   0.010 deg,    R =   -0.999 deg
};
P[608]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349930.627  mm,    Y =   128.181  mm,    Z =   -325823.608  mm,
    W =  -179.753 deg,    P =   -0.130 deg,    R =   -0.960 deg
};
P[609]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350016.289  mm,    Y =   -16.237  mm,    Z =   -325823.238  mm,
    W =  -179.935 deg,    P =   0.090 deg,    R =   -0.994 deg
};
P[610]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350017.799  mm,    Y =   -22.925  mm,    Z =   -325823.864  mm,
    W =  -179.927 deg,    P =   0.097 deg,    R =   -0.993 deg
};
P[611]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349868.910  mm,    Y =   87.096  mm,    Z =   -325823.676  mm,
    W =  -179.744 deg,    P =   0.078 deg,    R =   -0.963 deg
};
P[612]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350058.938  mm,    Y =   -110.413  mm,    Z =   -325823.623  mm,
    W =  -179.973 deg,    P =   0.099 deg,    R =   -0.995 deg
};
P[613]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349861.262  mm,    Y =   66.016  mm,    Z =   -325823.108  mm,
    W =  -179.794 deg,    P =   0.120 deg,    R =   -0.971 deg
};
P[614]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349865.019  mm,    Y =   45.314  mm,    Z =   -325823.669  mm,
    W =  -179.835 deg,    P =   0.142 deg,    R =   -0.976 deg
};
P[615]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349915.957  mm,    Y =   -6.201  mm,    Z =   -325823.127  mm,
    W =  -180.032 deg,    P =   0.225 deg,    R =   -0.974 deg
};
P[616]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349867.494  mm,    Y =   37.755  mm,    Z =   -325823.299  mm,
    W =  -179.865 deg,    P =   0.155 deg,    R =   -0.979 deg
};
P[617]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349906.293  mm,    Y =   -7.963  mm,    Z =   -325823.919  mm,
    W =  -180.037 deg,    P =   0.228 deg,    R =   -0.973 deg
};
P[618]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349901.341  mm,    Y =   -4.008  mm,    Z =   -325823.613  mm,
    W =  -180.022 deg,    P =   0.213 deg,    R =   -0.977 deg
};
P[619]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350110.906  mm,    Y =   -8.229  mm,    Z =   -325824.106  mm,
    W =  -179.929 deg,    P =   -0.177 deg,    R =   -0.982 deg
};
P[620]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349999.503  mm,    Y =   93.684  mm,    Z =   -325825.029  mm,
    W =  -179.977 deg,    P =   -0.215 deg,    R =   -0.976 deg
};
P[621]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349974.778  mm,    Y =   114.918  mm,    Z =   -325825.020  mm,
    W =  -179.860 deg,    P =   -0.204 deg,    R =   -0.969 deg
};
P[622]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349955.944  mm,    Y =   123.329  mm,    Z =   -325824.975  mm,
    W =  -179.824 deg,    P =   -0.179 deg,    R =   -0.968 deg
};
P[623]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350131.724  mm,    Y =   -95.376  mm,    Z =   -325824.978  mm,
    W =  -180.135 deg,    P =   -0.056 deg,    R =   -0.989 deg
};
P[624]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349907.698  mm,    Y =   128.251  mm,    Z =   -325825.029  mm,
    W =  -179.706 deg,    P =   -0.079 deg,    R =   -0.953 deg
};
P[625]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349900.539  mm,    Y =   125.055  mm,    Z =   -325824.203  mm,
    W =  -179.704 deg,    P =   -0.065 deg,    R =   -0.953 deg
};
P[626]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349876.884  mm,    Y =   98.338  mm,    Z =   -325824.990  mm,
    W =  -179.721 deg,    P =   0.046 deg,    R =   -0.959 deg
};
P[627]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350052.347  mm,    Y =   -108.073  mm,    Z =   -325824.414  mm,
    W =  -179.957 deg,    P =   0.121 deg,    R =   -0.992 deg
};
P[628]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350147.855  mm,    Y =   -58.641  mm,    Z =   -325825.204  mm,
    W =  -180.216 deg,    P =   -0.165 deg,    R =   -0.962 deg
};
P[629]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350014.548  mm,    Y =   64.004  mm,    Z =   -325826.002  mm,
    W =  -180.026 deg,    P =   -0.101 deg,    R =   -0.995 deg
};
P[630]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349936.249  mm,    Y =   129.830  mm,    Z =   -325825.405  mm,
    W =  -179.755 deg,    P =   -0.145 deg,    R =   -0.959 deg
};
P[631]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350008.500  mm,    Y =   -14.114  mm,    Z =   -325825.708  mm,
    W =  -179.947 deg,    P =   0.095 deg,    R =   -0.994 deg
};
P[632]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349883.725  mm,    Y =   109.512  mm,    Z =   -325825.366  mm,
    W =  -179.695 deg,    P =   0.007 deg,    R =   -0.952 deg
};
P[633]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349987.818  mm,    Y =   -0.891  mm,    Z =   -325825.719  mm,
    W =  -179.992 deg,    P =   0.076 deg,    R =   -0.997 deg
};
P[634]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350043.094  mm,    Y =   -103.717  mm,    Z =   -325825.153  mm,
    W =  -179.943 deg,    P =   0.138 deg,    R =   -0.989 deg
};
P[635]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349923.553  mm,    Y =   -8.254  mm,    Z =   -325825.947  mm,
    W =  -180.038 deg,    P =   0.211 deg,    R =   -0.977 deg
};
P[636]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349861.193  mm,    Y =   53.280  mm,    Z =   -325825.738  mm,
    W =  -179.815 deg,    P =   0.139 deg,    R =   -0.973 deg
};
P[637]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349958.979  mm,    Y =   -45.663  mm,    Z =   -325825.647  mm,
    W =  -179.997 deg,    P =   0.153 deg,    R =   -0.988 deg
};
P[638]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350146.694  mm,    Y =   -46.581  mm,    Z =   -325826.203  mm,
    W =  -180.190 deg,    P =   -0.200 deg,    R =   -0.961 deg
};
P[639]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350149.067  mm,    Y =   -50.934  mm,    Z =   -325826.947  mm,
    W =  -180.214 deg,    P =   -0.216 deg,    R =   -0.952 deg
};
P[640]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349993.627  mm,    Y =   104.053  mm,    Z =   -325826.548  mm,
    W =  -179.930 deg,    P =   -0.263 deg,    R =   -0.962 deg
};
P[641]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349982.826  mm,    Y =   114.408  mm,    Z =   -325826.150  mm,
    W =  -179.888 deg,    P =   -0.248 deg,    R =   -0.962 deg
};
P[642]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350010.183  mm,    Y =   77.496  mm,    Z =   -325826.345  mm,
    W =  -180.024 deg,    P =   -0.172 deg,    R =   -0.985 deg
};
P[643]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349916.816  mm,    Y =   130.140  mm,    Z =   -325826.365  mm,
    W =  -179.712 deg,    P =   -0.096 deg,    R =   -0.953 deg
};
P[644]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349878.673  mm,    Y =   105.774  mm,    Z =   -325826.649  mm,
    W =  -179.695 deg,    P =   0.028 deg,    R =   -0.952 deg
};
P[645]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  350094.161  mm,    Y =   -118.362  mm,    Z =   -325826.129  mm,
    W =  -180.045 deg,    P =   0.031 deg,    R =   -0.998 deg
};
P[646]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349868.486  mm,    Y =   92.821  mm,    Z =   -325826.685  mm,
    W =  -179.710 deg,    P =   0.060 deg,    R =   -0.955 deg
};
P[647]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349983.300  mm,    Y =   -63.110  mm,    Z =   -325826.649  mm,
    W =  -179.922 deg,    P =   0.180 deg,    R =   -0.981 deg
};
P[648]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349934.612  mm,    Y =   -15.316  mm,    Z =   -325826.682  mm,
    W =  -180.044 deg,    P =   0.187 deg,    R =   -0.981 deg
};
P[649]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349858.729  mm,    Y =   60.859  mm,    Z =   -325826.873  mm,
    W =  -179.792 deg,    P =   0.135 deg,    R =   -0.969 deg
};
P[650]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349974.774  mm,    Y =   -56.720  mm,    Z =   -325826.244  mm,
    W =  -179.947 deg,    P =   0.171 deg,    R =   -0.984 deg
};
P[651]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  349967.432  mm,    Y =   -51.345  mm,    Z =   -325826.266  mm,
    W =  -179.966 deg,    P =   0.157 deg,    R =   -0.987 deg
};
P[652]{
   GP1:
    UF : 0, UT : 6,      CONFIG : 'N U T, 0, 0, 0',
    X =  0.000  mm,    Y =   0.000  mm,    Z =   -225827.000  mm,
    W =  0.000 deg,    P =   0.000 deg,    R =   0.000 deg
};
/END
